const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const puppeteer=require(path.join(process.env.LOCALAPPDATA,'Temp/node_modules/puppeteer-core'));
const audit=require('./audit-function.js'),root=path.resolve(__dirname,'..'),out=path.join(root,'_review');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,pipe:true,args:['--no-sandbox','--disable-gpu']});
try{
 const page=await browser.newPage();await page.setViewport({width:1920,height:1080});const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));await page.setRequestInterception(true);page.on('request',r=>{if(/^https?:/.test(r.url())){network.push(r.url());r.abort();}else r.continue();});
 const url=pathToFileURL(path.join(root,'index.html')).href;await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>Reveal.isReady());await page.evaluate(async()=>{await deckReady;Reveal.configure({transition:'none'});});
 async function settle(){await page.evaluate(async()=>{RGWidgets.resize();await Promise.all(RGWidgets.instances.map(w=>w.ready));});await delay(25);}
 async function go(id){await page.evaluate(id=>Reveal.slide(Reveal.getSlides().findIndex(s=>s.id===id)),id);await settle();}
 async function check(){const a=await page.evaluate(audit),extra=await page.evaluate(()=>{const issues=[];for(const p of Reveal.getCurrentSlide().querySelectorAll('.rg-plot')){const b=p.getBoundingClientRect(),labels=[...p.querySelectorAll('.xtick text,.ytick text,.g-xtitle text,.g-ytitle text,.legendtext')].map(t=>({b:t.getBoundingClientRect(),text:t.textContent}));for(const {b:r,text}of labels)if(r.width&&r.height&&(r.left<b.left-2||r.right>b.right+2||r.top<b.top-2||r.bottom>b.bottom+2))issues.push({type:'chart-label-clipping',label:text});for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],c=labels[j];if(Math.min(a.b.right,c.b.right)-Math.max(a.b.left,c.b.left)>2&&Math.min(a.b.bottom,c.b.bottom)-Math.max(a.b.top,c.b.top)>2)issues.push({type:'chart-label-overlap',a:a.text,b:c.text});}}return issues;});a.issues.push(...extra);return a;}
 const count=await page.evaluate(()=>Reveal.getTotalSlides()),slides=[];for(let i=0;i<count;i++){await page.evaluate(i=>Reveal.slide(i),i);await settle();const s=await check();slides.push(s);await page.screenshot({path:path.join(out,`${String(i+1).padStart(2,'0')}-${s.slide}.png`)});}fs.writeFileSync(path.join(out,'initial-audit.json'),JSON.stringify({count,errors,network,slides},null,2));
 const responsive=[];for(const [width,height]of [[1366,768],[1024,768]]){await page.setViewport({width,height});for(let i=0;i<count;i++){await page.evaluate(i=>{Reveal.slide(i);Reveal.layout();},i);await settle();const s=await check();if(s.issues.length)responsive.push({viewport:[width,height],...s});}}await page.setViewport({width:1920,height:1080});
 let stateCount=0;const stateIssues=[];async function inspect(variant){await settle();const s=await check();if(s.issues.length)stateIssues.push({variant,...s});stateCount++;}
 const sources=await page.evaluate(()=>RGWidgets.instances.filter(w=>w.kind==='source').map(w=>({id:w.el.closest('section').id,sets:w.pointTraces.map(t=>t.name||'Observations')})));
 for(const s of sources){await go(s.id);for(const set of s.sets){if(s.sets.length>1)await page.select(`#${s.id} [data-setting="set"]`,set);const n=await page.$$eval(`#${s.id} [data-setting="point"] option`,es=>es.length);for(let i=1;i<=n;i++){await page.select(`#${s.id} [data-setting="point"]`,String(i));await inspect(s.id+'/'+set+'/'+i);}}
  if(await page.$(`#${s.id} [data-action="overlay"]`)){await page.click(`#${s.id} [data-action="overlay"]`);await inspect(s.id+'/overlay');}
  if(await page.$(`#${s.id} [data-setting="degree"]`)){const degrees=await page.$$eval(`#${s.id} [data-setting="degree"] option`,es=>es.map(e=>e.value));for(const degree of degrees){await page.select(`#${s.id} [data-setting="degree"]`,degree);await inspect(s.id+'/degree/'+degree);}}
 }
 await go('residual-lab');for(const b0 of [0,1.5,4])for(const b1 of [-1,2,5]){await page.evaluate(({b0,b1})=>{const w=RGWidgets.instances.find(w=>w.kind==='residual');w.exactOLS=null;w.setting('intercept').value=b0;w.setting('slope').value=b1;w.render();},{b0,b1});await inspect('residual/'+b0+'/'+b1);}
 await page.click('#residual-lab [data-action="fit"]');await settle();const coefficients=await page.evaluate(()=>RGWidgets.instances.find(w=>w.kind==='residual').currentCoefficients);const ref=require('./reference.json').lr_scatter;assert(Math.abs(coefficients[0]-ref.intercept)<1e-10&&Math.abs(coefficients[1]-ref.slope)<1e-10);await page.click('#residual-lab [data-action="segments"]');await inspect('residual/exact-fit-no-segments');assert.deepEqual(await page.evaluate(()=>RGWidgets.instances.find(w=>w.kind==='residual').currentCoefficients),coefficients);
 await go('bias-lab');for(const degree of [0,1,2,5,9])for(const n of [12,25,60])for(const seed of [1,7,23])for(const x of [-.8,0,.8]){await page.evaluate(({degree,n,seed,x})=>{const w=RGWidgets.instances.find(w=>w.kind==='bias');for(const [k,v]of Object.entries({degree,n,seed,x}))w.setting(k).value=v;w.render();},{degree,n,seed,x});await inspect('bias/'+[degree,n,seed,x].join('/'));}
 await go('tails-lab');for(const df of [3,10,23,88])for(const t of [-8,-3,-1,0,1,2.2,5,8]){await page.evaluate(({df,t})=>{const w=RGWidgets.instances.find(w=>w.kind==='tails');w.exactT=null;w.setting('df').value=df;w.setting('t').value=t;w.render();},{df,t});await inspect('tails/'+df+'/'+t);}await page.click('#tails-lab [data-action="source"]');await inspect('tails/course');assert(Math.abs(await page.evaluate(()=>RGWidgets.instances.find(w=>w.kind==='tails').currentP)/require('./reference.json').lr_maybe.p-1)<1e-10);
 await go('diagnostics-lab');for(const example of ['Well behaved','Curvature','Unequal variance','Serial pattern'])for(const axis of ['Fitted values','Observation order'])for(const seed of [1,7,23]){await page.evaluate(({example,axis,seed})=>{const w=RGWidgets.instances.find(w=>w.kind==='diagnostics');for(const [k,v]of Object.entries({example,axis,seed}))w.setting(k).value=v;w.render();},{example,axis,seed});await inspect('diagnostics/'+[example,axis,seed].join('/'));}
 const interactions=['Exact OLS button and residual toggle preserve coefficients','Source statistic button gives recomputed p-value'];
 // Real pointer interactions, including original source plots with supplied model traces.
 for(const id of ['scatter-lab','fit-lab','test-lab','overfit-lab','underfit-lab','uncertainty-lab','association-lab','bias-lab','tails-lab','diagnostics-lab']){
  await go(id);await page.click(`#${id} [data-action="pan"]`);assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.dragmode),'pan');await page.click(`#${id} [data-action="zoom"]`);
  const p=await page.$eval(`#${id} .rg-plot`,p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a._length*.2)*s,y:b.top+(y._offset+y._length*.2)*s,xx:b.left+(a._offset+a._length*.65)*s,yy:b.top+(y._offset+y._length*.7)*s};});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.xx,p.yy,{steps:7});await page.mouse.up();await delay(90);assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.autorange),false);await page.click(`#${id} [data-action="view"]`);await settle();assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.autorange),true);interactions.push(id+': pan, drag zoom and reset');
 }
 await go('fit-lab');await page.click('#fit-lab .legend .traces:first-child');await delay(350);assert.equal(await page.$eval('#fit-lab .rg-plot',p=>p.data[0].visible),'legendonly');interactions.push('Original chart legend toggle');
 await go('scatter-lab');const h=await page.$eval('#scatter-lab .rg-plot',p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a.l2p(p.data[0].x[0]))*s,y:b.top+(y._offset+y.l2p(p.data[0].y[0]))*s};});await page.mouse.move(h.x,h.y);await delay(120);assert(await page.$('#scatter-lab .hoverlayer .hovertext'));interactions.push('Original chart hover tooltip');
 // All original numerical coordinates survive Plotly styling unchanged.
 await page.evaluate(()=>{for(const w of RGWidgets.instances.filter(w=>w.kind==='source'))for(let i=0;i<w.raw.data.length;i++)for(const k of ['x','y'])if(JSON.stringify(w.plot.data[i][k])!==JSON.stringify(w.raw.data[i][k]))throw Error('Source coordinates changed');});
 await page.evaluate(()=>{document.activeElement.blur();Reveal.slide(0);});for(let i=1;i<count;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),count-1);for(const id of ['overfit-lab','bias-lab','uncertainty-lab','references']){await page.goto('about:blank');await page.goto(url+'#/'+id,{waitUntil:'load'});await page.waitForFunction(id=>Reveal.isReady()&&Reveal.getCurrentSlide().id===id,{},id);await page.evaluate(()=>deckReady);}
 const report={count,errors,offlineRequests:network,slides,responsive,stateIssues,stateCount,interactions,keyboardNavigation:true,directEntry:true};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({count,errors,network,issues:slides.filter(s=>s.issues.length),responsive,stateIssueCount:stateIssues.length,stateIssues:stateIssues.slice(0,5),stateCount,interactions:interactions.length},null,2));
 const files=slides.map((s,i)=>`${String(i+1).padStart(2,'0')}-${s.slide}.png`);fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>AIML · Regression · Gallery</title><style>body{margin:0;background:#0b0f17;color:#e8ecf4;font:18px system-ui}header{padding:24px}a{color:#45d6c0}img{display:block;width:100%;height:auto}figure{margin:0 0 30px}figcaption{padding:12px 24px}@media print{@page{size:1920px 1080px;margin:0}header,figcaption{display:none}figure{margin:0;break-after:page}img{height:1080px}}</style><header>Lesson 4 · Regression · ${count} slides · static previews<br><a href="../index.html">Open interactive presentation</a></header>${files.map((f,i)=>`<figure><img src="${f}" alt="Slide ${i+1}: ${slides[i].slide}"><figcaption>${i+1} / ${count} · ${slides[i].slide}</figcaption></figure>`).join('')}</html>`);await page.goto(pathToFileURL(path.join(out,'index.html')).href,{waitUntil:'load'});await page.pdf({path:path.join(out,'AIML-Regression-reviewed.pdf'),printBackground:true,preferCSSPageSize:true});assert.equal(errors.length+network.length+slides.filter(s=>s.issues.length).length+responsive.length+stateIssues.length,0,'Inspect audit.json for layout issues');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
