from pathlib import Path
import json
from html import escape
ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''):
    slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'):return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items):return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items):return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(t):return '<p class="takeaway">'+t+'</p>'
def math(t):return '<div class="formula">'+t+'</div>'
def diagram(k):return f'<div class="static-diagram" data-diagram="{k}"></div>'
def lab(id,title,kind,prompt,notes):add(id,'Interactive lab · Introduction to ML',title,f'<p class="lab-prompt">{prompt}</p><div class="ml-widget" data-kind="{kind}"></div>',notes,'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 3','Introduction to Machine Learning','<div class="cover-layout"><div><p class="eyebrow">Learn from examples. Predict beyond them.</p><h1 class="search-title grad">From data<br>to predictions.</h1><p class="cover-sub">Learning signals · Models · Generalization</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · How learning works</span><span>02 · Describe the data</span><span>03 · Evaluate new cases</span></div>','Follows the next course resource, 03_intro. Both original interactive plots retain all source coordinates. Four additional labs explore learning signals, self-supervised targets, exploration/exploitation and generalization.','cover-slide')
add('roadmap','The road ahead','Three questions organize the lecture',cols(card('What provides feedback?',bullets('Labels, structure or rewards.','Different signals define different learning settings.')),card('What are we modeling?',bullets('Observations and targets.','A model family and its parameters.'),'comp'),card('Will it work again?',bullets('Measure performance on unseen cases.','Distinguish fitting from generalizing.'),'stat')))
add('components','01 · How learning works','Learning needs more than a model',diagram('pipeline')+'<div class="card-grid compact">'+card('Data','<p>Examples and measurements: the study material.</p>')+card('Model','<p>A family of functions with adjustable parameters.</p>','comp')+card('Training algorithm','<p>A procedure that uses a learning signal to update the model.</p>','stat')+card('Evaluation','<p>A task-relevant assessment on appropriately held-out data.</p>','deep')+'</div>','The student/teacher analogy is helpful, but the model is not the entire learning system. The training procedure defines how evidence changes parameters; evaluation measures an explicitly chosen task.')
add('training-inference','01 · How learning works','Training changes the model; inference uses it',cols(card('Training',math('(examples, signal) → fitted parameters')+'<p>Adjust the model using the available data and objective.</p>'),card('Inference',math('new input → fitted model → prediction')+'<p>Apply the learned function to a new observation.</p>','stat'))+note('A useful prediction depends on the data, objective and evaluation—not just the algorithm.'))
add('signals','01 · Learning signals','Ask where the learning signal comes from','<table class="comparison"><thead><tr><th>Setting</th><th>Available signal</th><th>Example</th></tr></thead><tbody><tr><td>Supervised</td><td>Input–target pairs</td><td>Image → animal label</td></tr><tr><td>Unsupervised</td><td>Structure in observations</td><td>Group similar images</td></tr><tr><td>Self-supervised</td><td>Targets derived from the data</td><td>Predict a hidden token</td></tr><tr><td>Semi-supervised</td><td>Some labeled + some unlabeled data</td><td>Learn from both subsets</td></tr><tr><td>Reinforcement</td><td>Rewards from actions</td><td>Learn a decision policy</td></tr></tbody></table>'+note('These categories overlap. A single system may use several learning stages.'),'Self-supervision is often grouped under unsupervised learning because labels are not manually provided. Generative modeling can use supervised conditioning or self-supervised objectives. This taxonomy is a guide rather than a disjoint partition.')
add('supervised','01 · Learning signals','Supervised learning compares a prediction to a target',cols(math('x → f<sub>θ</sub>(x) = ŷ<br><br>compare ŷ with y'),card('The fertilizer example','<p>Input x: fertilizer level.</p><p>Target y: measured crop yield.</p><p>The discrepancy supplies feedback for training.</p>','stat'))+note('“Ground truth” is a reference measurement or annotation. It can still contain errors.'),'Labels may come from instruments, logs, expert annotation or other processes. They are not necessarily perfect or manually produced.')
add('regression-classification','01 · Learning signals','The output determines the prediction task',cols(card('Regression','<p>Predict a numerical quantity.</p>'+math('fertilizer level → crop yield')+'<p>Other examples: temperature, travel time.</p>','stat'),card('Classification','<p>Predict a category or its probability.</p>'+math('image → {cat, dog, bird}')+'<p>Class IDs such as 0, 1, 2 are labels, not measured magnitudes.</p>','comp'))+note('A number can encode a category. The meaning of the target matters.'),'The course focuses on continuous-response regression. Count prediction is also possible with appropriate regression models; numerical storage alone does not identify a task.')
add('unsupervised','01 · Learning signals','Without task labels, look for structure',cols(card('Clustering',diagram('clusters')+'<p>Group observations using a similarity definition.</p>'),card('Generative modeling',math('learn a distribution → sample new data')+'<p>Capture patterns that support generating plausible observations.</p>','comp'))+note('A cluster is not automatically a meaningful class. A generated sample need not copy a training example.'),'Clustering depends on representation, distance and modeling choices. Generative training is not universally reconstruction. Avoid claiming that unlabeled data always makes training cheaper or inherently harder.')
lab('signal-lab','Identify the signal, then reveal the reasoning','signals','Choose a scenario and a learning setting. Check your answer to see why it fits.','Added six-scenario concept check, including classification, regression, clustering, masking, semi-supervised data and reward-based action selection. Answers are fixed explanations, not model-generated judgments.')
add('self-supervised','01 · Learning signals','Create a target from the observation itself',cols(card('Mask part of an image',diagram('mask')+'<p>Use visible content to predict withheld content.</p>'),card('Predict the next token',math('“The crop needs” → “water”')+'<p>The next token in the recorded sequence becomes the target.</p>','stat'))+note('No manual task label is required, but there is still a training objective and a target.'),'Self-supervised objectives include generative and contrastive approaches. Masked reconstruction and next-token prediction are examples, not the whole category. Pretraining may be followed by supervised adaptation.')
lab('mask-lab','Build a self-supervised training pair','mask','Choose a sentence and which token to hide. Reveal the target that the original sentence supplies.','Added target-construction demonstration. This does not train or run a language model: it separates the observed input from the known training target. The correct target is what occurred in the source sentence, not the only plausible completion.')
add('semi-supervised','01 · Learning signals','Use the labeled and unlabeled parts together',cols(diagram('labels'),card('Two prediction goals','<p><strong>Transductive:</strong> infer labels for the particular unlabeled cases already available.</p><p><strong>Inductive:</strong> learn a rule that also applies to future cases.</p>','comp'))+note('Extra unlabeled data helps only when its structure is relevant to the task.'),'Semi-supervised learning uses both labeled and unlabeled data. Transduction and induction describe prediction goals; they are not restricted to this learning setting.')
add('weak-shift','01 · Learning signals','Weak labels and domain shift are different issues',cols(card('Weak supervision','<p>Learning signals may be incomplete, coarse or noisy.</p><p>Examples: image-level labels for object location; labels from imperfect rules.</p>','cyber'),card('Domain adaptation','<p>Training and deployment data differ.</p><p>Example: dog images from website A differ in lighting and compression from website B.</p>','comp'))+note('Both issues can occur together. New target classes additionally raise open-set recognition questions.'),'Corrects the course subsection that describes weak supervision primarily as distribution alignment. Zhou distinguishes incomplete, inexact and inaccurate supervision. The website A/B example describes domain shift; adaptation addresses this change. A changed distribution does not automatically imply failure.')
add('reinforcement','01 · Learning signals','Reinforcement learning learns which actions to take',cols(diagram('rl'),card('A different kind of feedback',bullets('Observe a state or context.','Choose an action.','Receive a reward and new experience.','Improve the decision policy.'),'stat'))+note('The objective concerns accumulated reward. Feedback may arrive after several decisions.'),'The course motivates reinforcement learning through chess. This presentation avoids the unsupported comparison of chess states with atoms in the universe. Offline reinforcement learning also exists; interaction is not required during every training procedure.')
lab('bandit-lab','Explore or exploit? Try three uncertain actions','bandit','Pull an arm yourself, or run an ε-greedy policy. Estimates change after every observed reward.','Added stationary three-armed Bernoulli bandit with reward probabilities 0.25, 0.50 and 0.75. It is a simple reinforcement-learning setting without state transitions or delayed rewards. Each arm is tried once before automated epsilon-greedy selection. Ties use seeded randomness. The finite run need not identify the best arm.')
add('domains','02 · Describe the data','Learning setting and data domain are separate axes',cols(card('Computer vision',bullets('Images and video.','Classify, locate or segment objects.')),card('Natural language',bullets('Text and token sequences.','Classify, tag or interpret meaning.'),'comp'),card('Multimodal learning',bullets('Combine text, images, audio or video.','Learn complementary representations.'),'stat'))+note('An image task can be supervised, self-supervised or reinforcement-based. The data type does not decide the learning signal.'))
add('vision','02 · Data domains','One scene, three kinds of visual output',diagram('vision')+'<div class="three-captions"><p><strong>Classification</strong><br>Which category is present?</p><p><strong>Detection</strong><br>Which objects, and where?</p><p><strong>Semantic segmentation</strong><br>Which class at each pixel?</p></div>','The vector scene is a conceptual illustration. Its boxes and regions are hand-authored teaching annotations, not outputs of a trained vision model. Semantic segmentation assigns class labels; instance segmentation additionally separates individual objects.')
add('language','02 · Data domains','Language tasks depend on context',cols(card('Classify a document','<p>“A late goal decided the final.”</p>'+math('topic → sports')),card('Tag or disambiguate','<p>“They <strong>bank</strong> the aircraft.”<br>bank → verb</p><p>“They sat on the river <strong>bank</strong>.”<br>bank → edge of a river</p>','comp'))+note('Text classification, part-of-speech tagging and word-sense disambiguation ask different questions.'),'The source uses genre and topic interchangeably; these are distinct label schemes. The slide explicitly uses topic classification.')
add('fertilizer','02 · A running regression problem','Predict yield before the crop grows',cols(diagram('field'),card('Define one observation','<p>Choose a plot and apply a fertilizer level.</p><p>Measure the yield after growing the crop.</p>'+math('(fertilizer level, crop yield)'),'stat'))+note('Prediction alone does not establish a causal effect. Study design determines what comparisons support.'),'Retains the agronomy example. Source numerical axes do not document physical units or data provenance. The deck treats the 25 points as course illustration data and does not claim measured field results or convert the original 0–1 fertilizer coordinates to physical doses.')
add('variable-types','02 · Variables and datasets','Variable type describes what values mean','<div class="card-grid">'+card('Quantitative · continuous','<p>Measured magnitude on a continuum.<br>Examples: height, temperature.</p>')+card('Quantitative · discrete','<p>A count or discrete quantity.<br>Examples: number of cars, defect count.</p>','stat')+card('Categorical · nominal','<p>Unordered categories.<br>Examples: soil type, country.</p>','comp')+card('Categorical · ordinal','<p>Ordered categories without assumed equal gaps.<br>Example: low, medium, high.</p>','deep')+'</div>'+note('Binary means two possible values. Numeric codes do not create a meaningful distance.'),'Age may be measured continuously or recorded in completed years; it is not intrinsically discrete. Binary variables may be nominal or ordinal depending on interpretation. Avoid using yes/no degree status as a general ordinal example.')
add('roles','02 · Variables and datasets','Predictors are inputs; the outcome is the target',cols(card('Predictors · x',math('x = [fertilizer, rainfall, soil pH]ᵀ')+'<p>Features available when the prediction is made.</p>'),card('Outcome · y',math('y = crop yield')+'<p>The quantity the model is asked to predict.</p>','stat'))+note('Choose roles for the task. The same variable may be an input in one task and an outcome in another.'),'Predictor does not imply statistical independence, and explanatory-variable terminology does not imply causation. Rainfall observed after prediction time cannot be used as if it were already known; forecasts and past measurements must be distinguished.')
add('dataset','02 · Variables and datasets','A dataset pairs each observation with its target',math('D = {(xᵢ, yᵢ)}ᵢ₌₁ⁿ')+'<table class="comparison"><thead><tr><th>Plot i</th><th>Fertilizer xᵢ</th><th>Yield yᵢ</th></tr></thead><tbody><tr><td>1</td><td>0.0000</td><td>1.9200</td></tr><tr><td>2</td><td>0.0417</td><td>1.7144</td></tr><tr><td>3</td><td>0.0833</td><td>2.0449</td></tr></tbody></table>'+note('Here n = 25 and m = 1: 25 observations, one predictor. Values shown are rounded from the course chart.'),'The first three rows reproduce the source values to four decimal places. Targets are available for supervised training; they are unknown for a new inference case.')
add('matrix','02 · Variables and datasets','Rows are observations; columns are features',cols(math('X ∈ ℝ<sup>n×m</sup><br><br>Xᵢⱼ = feature j of observation i'),math('y ∈ ℝⁿ<br><br>yᵢ = target of observation i'))+note('If xᵢ is a column vector, row i of the design matrix is xᵢᵀ.'),'Corrects the source display that stacks column observations without explicit transposes. Numerical matrix form requires a suitable representation for categorical, image or text data; raw categories do not automatically have a meaningful real-valued encoding.')
lab('observations-lab','Inspect the original fertilizer observations','observations','Hover to inspect values. Drag to zoom, use Pan to move, and Reset view to restore the full range.','Original nonlinear.json scatter plot, all 25 x/y coordinates preserved. Plotly remains fully interactive offline. The slide adds explicit zoom/pan/reset controls and a keyboard-accessible point inspector. The original horizontal axis title is retained; its physical interpretation is unspecified.')
add('hypotheses','03 · Models and generalization','A model family contains many possible functions',cols(card('Choose a family',math('f<sub>θ</sub>(x) = ax² + bx + c')+'<p>A quadratic family assumes a particular functional form.</p>'),card('Choose its parameters',math('θ = (a, b, c) ∈ ℝ³')+'<p>A parameter choice specifies one member of that family.</p>','comp'))+note('Training searches within a chosen family. Model selection compares families or settings.'),'The course calls a parameter setting a hypothesis. More commonly, the corresponding function is the hypothesis; both conventions are clarified here. The course curve is illustrative and is not asserted to be an optimal fit or quadratic.')
lab('hypothesis-lab','Compare the original observations and hypothesis','hypothesis','Toggle a trace using the legend. Inspect a point to compare its observed and predicted values.','Original nonlinear_mod.json: both 25-point traces retained exactly, including the illustrative hypothesis curve. Interactive hover, trace toggles, pan and zoom are preserved. The sidebar computes residuals and mean squared error against the provided curve, without claiming the source used a particular fitting algorithm.')
add('residuals','03 · Models and generalization','Residuals measure disagreement on the observed data',cols(math('ŷᵢ = f<sub>θ</sub>(xᵢ)<br>rᵢ = yᵢ − ŷᵢ'),card('One possible training loss',math('MSE = (1/n) Σᵢ (yᵢ − ŷᵢ)²')+'<p>Squaring makes signs irrelevant and emphasizes larger errors.</p>','stat'))+note('A lower training loss means a closer fit to these data. It does not establish better predictions on new cases.'),'MSE is a supplemental concrete score that prepares for the next Regression lecture. It has squared target units and is not appropriate for every task.')
add('noise','03 · Models and generalization','The same input can have different outcomes',cols(card('Sources of variation',bullets('Measurement imprecision.','Unobserved conditions such as soil or weather.','Intrinsic variability in the process.')),card('A useful simplified model',math('Y = f*(X) + ε')+'<p>The residual may include noise and model mismatch.</p>','comp'))+note('Do not assume every deviation is a measurement mistake that a larger model should fit.'),'The source emphasizes measurement error. This slide broadens the explanation to omitted predictors, irreducible variation and misspecification. No claim of zero-mean or independent noise is made without an assumption.')
add('generalization','03 · Models and generalization','Generalization is performance on new cases',cols(card('Fit the sample',math('small loss on D<sub>train</sub>')+'<p>The model has seen these observations during fitting.</p>'),card('Predict beyond the sample',math('small expected loss on new (X, Y)')+'<p>Performance depends on the deployment distribution.</p>','stat'))+note('The goal is not exact prediction for every possible input–output pair.'),'Corrects the source domain-wide approximation statement. In noisy problems the same input can have several possible targets. Generalization concerns expected or otherwise specified performance under a relevant distribution, not uniform exactness throughout the Cartesian product.')
add('splits','03 · Models and generalization','Give training, validation and testing different jobs',diagram('splits')+cols(card('Training','<p>Fit parameters and learned preprocessing.</p>'),card('Validation','<p>Compare choices such as model complexity.</p>','comp'),card('Test','<p>Estimate final performance after choices are fixed.</p>','stat'))+note('Split by time or group when future dates or new subjects are the real prediction target.'),'Supplemental practical evaluation guidance. Repeated use of test results for model choice compromises a final independent assessment. Use the validation set in the following interactive lab; it is intentionally not called a test set.')
lab('generalization-lab','Fit the training points; compare unseen validation points','generalization','Change polynomial degree or noise. The fitted curve uses training data only; compare both errors.','Added synthetic regression experiment. Training and validation are disjoint samples from y=2+1.2x−0.9x² plus independent seeded noise, on x in [−1,1]. Degrees 0,1,2,5,9 are fitted by least squares using Householder QR. Validation outcomes never enter fitting. Displaying and comparing validation results makes this model development, not a final test evaluation.')
add('leakage','03 · Models and generalization','Evaluation must match the intended use',cols(card('Keep unavailable information out',bullets('Fit scaling and imputation on training data.','Avoid duplicate or related cases across splits.','Do not use future measurements as known inputs.')),card('Watch for distribution change',bullets('Different cameras or acquisition conditions.','A new population or location.','A changing process over time.'),'cyber'))+note('A clean held-out score supports the tested conditions. It does not guarantee every future setting.'),'Data leakage and domain shift are distinct failure modes. This summary follows scikit-learn common-pitfalls guidance for split-before-fit preprocessing and the course website A/B example for domain shift.')
add('practice','Check your understanding','Name the signal, shape and evaluation target','<ol class="exercise-list"><li>A model predicts a hidden word from the surrounding text. Where does its target come from?</li><li>A dataset has 80 rows and 4 predictor columns. What are n, m and the shape of X?</li><li>A degree-9 curve fits training data better than a degree-2 curve. Which should you choose?</li><li>Dog photos on a new website have different lighting. Is this necessarily weak supervision?</li></ol>')
add('answers','Check your understanding','Explain the choices','<div class="card-grid">'+card('01 · Target','<p>From the original observed text. Hiding it constructs a self-supervised pair.</p>')+card('02 · Shape','<p>n = 80, m = 4.<br>X has shape 80 × 4; y has 80 entries for a single target.</p>','stat')+card('03 · Model choice','<p>Compare validation performance and task needs. Training error alone cannot decide.</p>','comp')+card('04 · Distribution','<p>This is domain shift. Weak supervision concerns incomplete, coarse or noisy learning signals.</p>','deep')+'</div>')
add('summary','Lesson 3 · Takeaways','Define the task before choosing the algorithm',cols(bullets('Identify the learning signal.','Describe observations, predictors and targets.','Choose a model family and fit its parameters.','Evaluate on data that represent new cases.','Treat good training fit as evidence about training only.'),diagram('cover'))+note('Next lecture: regression turns these ideas into concrete fitting methods.'))
add('references','Sources & further reading','Continue exploring',card('Primary course resource','<p><a href="https://www.aretor.it/courses/aiml2526/lessons/03_intro/" target="_blank" rel="noopener">AIML 2025/26 · Lesson 03 — Introduction to Machine Learning</a></p><p class="small">Original examples, terminology and both fertilizer plots.</p>')+card('Clarifications and extensions','<p><a href="https://doi.org/10.1093/nsr/nwx106" target="_blank" rel="noopener">Zhou · A Brief Introduction to Weakly Supervised Learning</a><br><a href="https://arxiv.org/abs/2006.08218" target="_blank" rel="noopener">Liu et al. · Self-supervised Learning: Generative or Contrastive</a><br><a href="https://scikit-learn.org/stable/common_pitfalls.html" target="_blank" rel="noopener">scikit-learn · Common pitfalls and evaluation leakage</a></p>','stat')+'<p class="small">Teaching notes and source mapping are included in the notes folder.<br>Use the HTML deck for interactivity. The PDF is a static handout.</p>')

html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 3 — Introduction to Machine Learning · AIML</title><link rel="stylesheet" href="lib/reveal/reset.min.css"><link rel="stylesheet" href="lib/reveal/reveal.min.css"><link rel="stylesheet" href="css/theme-base.css"><link rel="stylesheet" href="css/search.css"><link rel="stylesheet" href="css/ml.css"></head><body><div class="reveal"><div class="slides">'
for s in slides:html+=f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div><aside class="notes">{escape(s["notes"])}</aside></section>'
html+='</div></div><div class="lesson-tag">AIML · Lesson 3 — Introduction to Machine Learning</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav><script src="lib/reveal/reveal.min.js"></script><script src="lib/plotly.min.js"></script><script src="js/course-data.js"></script><script src="js/ml-engine.js"></script><script src="js/visuals.js"></script><script src="js/widgets.js"></script><script src="js/deck.js"></script></body></html>'
(ROOT/'index.html').write_text(html,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 3 — Introduction to Machine Learning\n\n'+''.join(f'## {i}. {s["title"]}\n\n{s["notes"] or "Discuss the examples before moving on."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],indent=2),encoding='utf-8')
print('Built',len(slides),'slides.')
