from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''):
    slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'):return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items):return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items):return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(text):return '<p class="takeaway">'+text+'</p>'
def math(text):return '<div class="formula">'+text+'</div>'
def diagram(kind):return f'<div class="static-diagram" data-diagram="{kind}"></div>'
def lab(id,title,kind,prompt,notes):add(id,'Interactive lab · Constraint satisfaction',title,f'<p class="lab-prompt">{prompt}</p><div class="cp-widget" data-kind="{kind}"></div>',notes,'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 2','Constraint satisfaction problems','<div class="cover-layout"><div><p class="eyebrow">Find values that work together</p><h1 class="search-title grad">Many choices.<br>One set of rules.</h1><p class="cover-sub">Variables · Domains · Constraints</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · Model the constraints</span><span>02 · Search and propagate</span><span>03 · Improve locally</span></div>','Follows course lesson 02_constraint. The original DFS and GAC interactions are retained in locally implemented widgets. Additional labs explore assignments, domain splitting, local search and simulated annealing. All presentation assets are local.','cover-slide')
add('map','The road ahead','Three ways to reason about possibilities',cols(card('Represent',bullets('Choose variables and domains.','State the rules precisely.','Recognize a valid assignment.'),'stat'),card('Reduce and search',bullets('Backtrack on partial assignments.','Remove unsupported values.','Split remaining domains.')),card('Improve locally',bullets('Start with a total assignment.','Count conflicts.','Move, restart or anneal.'),'comp'))+note('A CSP asks which values can coexist. A solution must satisfy <strong>every</strong> constraint.'))
add('applications','01 · Model the problem','Constraints turn a task into a model','<div class="card-grid">'+card('University timetable','<p>Variables: course time slots.<br>Rules: no student or lecturer clashes; respect availability.</p>','neural')+card('Robot planning','<p>Variables: task times and locations.<br>Rules: precedence, deadlines and reachable locations.</p>','stat')+card('Scene understanding','<p>Variables: labels for image regions.<br>Rules or preferences: plausible spatial relationships.</p>','comp')+card('Hard or soft?','<p>A hard constraint must hold.<br>A preference needs an objective, weight or soft-constraint model.</p>','deep')+'</div>','The source introduces scheduling, robot planning and scene understanding. Rules such as “sky above ground” can have exceptions; distinguish useful preferences from inviolable constraints. This lesson focuses on finite-domain hard CSPs, with local-search conflict scores used to seek feasibility.')
add('variables','01 · Model the problem','A variable chooses one value from its domain',cols(math('X ∈ dom(X)')+bullets('Binary: dom(X) = {0, 1}.','Color: dom(C) = {red, green, blue}.','Time slot: dom(T) = {Mon 9, Mon 11, …}.'),card('Compact representation',math('n variables · d values each<br>⇒ dⁿ total assignments')+'<p>10 binary variables describe<br><strong>2¹⁰ = 1024 possible states.</strong></p>','stat'))+note('Compactly describing many states does not make searching them cheap.'),'Use dom(X)={...}, not dom(X)∈{...}. Variables describe potential assignments; a chosen total assignment represents one state at a time. Unequal domain sizes produce the product of their cardinalities.')
add('assignments','01 · Model the problem','Partial and total assignments',cols(card('Partial context',math('A = {X₁ = 1}')+'<p>Only some variables have a value.</p><p>The unassigned variables are still open choices.</p>'),card('Total assignment',math('a = {X₁ = 1, X₂ = 2, X₃ = 0}')+'<p>Every variable has a value.</p><p>It is a solution only if every constraint holds.</p>','stat'))+note('For domains of sizes 3 and 2, there are <strong>3 × 2 = 6</strong> total assignments.'),'A single assignment and a total assignment are also partial assignments in the inclusive mathematical sense. Restricting a total assignment to a constraint’s scope supplies the values needed to evaluate that constraint.')
add('constraints','01 · Model the problem','A constraint has a scope and a truth value','<div class="card-grid">'+card('Unary · one variable',math('X₁ < 2')+'<p>scope = {X₁}</p>','stat')+card('Binary · two variables',math('X₃ < X₁')+'<p>scope = {X₃, X₁}</p>')+card('Ternary · three variables',math('X₁ + X₂ = X₃')+'<p>scope = {X₁, X₂, X₃}</p>','comp')+card('Evaluation','<p>True: the assigned values satisfy it.<br>False: they violate it.<br>Pending: its scope is not fully assigned.</p>','deep')+'</div>','The basic DFS solver evaluates a constraint when all variables in its scope are assigned. Pending is not false. Propagation can nevertheless reason about domains before a complete scope is assigned, by looking for support.')
add('definition','01 · Model the problem','A CSP is variables, domains and constraints',math('P = (X, dom, C)')+cols(card('Variables and domains','<p>X = {X₁, X₂, X₃}<br>dom(Xᵢ) = {0, 1, 2}</p>'),card('Constraints','<p>X₁ &lt; 2<br>X₂ &gt; 0<br>X₃ &lt; X₁</p>','comp'))+note('The course example has 27 total assignments and exactly <strong>two solutions</strong>.'),'The solutions are (X1,X2,X3)=(1,1,0) and (1,2,0). We retain this example throughout the original DFS and GAC demonstrations. Finding one solution, finding all solutions and proving unsatisfiability are distinct stopping requirements.')
lab('assignment-lab','Try an assignment · which rules can be checked?','assignment','Change a value, or leave it unassigned. Pending constraints must not be treated as violations.','Added interactive assignment evaluator for the original three-variable CSP. The selectors include an unassigned value. Every constraint reports true, false or pending, and the summary distinguishes total solutions from consistent partial contexts.')
add('generate-test','02 · Systematic solving','Generate-and-test checks complete candidates',cols('<ol class="steps"><li>Generate a total assignment.</li><li>Evaluate every constraint.</li><li>Keep it if all constraints hold.</li><li>Repeat until the search is complete.</li></ol>',card('The combinatorial cost',math('4¹⁵ = 1,073,741,824')+'<p>Fifteen variables with four choices each already produce over one billion candidates.</p>','cyber'))+note('A partial contradiction is enough to reject all of its completions.'),'Generate-and-test is complete for finite domains when all assignments are enumerated. Worst-case candidate count is the product of domain sizes; evaluating constraints adds per-candidate cost. Backtracking gains efficiency by evaluating failures earlier.')
add('backtracking','02 · Systematic solving','Backtracking rejects bad branches early',cols(bullets('Maintain a partial assignment: the context.','Assign the next variable a candidate value.','Evaluate constraints whose scope is complete.','On a violation, undo the choice and try another.'),card('In the course example',math('X₁ = 2 ⇒ X₁ < 2 is false')+'<p>All nine completions of this context can be rejected immediately.</p>','stat'))+note('Keep exploring after a solution if the task is to find <strong>all</strong> solutions.'))
add('dfs-code','02 · Systematic solving','A recursive solver for all solutions',cols('<pre class="pseudocode"><code>solve(context, remaining):\n    if any evaluable rule is false:\n        return []\n    if remaining is empty:\n        return [context]\n    choose X from remaining\n    answers ← []\n    for value in domain(X):\n        answers += solve(context + X=value,\n                         remaining - X)\n    return answers</code></pre>',card('The stopping cases',bullets('False rule: prune this branch.','No variables left: record a solution.','Otherwise: extend the context.'))),'All branch contexts are copied or correctly restored, so sibling branches do not inherit assignments. In the basic algorithm, satisfied fully assigned constraints need not be re-evaluated below that context. The implementation keeps predicate functions rather than evaluating source strings.')
lab('dfs-lab','DFS solver · inspect the assignment tree','dfs','Step through the original example. Hover or focus a node to inspect its context and constraint results.','Preserves the original 22-node pruned assignment tree, ascending value order, constraint inspection, current context and accumulated solution list. Failed branches have no descendants. Back restores the historical solution list. Reverse value order is an added comparison setting; default reproduces the source tree.')
add('ordering','02 · Systematic solving','Good ordering exposes contradictions sooner',cols(card('Variable order',bullets('Choose a variable likely to fail early.','Minimum remaining values (MRV): choose the smallest remaining domain.','Use degree as a possible tie-break.')),card('Value order',bullets('Try values that leave more options for neighbors.','Least-constraining value can help find an early solution.','Ordering changes effort, not the solution set.'),'comp'))+note('The course lab keeps X₁, X₂, X₃ fixed so the original traversal is easy to follow.'),'MRV, degree and least-constraining value are supplemental heuristics. They are not implemented in the small DFS demo; its toggle only reverses value order. Correct exhaustive backtracking with finite domains remains complete regardless of ordering.')
add('propagation','02 · Reduce the domains','Remove impossible values before branching',cols(math('A < B<br>dom(A) = dom(B) = {1,2,3,4}'),card('Two immediate deductions','<p>A = 4 has no larger value of B.<br><strong>Remove 4 from dom(A).</strong></p><p>B = 1 has no smaller value of A.<br><strong>Remove 1 from dom(B).</strong></p>','stat'))+note('A deleted value has no supporting combination for a constraint.'),'Do not say A=4 is intrinsically false. It is unsupported relative to the current domain of B and constraint A<B. Domain pruning preserves solutions and can trigger deductions elsewhere.')
add('network','02 · Reduce the domains','A constraint network is bipartite',cols(diagram('network'),bullets('Circles or ovals represent variables.','Rectangles represent constraints.','Connect X to c when X belongs to scope(c).','A k-ary constraint has k incident arcs.')),'The source shows A<B and B<C as a bipartite factor-style network. These arcs indicate participation in a constraint, not legal actions or a path-search direction. The GAC lab uses the original three-variable network with four variable–constraint arcs.')
add('support','02 · Reduce the domains','Every remaining value needs some support',math('For every x ∈ dom(X), there exists a tuple<br>for the other variables that satisfies c.')+cols(card('Supported','<p>For A &lt; B, value A = 2 is supported by B = 3 (or 4).</p>','stat'),card('Unsupported','<p>A = 4 has no support when dom(B) = {1,2,3,4}.</p>','cyber'))+note('“For every value, some supporting tuple” does <strong>not</strong> mean every tuple must satisfy the rule.'),'Generalized arc consistency applies to arbitrary constraint arity. Unary support is just satisfaction of that unary rule. For k-ary constraints the support search considers the other k−1 domains; the teaching engine uses exhaustive support enumeration because its examples are small.')
add('gac','02 · Reduce the domains','GAC revises arcs until no more pruning occurs',cols('<ol class="steps"><li>Put all variable–constraint arcs in a worklist.</li><li>Take an arc (X, c).</li><li>Remove X values with no support for c.</li><li>If X shrinks, enqueue affected neighboring arcs.</li><li>Repeat until the worklist is empty.</li></ol>',card('What it returns','<p>A collection of pruned domains.</p><p>It does <strong>not</strong> generally enumerate satisfying assignments.</p>','comp'))+note('The network stays intact. An arc is removed from the <strong>worklist</strong>, not deleted from the problem.'),'The page’s algorithm output heading suggests assignments, but GAC returns domains. We implement the re-enqueue rule for changed domains, rather than a hard-coded four-step demonstration. Stop early on an empty domain, or reach a fixed point when the worklist is empty.')
lab('gac-lab','GAC · prune values and update the worklist','gac','Begin with the course example. Then choose the chain to see a previously processed arc return.','Retains the original GAC example, four arcs, worklist, domain display and highlighted selected arc. The full algorithm also supports the source chain example and the source arc-consistent contradiction. The sidebar shows actual support witnesses for the selected arc. Back restores domains and queue exactly.')
add('requeue','02 · Reduce the domains','A changed domain can invalidate old support',cols(diagram('chain'),card('A < B, B < C','<p>Revising B against B &lt; C can remove its largest value.</p><p>A value previously supported by that B value may now be unsupported.</p><p>Revisit <strong>(A, A &lt; B)</strong>.</p>','stat'))+note('Propagation continues through the network; it is not limited to one pass over the arcs.'),'From domains {1,2,3,4}, chain propagation reaches A={1,2}, B={2,3}, C={3,4}. The exact worklist order is not unique. The widget processes FIFO and suppresses duplicate queued arcs. After a split, this implementation safely starts with all arcs; an optimized implementation can seed only affected arcs and still propagate onward.')
add('gac-outcomes','02 · Reduce the domains','Three outcomes at the fixed point',cols(card('An empty domain','<p>No value can work for some variable.</p><p class="orange"><strong>This branch has no solution.</strong></p>','cyber'),card('All singleton domains','<p>Every variable has exactly one value, and all arcs are consistent.</p><p class="teal"><strong>A solution is determined.</strong></p>','stat'),card('Nonempty, some non-singleton','<p>There are still choices.</p><p><strong>A solution may or may not exist.</strong></p>','comp')),'The third case does not require any singleton domain; all domains may have multiple values. All-singleton domains imply a solution only after consistency is established. Empty domains immediately certify failure in the current branch.')
add('consistent-unsat','02 · Reduce the domains','Local support does not imply global agreement',cols(math('X₁ = X₂<br>X₂ = X₃<br>X₁ ≠ X₃'),'<p>Every domain is {1,2,3,4}.</p>'+bullets('Every equality value has an equal partner.','Every inequality value has a different partner.','But the two equalities force X₁ = X₃.'))+note('All arcs are consistent, yet the CSP is <strong>unsatisfiable</strong>.'),'This is the original counterexample. Support witnesses for different constraints need not agree on a single shared total assignment. Try it in both the GAC and domain-splitting labs: GAC leaves the domains unchanged; complete splitting proves failure.')
add('splitting','02 · Search after propagation','Split one domain and propagate each branch',cols(math('dom(X) = {1,2,3,4}<br>↙　　　　　　　　↘<br>{1,2}　　　　　　{3,4}'),bullets('Choose a domain with more than one value.','Partition it into nonempty, disjoint parts.','Copy the domains for each branch.','Run GAC, then split again if necessary.'))+note('Explore both parts to retain every solution. Prune any branch that develops an empty domain.'),'The two sets must cover the original domain. Finite domains plus exhaustive recursion make the solver complete. It finds all solutions and can prove unsatisfiability. The implementation partitions the first non-singleton domain in half and reruns full GAC per branch.')
lab('split-lab','Domain splitting · turn pruning into a solver','split','The course problem branches on X₂. Switch to the contradiction: every branch eventually fails.','Added live solver using genuine GAC at every branch. Each tree node shows the split that produced it, and the sidebar shows its propagated domains. Both solutions of the course example are found; the source contradiction has zero solutions. Branch domains are independent copies.')
add('local-intro','03 · Local search','Start complete. Repair what is wrong.','<p class="chapter-lead">Systematic search builds a valid assignment.<br>Local search modifies a complete candidate.</p>'+math('E(a) = number of violated constraints'),'Local search uses total assignments, even when they violate constraints. Neighborhoods commonly change one variable at a time. The score E is an objective used to seek feasibility; a satisfying assignment has score zero.','chapter-slide')
add('conflicts','03 · Local search','Use conflicts as a score',cols(diagram('coloring'),card('A small graph-coloring CSP','<p>Variables: A, B, C, D.<br>Domains: red, green, blue.<br>Rules: adjacent vertices must differ.</p>'+math('E(a) = 0 ⇒ solution'),'stat'))+note('A move changes one variable’s color. A conflicting edge contributes one to E.'),'Added graph: edges AB, BC, CD, DA and AC. There is no BD edge. Vertex labels include color initials so color is not the only cue. The graph is 3-colorable; the plateau initialization is A=red, B=green, C=red, D=blue, with one conflict on AC.')
add('local-loop','03 · Local search','A local search loop needs stopping rules',cols('<pre class="pseudocode"><code>repeat for each permitted restart:\n    a ← initial total assignment\n    repeat within the step budget:\n        if conflicts(a) == 0: return a\n        propose a neighboring assignment\n        accept or reject it by the policy\nreturn "no solution found in this run"</code></pre>',card('Two distinct outcomes','<p><strong>Zero conflicts:</strong> a verified solution.</p><p><strong>Budget exhausted:</strong> no solution found yet.</p><p>Failure to find is not a proof of impossibility.</p>','cyber')),'The demos use a 40-step budget and seeded randomness for reproducible traces. A best-improvement run may stop sooner at a plateau. Reset replays the same selected seed; choosing another seed gives a new run. No finite-budget success guarantee is implied.')
add('random','03 · Local search','Random sampling and random walk',cols(card('Random sampling',bullets('Draw a new total assignment.','Test all constraints.','Repeat independently.'),'comp'),card('Random walk',bullets('Start with a total assignment.','Change one randomly chosen variable.','Keep the proposed move, even if it is worse.')))+note('With independent uniform samples, success after N draws is 1 − (1 − q)ᴺ, where q is the fraction of solutions.'),'For a finite satisfiable space with full-support independent sampling, success probability tends to one as samples tend to infinity. This is not a guarantee within a finite number of draws. Random-walk reachability depends on the move graph. Each demo walk chooses a uniformly random variable and a different color; equal domain sizes make this equivalent to a uniform variable–value move.')
add('improvement','03 · Local search','Best improvement can stop before a solution',cols(card('Strict greedy descent',bullets('Evaluate one-variable neighbors.','Choose a neighbor with the fewest conflicts.','Move only if its score is strictly smaller.')),card('A plateau at E = 1','<p>In the added coloring example, no single-variable move improves the initial score.</p><p>A sideways move can still open a route to a solution.</p>','cyber'))+note('We label the strict variant explicitly; other best-neighbor policies may permit equal or worse moves.'),'The course presents strict improvement, whereas the textbook also discusses best-neighbor versions that allow sideways/worse moves. Our Best improvement setting follows the course’s strict interpretation and stops on its demonstrated plateau. Tabu and annealing are separate policies and can accept non-improving changes.')
lab('local-lab','Local search · compare movement policies','local','Try strict improvement on the plateau, then random walk, tabu or annealing. Change the seed to compare runs.','Added interactive coloring simulation with random sampling, random walk, strict best improvement, tabu tenure 2 with aspiration for a new best score, and simulated annealing. The default plateau stalls strict improvement at one conflict. All states retain exact scores and conflicts; Back replays the same seeded trajectory.')
add('escaping','03 · Local search','Ways to leave a local minimum','<div class="card-grid">'+card('Random restart','<p>Replace the whole assignment and begin elsewhere.</p>','comp')+card('Random step','<p>Occasionally accept a random local change, even if it is worse.</p>')+card('Tabu memory','<p>Avoid changing recently modified variables. An aspiration rule can allow a new best solution.</p>','stat')+card('Temperature','<p>Use a controlled probability of accepting a worse candidate.</p>','deep')+'</div>','The local lab implements tabu tenure two. It chooses a best admissible one-variable neighbor; ties use seeded randomness. Tabu may accept equal or worse scores and is not restricted to strict descent. Random restart is explained here; choose a different initialization or seed in the lab to compare starting trajectories.')
add('annealing','03 · Local search','Simulated annealing sometimes accepts worse moves',math('ΔE = E(candidate) − E(current)')+cols(card('Better or equal',math('ΔE ≤ 0 ⇒ accept'),'stat'),card('Worse',math('P(accept) = exp(−ΔE / T)')+'<p>Compare a uniform draw u ∈ [0,1) with this probability.</p>','cyber'))+note('For T &gt; 0, the combined rule is <strong>min(1, exp(−ΔE / T))</strong>.'),'This specifies an acceptance probability, rather than merely a proportional Gibbs weight. It is the standard rule for the symmetric proposal used here. Equal-score moves have probability one at positive temperature. The local lab uses uniform one-variable color proposals and geometric cooling.')
lab('anneal-lab','Annealing · temperature changes the decision','anneal','Vary the temperature, score change and test draw. The highlighted point lies on the acceptance curve.','Added interactive probability explorer. The draw is a user-controlled test value, not a newly sampled random number. The graph shows acceptance versus ΔE at the current temperature; inputs update the curve, point, probability and accept/reject decision. The live local-search lab performs actual seeded proposals and draws.')
add('cooling','03 · Local search','Cooling shifts the balance toward improvement',cols(diagram('cooling'),bullets('High T: worse moves are accepted more often.','Low T: large score increases become unlikely.','Fast cooling can freeze the search too early.','Choose a schedule and a practical stopping budget.'))+note('The lab uses Tₖ = 2 × 0.92ᵏ. This finite schedule does not guarantee a global optimum.'),'The sketch illustrates geometric cooling, not a theorem about convergence. The acceptance explorer shows exact probabilities for individual moves. Guaranteed asymptotic convergence requires restrictive conditions and very slow cooling; we do not imply that the teaching schedule provides it.')
add('comparison','Putting it together','Match the solver to the required answer','<table class="comparison"><thead><tr><th>Method</th><th>Works with</th><th>What completion establishes</th></tr></thead><tbody><tr><td>Generate-and-test</td><td>Total assignments</td><td>All solutions, if exhaustively enumerated</td></tr><tr><td>Backtracking</td><td>Partial contexts</td><td>All solutions, if all branches explored</td></tr><tr><td>GAC alone</td><td>Domains and supports</td><td>Pruned domains; may remain inconclusive</td></tr><tr><td>GAC + splitting</td><td>Branches of domain restrictions</td><td>All solutions or a proof of none*</td></tr><tr><td>Local search</td><td>A changing total assignment</td><td>A solution if E = 0; otherwise inconclusive</td></tr></tbody></table>'+note('* For finite domains and exhaustive splitting.'))
add('practice','Check your understanding','Predict, then verify in a lab','<ol class="exercise-list"><li>With X₁ = 1 only, which course constraints can be evaluated?</li><li>After course GAC, what are the three domains? Why is the answer not a single assignment?</li><li>Why does the equality/equality/inequality example survive GAC?</li><li>For ΔE = 2, how does acceptance change from T = 4 to T = 0.5?</li></ol>')
add('answers','Check your understanding','Explain the deductions','<div class="card-grid">'+card('01 · Complete scope','<p>X₁ &lt; 2 is true.<br>X₂ &gt; 0 and X₃ &lt; X₁ are pending.</p>')+card('02 · Remaining choices','<p>X₁ = {1}, X₂ = {1,2}, X₃ = {0}.<br>X₂ still has two choices; both yield solutions.</p>','stat')+card('03 · Different witnesses','<p>Each constraint has support considered separately, but no single assignment satisfies all three.</p>','comp')+card('04 · Temperature','<p>At T = 4: exp(−0.5) ≈ 0.607.<br>At T = 0.5: exp(−4) ≈ 0.018.<br>Cooling makes this worse move less likely.</p>','deep')+'</div>')
add('summary','Lesson 2 · Takeaways','Represent, prune, branch — or repair',cols(bullets('A CSP combines variables, domains and constraints.','Backtracking rejects inconsistent contexts early.','GAC removes unsupported values.','Domain splitting completes finite systematic search.','Local search repairs candidates; zero conflicts certifies success.'),diagram('cover'))+note('Always distinguish <strong>“no solution exists”</strong> from <strong>“this run did not find one.”</strong>'))
add('references','Sources & further reading','Continue exploring',card('Primary course resource','<p><a href="https://www.aretor.it/courses/aiml2526/lessons/02_constraint/" target="_blank" rel="noopener">AIML 2025/26 · Lesson 02 — Constraint Satisfaction Problems</a></p><p class="small">Definitions, course CSP, original DFS and GAC interactions, domain splitting and local search.</p>')+card('Textbook reference','<p><a href="https://artint.info/3e/html/ArtInt3e.Ch4.html" target="_blank" rel="noopener">Poole &amp; Mackworth · Artificial Intelligence: Foundations of Computational Agents, 3rd ed. · Chapter 4</a></p>','stat')+'<p class="small">Slide notes and source corrections are in the notes folder.<br>Use the HTML deck for interactivity; the PDF and gallery contain static previews.</p>')

html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 2 — Constraint Satisfaction · AIML</title><link rel="stylesheet" href="lib/reveal/reset.min.css"><link rel="stylesheet" href="lib/reveal/reveal.min.css"><link rel="stylesheet" href="css/theme-base.css"><link rel="stylesheet" href="css/search.css"><link rel="stylesheet" href="css/csp.css"></head><body><div class="reveal"><div class="slides">'
for s in slides:html+=f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div></section>'
html+='</div></div><div class="lesson-tag">AIML · Lesson 2 — Constraint Satisfaction</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav><script src="lib/reveal/reveal.min.js"></script><script src="js/csp-engine.js"></script><script src="js/visuals.js"></script><script src="js/widgets.js"></script><script src="js/deck.js"></script></body></html>'
(ROOT/'index.html').write_text(html,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 2 — Constraint satisfaction problems\n\n'+''.join(f'## {i}. {s["title"]}\n\n{s["notes"] or "Use the slide to connect the preceding definitions and examples."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],indent=2),encoding='utf-8')
print('Built',len(slides),'slides.')
