const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const puppeteer=require(path.join(process.env.LOCALAPPDATA,'Temp/node_modules/puppeteer-core'));
const audit=require('./audit-function.js'),root=path.resolve(__dirname,'..'),out=path.join(root,'_review');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,pipe:true,args:['--no-sandbox','--disable-gpu']});
try{
 const page=await browser.newPage();await page.setViewport({width:1920,height:1080});const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.setRequestInterception(true);page.on('request',r=>{if(/^https?:/.test(r.url())){network.push(r.url());r.abort();}else r.continue();});
 const url=pathToFileURL(path.join(root,'index.html')).href;
 await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>Reveal.isReady());await page.evaluate(async()=>{await deckReady;Reveal.configure({transition:'none'});});
 async function settle(){await page.evaluate(async()=>{MLWidgets.resize();await Promise.all(MLWidgets.instances.map(w=>w.ready));});await delay(40);}
 async function go(id){await page.evaluate(id=>Reveal.slide(Reveal.getSlides().findIndex(s=>s.id===id)),id);await settle();}
 async function check(){const r=await page.evaluate(audit);const plotIssues=await page.evaluate(()=>{
  const issues=[];for(const p of Reveal.getCurrentSlide().querySelectorAll('.ml-plot')){const b=p.getBoundingClientRect();for(const t of p.querySelectorAll('.xtick text,.ytick text,.g-xtitle text,.g-ytitle text,.legendtext')){const r=t.getBoundingClientRect();if(r.width&&r.height&&(r.left<b.left-2||r.right>b.right+2||r.top<b.top-2||r.bottom>b.bottom+2))issues.push({type:'chart-label-clipping',label:t.textContent});}}
  return issues;
 });r.issues.push(...plotIssues);return r;}
 const count=await page.evaluate(()=>Reveal.getTotalSlides()),slides=[];
 for(let i=0;i<count;i++){await page.evaluate(i=>Reveal.slide(i),i);await settle();await page.evaluate(()=>{if(Reveal.getCurrentSlide().id==='bandit-lab'){const w=MLWidgets.instances.find(w=>w.kind==='bandit');for(let j=0;j<20;j++)w.advance();w.render();}});const s=await check();slides.push(s);await page.screenshot({path:path.join(out,`${String(i+1).padStart(2,'0')}-${s.slide}.png`)});}
 fs.writeFileSync(path.join(out,'initial-audit.json'),JSON.stringify({count,errors,network,slides},null,2));
 const responsive=[];for(const [width,height]of [[1366,768],[1024,768]]){await page.setViewport({width,height});for(let i=0;i<count;i++){await page.evaluate(i=>{Reveal.slide(i);Reveal.layout();},i);await settle();const s=await check();if(s.issues.length)responsive.push({viewport:[width,height],...s});}}
 await page.setViewport({width:1920,height:1080});const stateIssues=[];let stateCount=0;async function inspect(variant){await settle();const s=await check();if(s.issues.length)stateIssues.push({variant,...s});stateCount++;}
 await go('signal-lab');for(let i=1;i<=6;i++)for(const answer of ['Supervised','Unsupervised','Self-supervised','Semi-supervised','Reinforcement']){await page.select('[data-kind="signals"] [data-setting="scenario"]',String(i));await page.select('[data-kind="signals"] [data-setting="answer"]',answer);await page.click('[data-kind="signals"] [data-action="check"]');await inspect('signals/'+i+'/'+answer);}
 await go('mask-lab');for(let sentence=1;sentence<=3;sentence++){await page.select('[data-kind="mask"] [data-setting="sentence"]',String(sentence));const n=await page.$$eval('[data-kind="mask"] [data-setting="token"] option',e=>e.length);for(let i=1;i<=n;i++){await page.select('[data-kind="mask"] [data-setting="token"]',String(i));await page.click('[data-kind="mask"] [data-action="reveal"]');await inspect('mask/'+sentence+'/'+i);assert.equal(await page.$eval('.target-token',e=>e.textContent),await page.evaluate(({sentence,i})=>ML.sentences[sentence-1].split(' ')[i-1],{sentence,i}));}}
 await go('bandit-lab');for(const seed of ['1','7','23'])for(const eps of ['0','0.1','0.3','1']){await page.select('[data-kind="bandit"] [data-setting="seed"]',seed);await page.select('[data-kind="bandit"] [data-setting="epsilon"]',eps);await page.evaluate(()=>{const w=MLWidgets.instances.find(w=>w.kind==='bandit');w.revealed=true;});for(let i=0;i<=60;i++){await page.evaluate(i=>{const w=MLWidgets.instances.find(w=>w.kind==='bandit');if(i)w.advance();w.render();},i);await inspect('bandit/'+seed+'/'+eps+'/'+i);}}
 for(const id of ['observations-lab','hypothesis-lab']){await go(id);for(let i=1;i<=25;i++){await page.select(`#${id} [data-setting="point"]`,String(i));await inspect(id+'/'+i);}}
 await go('generalization-lab');for(const degree of ['0','1','2','5','9'])for(const seed of ['1','7','23'])for(const noise of ['0','0.25','0.6']){await page.select('[data-kind="generalization"] [data-setting="degree"]',degree);await page.select('[data-kind="generalization"] [data-setting="seed"]',seed);await page.select('[data-kind="generalization"] [data-setting="noise"]',noise);await page.evaluate(()=>{const w=MLWidgets.instances.find(w=>w.kind==='generalization');w.revealed=true;w.render();});await inspect('fit/'+degree+'/'+seed+'/'+noise);}
 const interactions=[];
 await go('bandit-lab');await page.click('[data-kind="bandit"] [data-action="reset"]');await page.click('[data-kind="bandit"] [data-action="armB"]');assert.equal(await page.evaluate(()=>MLWidgets.instances.find(w=>w.kind==='bandit').b.state.arm),1);await page.click('[data-kind="bandit"] [data-action="back"]');assert.equal(await page.evaluate(()=>MLWidgets.instances.find(w=>w.kind==='bandit').b.index),0);await page.click('[data-kind="bandit"] [data-action="next"]');assert.equal(await page.evaluate(()=>MLWidgets.instances.find(w=>w.kind==='bandit').b.index),1);await page.click('[data-kind="bandit"] [data-action="play"]');await delay(450);assert(await page.evaluate(()=>MLWidgets.instances.find(w=>w.kind==='bandit').b.index>=2));await go('title');assert(await page.evaluate(()=>!MLWidgets.instances.find(w=>w.kind==='bandit').running));interactions.push('Bandit: manual pull, back/next replay, play, reset and pause on leaving');
 for(const id of ['observations-lab','hypothesis-lab','generalization-lab']){
  await go(id);await page.click(`#${id} [data-action="pan"]`);assert.equal(await page.$eval(`#${id} .ml-plot`,e=>e._fullLayout.dragmode),'pan');await page.click(`#${id} [data-action="zoom"]`);
  const pos=await page.$eval(`#${id} .ml-plot`,p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a._length*.25)*s,y:b.top+(y._offset+y._length*.25)*s,xx:b.left+(a._offset+a._length*.65)*s,yy:b.top+(y._offset+y._length*.7)*s};});
  await page.mouse.move(pos.x,pos.y);await page.mouse.down();await page.mouse.move(pos.xx,pos.yy,{steps:8});await page.mouse.up();await delay(100);assert.equal(await page.$eval(`#${id} .ml-plot`,e=>e._fullLayout.xaxis.autorange),false);await page.click(`#${id} [data-action="view"]`);await settle();assert.equal(await page.$eval(`#${id} .ml-plot`,e=>e._fullLayout.xaxis.autorange),true);interactions.push(id+': actual drag zoom, pan control and reset');
 }
 await go('hypothesis-lab');await page.click('#hypothesis-lab .legend .traces:first-child');await delay(400);assert.equal(await page.$eval('#hypothesis-lab .ml-plot',e=>e.data[0].visible),'legendonly');interactions.push('Original hypothesis chart: legend toggles');
 // Actual pointer hover over the first original observation.
 await go('observations-lab');const hover=await page.$eval('#observations-lab .ml-plot',p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a.l2p(p.data[0].x[0]))*s,y:b.top+(y._offset+y.l2p(p.data[0].y[0]))*s};});await page.mouse.move(hover.x,hover.y);await delay(150);assert(await page.$('#observations-lab .hoverlayer .hovertext'));interactions.push('Original scatter: pointer hover tooltip');
 await page.evaluate(()=>{document.activeElement.blur();Reveal.slide(0);});for(let i=1;i<count;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),count-1);
 for(const id of ['bandit-lab','hypothesis-lab','generalization-lab','references']){await page.goto('about:blank');await page.goto(url+'#/'+id,{waitUntil:'load'});await page.waitForFunction(id=>Reveal.isReady()&&Reveal.getCurrentSlide().id===id,{},id);await page.evaluate(()=>deckReady);}
 const report={count,errors,offlineRequests:network,slides,responsive,stateIssues,stateCount,interactions,keyboardNavigation:true,directEntry:true};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify({count,errors,network,issues:slides.filter(s=>s.issues.length),responsive,stateIssueCount:stateIssues.length,stateIssues:stateIssues.slice(0,5),stateCount,interactions},null,2));
 const files=slides.map((s,i)=>`${String(i+1).padStart(2,'0')}-${s.slide}.png`);fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>AIML · Introduction to ML · Gallery</title><style>body{margin:0;background:#0b0f17;color:#e8ecf4;font:18px system-ui}header{padding:24px}a{color:#45d6c0}img{display:block;width:100%;height:auto}figure{margin:0 0 30px}figcaption{padding:12px 24px}@media print{@page{size:1920px 1080px;margin:0}header,figcaption{display:none}figure{margin:0;break-after:page}img{height:1080px}}</style><header>Lesson 3 · Introduction to Machine Learning · ${count} slides · static previews<br><a href="../index.html">Open interactive presentation</a></header>${files.map((f,i)=>`<figure><img src="${f}" alt="Slide ${i+1}: ${slides[i].slide}"><figcaption>${i+1} / ${count} · ${slides[i].slide}</figcaption></figure>`).join('')}</html>`);
 await page.goto(pathToFileURL(path.join(out,'index.html')).href,{waitUntil:'load'});await page.pdf({path:path.join(out,'AIML-Intro-ML-reviewed.pdf'),printBackground:true,preferCSSPageSize:true});
 assert.equal(errors.length+network.length+slides.filter(s=>s.issues.length).length+responsive.length+stateIssues.length,0,'Inspect audit.json for layout issues');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
