from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''):slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'):return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items):return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items):return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(t):return '<p class="takeaway">'+t+'</p>'
def math(t):return '<div class="formula">'+t+'</div>'
def diagram(k):return f'<div class="static-diagram" data-diagram="{k}"></div>'
def table(headers,rows):return '<table class="comparison"><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table>'
def lab(id,title,kind,prompt,notes,source=''):add(id,'Interactive lab · Regression',title,f'<p class="lab-prompt">{prompt}</p><div class="rg-widget" data-kind="{kind}" data-source="{source}"></div>',notes,'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 4','Regression','<div class="cover-layout"><div><p class="eyebrow">Fit the relationship. Quantify the uncertainty.</p><h1 class="search-title grad">A line is<br>just the start.</h1><p class="cover-sub">Least squares · Complexity · Inference</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · Fit and evaluate</span><span>02 · Choose complexity</span><span>03 · Interpret responsibly</span></div>','Follows course 04_regression. All seven source Plotly charts are retained locally, with additional interactive labs for residuals, repeated-sample bias/variance, t tails and residual diagnostics.','cover-slide')
add('map','The road ahead','Three decisions behind a regression model',cols(card('Fit',bullets('Specify a model family.','Minimize a loss.','Measure fit and predictive error.')),card('Choose complexity',bullets('Add polynomial features.','Balance flexibility and stability.','Use validation to compare models.'),'comp'),card('Interpret',bullets('Quantify coefficient uncertainty.','Separate association from causation.','Check assumptions.'),'stat')))
lab('scatter-lab','Inspect the original linear-looking data','source','Hover over the observations or select a point. Drag to zoom and use Reset view to see the complete dataset.','Original lr_scatter.json: all 25 observation coordinates preserved. The source fertilizer and yield scales are illustrative and lack documented physical units.','lr_scatter')
add('line','01 · Fit a model','Simple linear regression has two parameters',math('Yᵢ = β₀ + β₁xᵢ + εᵢ')+cols(card('Intercept β₀','<p>The modeled mean response at x = 0.</p><p>Its interpretation depends on whether zero is meaningful and within the relevant range.</p>'),card('Slope β₁','<p>The change in modeled mean response for a one-unit increase in x.</p><p>Its units are response units per predictor unit.</p>','stat'))+note('The error term includes unexplained variability; it is not limited to measurement mistakes.'),'An intercept is also sometimes called a bias parameter; that usage differs from estimator bias. A zero-mean conditional error assumption connects the function to E[Y|X=x].')
lab('residual-lab','Move the line and watch the residuals change','residual','Adjust the intercept and slope. Then press Fit OLS to find the least-squares solution for these observations.','Added live parameter explorer using the original lr_scatter data. Vertical segments show y minus prediction; RSS and R-squared update. The Fit OLS action uses the analytic slope and intercept, not a precomputed source line.')
add('rss','01 · Fit a model','Least squares penalizes large residuals',cols(math('ŷᵢ = β₀ + β₁xᵢ<br>rᵢ = yᵢ − ŷᵢ'),card('Residual sum of squares',math('RSS(β) = Σᵢ (yᵢ − β₀ − β₁xᵢ)²')+'<p>Choose β̂ to minimize this sum.</p>','stat'))+note('Squaring prevents positive and negative residuals from canceling. Large residuals receive more weight.'),'RSS is a sum of squared deviations, not itself a variance. OLS fits a conditional-mean model; it does not make the data noiseless.')
add('ols','01 · Fit a model','The best line has a closed-form solution',math('β̂₁ = Σᵢ (xᵢ − x̄)(yᵢ − ȳ) / Σᵢ (xᵢ − x̄)²<br><br>β̂₀ = ȳ − β̂₁x̄')+cols(card('Slope','<p>Compare how x and y vary together with how much x varies.</p>'),card('Intercept','<p>The fitted line passes through the centroid (x̄, ȳ).</p>','comp'))+note('The slope formula requires variation in x: Σᵢ(xᵢ − x̄)² &gt; 0.'),'The sums are over all n training observations. The analytic solution agrees with a full-rank QR least-squares solution.')
add('uniqueness','01 · Fit a model','Convexity does not by itself imply uniqueness',cols(card('Different predictor values','<p>The intercept and slope can be identified.</p><p>RSS has a unique minimum when the design has full column rank.</p>','stat'),card('Every x equals the same value c',math('β₀ + cβ₁ = ȳ')+'<p>Many parameter pairs produce the same best fitted value.</p>','cyber'))+note('Least-squares solutions still exist when parameters are not uniquely identifiable.'),'Corrects the source claim that convexity alone implies one global minimizer. With an intercept and one predictor, full rank is equivalent to nonconstant predictor values.')
lab('fit-lab','Compare the supplied line with a fresh OLS fit','source','The original traces remain available. Toggle the recomputed OLS line to compare the two fits.','Original lr_scatter_mod.json preserved exactly. The supplied line is close to, but not identical to, OLS on its plotted training points. Recomputed OLS intercept 2.13386187 and slope 2.82610678; the source line slope is 2.85208755. The overlay is explicitly distinguished.','lr_scatter_mod')
add('metrics','01 · Evaluate the fit','Different metrics answer different questions',table(['Metric','Definition','Interpretation'],[['RSS','Σrᵢ²','Total squared discrepancy on the chosen data'],['RMSE','√(RSS / N)','Prediction error in response units'],['RSE','√(RSS / (n − q))','Estimate of error standard deviation after fitting'],['R²','1 − RSS / TSS','Improvement over a mean-response baseline']])+note('q is the number of independently estimated coefficients, including the intercept.'),'RSE formula here assumes a full-column-rank OLS fit and n>q. The general denominator is n minus design rank. RMSE can be computed on any set; it is not defined exclusively for testing.')
add('rse','01 · Evaluate the fit','Residual standard error estimates a noise scale',cols(math('s = RSE = √(RSS / (n − 2))'),card('For a fitted line','<p>Two parameters were estimated.</p><p>s is in the same units as y.</p><p>s² estimates the error variance under the model assumptions.</p>','stat'))+note('RSE is a standard-deviation estimate, not a variance and not an independent test score.'),'For polynomial degree p the full-rank parameter count is p+1, so use n−p−1. Under homoscedastic zero-mean errors, RSS divided by residual degrees of freedom is unbiased for the error variance; taking the square root does not preserve exact unbiasedness.')
add('r2','01 · Evaluate the fit','R² compares squared error to a baseline',math('TSS = Σᵢ (yᵢ − ȳ)²  R² = 1 − RSS / TSS')+cols(card('R² = 1','<p>Zero residual error on this dataset, provided TSS &gt; 0.</p>','stat'),card('R² = 0','<p>The squared error equals that of predicting this dataset’s mean.</p>'),card('R² &lt; 0','<p>The predictions have greater squared error than that baseline.</p>','cyber'))+note('Training OLS with an intercept has R² ≥ 0. Held-out R² can be negative without a software error.'),'If all outcomes are constant, TSS=0 and this ratio is undefined. A zero score is not a universal judgment that a task is unlearnable. R-squared has no universal acceptable threshold.')
add('evaluation','01 · Evaluate new cases','Fit, compare and assess on different data',diagram('splits')+cols(card('Train','<p>Estimate coefficients and preprocessing.</p>'),card('Validate','<p>Compare model families and degrees.</p>','comp'),card('Test','<p>Assess the final chosen procedure.</p>','stat'))+note('Use time-aware or group-aware splits when those reflect the real prediction task.'),'Extends the source train/test distinction to preserve the validation role already introduced in the previous deck. Choosing the minimum final-test error repeatedly makes the test set part of development.')
lab('test-lab','Evaluate the original line on held-out points','source','Switch the inspected set between train and test. Compare RMSE for the supplied line without refitting it.','Original lr_scatter_mod_with_test.json, retaining 25 training points, 10 test points and the supplied line. Metrics are computed for that line using its endpoint slope/intercept. The line is not fitted using test targets.','lr_scatter_mod_with_test')
add('polynomial','02 · Choose model complexity','Curved in x can still be linear in the parameters',math('Yᵢ = β₀ + β₁xᵢ + β₂xᵢ² + ⋯ + βₚxᵢᵖ + εᵢ')+cols(card('Polynomial degree p','<p>Determines which features are available.</p><p>A degree-p model has p + 1 coefficients.</p>','comp'),card('Linear in β','<p>Each coefficient multiplies a known feature.</p><p>No products or nonlinear functions of unknown coefficients appear.</p>','stat'))+note('“Linear regression” refers to the coefficients, not necessarily to a straight plot against raw x.'))
add('design','02 · Choose model complexity','Feature expansion creates the design matrix',math('φ(xᵢ) = [1, xᵢ, xᵢ², …, xᵢᵖ]')+cols(card('Stack the rows',math('X ∈ ℝ<sup>n×(p+1)</sup>')+'<p>One observation per row.<br>One polynomial feature per column.</p>'),card('Collect the coefficients',math('β ∈ ℝ<sup>p+1</sup>  y ∈ ℝⁿ')+'<p>The model is y = Xβ + ε.</p>','comp'))+note('The leading column of ones represents the intercept.'),'Corrects the source parameter space R^p to R^(p+1). Matrix X here denotes the expanded design, not only the raw predictor column.')
add('normal-equations','02 · Least squares in matrix form','The gradient yields the normal equations',math('RSS(β) = (y − Xβ)ᵀ(y − Xβ)<br><br>∇RSS(β) = −2Xᵀy + 2XᵀXβ')+note('At a least-squares solution: <strong>XᵀXβ̂ = Xᵀy</strong>.'),'This condenses the source expandable derivation into an explicit slide. Expanding gives yᵀy−2βᵀXᵀy+βᵀXᵀXβ. Use argmin for the minimizing coefficients; min denotes the objective value.')
add('rank','02 · Least squares in matrix form','Use the inverse formula only when it exists',cols(card('Full column rank',math('β̂ = (XᵀX)⁻¹Xᵀy')+'<p>The least-squares coefficients are unique.</p>','stat'),card('Rank-deficient design',math('β̂ = X⁺y')+'<p>The Moore–Penrose pseudoinverse selects the minimum-norm least-squares solution.</p>','comp'))+note('Numerical solvers generally use QR or SVD rather than explicitly forming an inverse.'),'The pseudoinverse exists for every matrix. The expression (XᵀX)^−1Xᵀ is one full-column-rank special case, not the only setting in which least squares has a solution. High powers of raw x may be severely ill-conditioned.')
add('hyperparameter','02 · Choose model complexity','A degree is selected; coefficients are fitted',cols(card('Hyperparameter p','<p>Choose a candidate degree before fitting.</p><p>Compare degrees using validation or cross-validation.</p>','comp'),card('Parameters β','<p>Estimate the coefficients from training observations for that candidate.</p><p>Keep the evaluation procedure consistent.</p>'))+note('Greater flexibility can reduce training RSS, yet worsen performance on new observations.'))
lab('overfit-lab','Explore the original high-degree curves','source','Select one degree or show all curves. Zoom near the edges to inspect how the supplied fits behave.','Original lr_scatter_polymods_with_test.json, including degree 1,5,15,23 curves and train/test points. All sampled curve coordinates are retained. Metrics displayed here are explicitly source-reported; the degree-23 curve does not match a unique stable full-rank degree-23 OLS fit, whose behavior is substantially more extreme. No undocumented fitting implementation is asserted.','lr_scatter_polymods_with_test')
add('overfit-metrics','02 · Recognize overfitting','A better training score can accompany worse prediction',table(['Degree','Training R² · source report','Held-out RMSE · source report'],[['1','0.9850','0.1220'],['5','0.9878','0.1225'],['15','0.9933','0.1548'],['23','0.9938','0.3052']])+note('These describe the supplied course fits. High-degree numerical details affect the result.'),'The first three rows agree with independent polynomial fits to the provided data. For degree 23, stable full-rank Legendre-basis OLS gives training R²≈0.99947 and held-out RMSE≈51.19; the supplied curve and reported row likely reflect a different numerical treatment, but the exact method is unavailable. Preserve the demonstration without presenting its row as universal degree-23 behavior.')
lab('underfit-lab','Compare constant, linear and quadratic models','source','Toggle the model degree. The full vertical range is shown so every original observation remains visible.','Original lr_underfitting.json retained. Its original fixed y-range 0–6 clipped observations near 8; the deck defaults to autorange. Reported R² and RMSE agree with independent fits. RSE is recomputed using n−(p+1), correcting a fixed n−2 denominator for other degrees.','lr_underfitting')
add('diagnose-fit','02 · Recognize fit problems','Training and held-out error need interpretation',cols(card('Poor fit even on training data','<p>The family may be too restrictive.</p><p>Also inspect features, label quality and optimization.</p>','cyber'),card('Strong training fit, weak new-case performance','<p>Overfitting is one explanation.</p><p>Also investigate distribution shift, leakage and an unrepresentative split.</p>','comp'))+note('One bad score is a symptom, not a complete diagnosis.'),'Corrects the source implications that poor training performance necessarily means underfitting and poor test performance necessarily means overfitting.')
add('bias-variance','02 · Repeated samples','Bias and variance describe different kinds of error',cols(card('Bias',math('E<sub>D</sub>[f̂(x)] − f*(x)')+'<p>How the average fitted prediction differs from the true mean response.</p>'),card('Variance',math('Var<sub>D</sub>[f̂(x)]')+'<p>How fitted predictions change when the training sample changes.</p>','comp'))+note('These are properties of a learning procedure across datasets—not just residuals from one fit.'),'A low-complexity family often trades higher approximation bias for lower variance; this is a tendency, not a universal monotonic law for every modern model. Bias here is unrelated to the intercept parameter.')
lab('bias-lab','Repeat the experiment: how much do fits move?','bias','Change degree and sample size. Inspect bias and variance at a chosen x across 60 simulated training samples.','Added repeated-sample experiment: fixed evenly spaced x in [−1,1], truth 2+1.2x−0.9x², independent Gaussian errors with σ=0.3. Fit 60 samples using Householder QR, display the first 15 curves plus their 60-fit mean. The variance uses divisor 60 to give the exact finite-ensemble decomposition around the empirical mean; this approximates the population decomposition.')
add('decomposition','02 · Repeated samples','Squared prediction error has three components',math('Expected squared error at x<br>= Bias(x)² + Variance(x) + σ²')+cols(card('Reducible components','<p>Model and training choices affect bias and variance.</p>'),card('Irreducible noise','<p>A new response can differ from its true conditional mean.</p>','stat'))+note('Assume Y = f*(x) + ε with zero-mean noise independent of the training sample.'),'The identity is pointwise in x and uses squared loss. The lab computes the finite-ensemble bias and variance and adds the known fresh-noise variance 0.09. It does not claim to estimate these quantities from an unknown real-world data-generating function.')
add('selection','02 · Choose model complexity','Use validation to select; reserve testing for assessment',bullets('Fit each candidate on training data.','Compare validation error or cross-validation estimates.','Choose the procedure, including preprocessing and degree.','Assess the fixed procedure on the final test set.')+note('If test results guide repeated choices, that set is functioning as validation data.'),'Corrects the source recommendation to select the model minimizing test MSE. The original chart labels “Test points” are preserved for provenance; the deck does not recommend repeatedly optimizing their score.')
lab('uncertainty-lab','Recompute the slope evidence from the source points','source','Inspect the original observations and toggle a fitted line. The sidebar computes the slope test from these 90 points.','Original lr_maybe.json. The source text reports t≈2.16 and p≈0.03, but the plotted data yield slope≈0.10754, SE≈0.01795, t≈5.99193 on 88 df, two-sided p≈4.4453e−8. The slide uses statistics recomputed from the actual data. Exact t inference assumes the classical normal, independent, equal-variance error model.','lr_maybe')
add('hypothesis-test','03 · Quantify uncertainty','A slope test asks about linear association',cols(card('Null hypothesis',math('H₀: β₁ = 0')+'<p>No linear change in the conditional mean under this model.</p>'),card('Two-sided alternative',math('H₁: β₁ ≠ 0')+'<p>The population slope differs from zero.</p>','stat'))+note('Rejecting H₀ does not establish causation. Failing to reject does not establish no relationship.'),'A nonlinear relationship may have a zero simple-regression slope. Replace causal “influences” wording with association under a specified model.')
add('standard-error','03 · Quantify uncertainty','A coefficient estimate has a sampling standard error',math('SE(β̂₁) = s / √Σᵢ(xᵢ − x̄)²<br><br>t = (β̂₁ − 0) / SE(β̂₁)')+cols(card('More residual noise','<p>Larger s means a less precise slope estimate, all else equal.</p>','cyber'),card('More predictor spread','<p>Larger Σ(xᵢ−x̄)² means more information about the slope, under the model.</p>','stat'))+note('With classical normal errors and H₀, t follows a Student t distribution with n − 2 degrees of freedom.'),'The estimated slope is normally distributed under normal errors with conditional variance σ²/Sxx. Replacing unknown σ by the residual estimate produces the exact t pivot. A centered t distribution has mean zero only when its degrees of freedom exceed one.')
lab('tails-lab','A two-sided p-value is the area in both tails','tails','Change the observed statistic and degrees of freedom. The shaded area is P(|T| ≥ |t observed|) under H₀.','Added interactive Student t density with both tails shaded, exact p-value calculated through the regularized incomplete beta function. This probability is conditional on the null model, not the probability that the null is true. A button loads the statistic and df recomputed from the original lr_maybe points.')
add('pvalues','03 · Quantify uncertainty','A p-value is conditional on the null model',cols(card('What it answers','<p>If H₀ and the assumptions held, how probable is a statistic at least this extreme?</p>'),card('What else is needed','<p>Effect size and its units.</p><p>Uncertainty intervals, study design and practical relevance.</p>','stat'))+note('A threshold such as α = 0.05 is a decision convention, not a measure of practical importance.'),'The p-value is not P(H0|data), not the probability that the result is due to chance, and not a posterior probability of an effect. Prespecify tests and account for multiplicity when applicable.')
add('interval','03 · Quantify uncertainty','A confidence interval expresses coefficient precision',math('β̂₁ ± t<sub>0.975, n−2</sub> × SE(β̂₁)')+card('For the 90-point course dataset','<p>Slope estimate: <strong>0.1075</strong><br>95% confidence interval: approximately <strong>[0.0719, 0.1432]</strong></p>','stat')+note('Under repeated sampling and the stated assumptions, this procedure covers the true slope 95% of the time.'),'Added interval interpretation to accompany the corrected source test. This is not a claim of a 95% posterior probability for a fixed parameter. It is a slope interval, not a prediction interval for an individual future crop.')
add('multiple','03 · Multiple predictors','Multiple regression adds one coefficient per feature',math('Yᵢ = β₀ + β₁xᵢ₁ + ⋯ + βₘxᵢₘ + εᵢ')+cols(card('Design matrix','<p>n rows, m + 1 columns including the intercept.</p>'+math('y = Xβ + ε')),card('Same fitting principle','<p>Minimize RSS over all coefficients.</p><p>Check rank and conditioning when predictors overlap strongly.</p>','comp'))+note('Multiple predictors with one outcome is multiple or multivariable regression.'),'Corrects the source omission of the error term in the multiple-regression observation model. “Multivariate” often specifically refers to several response variables. With two predictors a fitted plane can be visualized; beyond that, partial plots and summaries are useful.')
add('conditional','03 · Multiple predictors','A coefficient is conditional on the included features',cols(card('Interpret βⱼ','<p>The modeled change in mean Y per unit of xⱼ, holding the other included predictors fixed.</p>'),card('Be careful with correlated predictors','<p>Individual coefficients may be unstable.</p><p>A comparison that never occurs in the data can rely heavily on extrapolation.</p>','cyber'))+note('Adding a variable changes the question answered by a coefficient.'),'No causal interpretation follows from a coefficient alone. Include predictors based on task timing and study design; indiscriminate adjustment can also introduce bias.')
lab('association-lab','Inspect the original ice-cream and shark example','source','The plotted association is real within this illustrative dataset. The graph does not identify its cause.','Original lr_corcau.json: line, 80 training and 20 test points. Recomputed training R²≈0.5300, slope t≈9.3792 on 78 df; the source text t≈4.7057 does not match these plotted observations. No temperature observations are supplied, so adjusted regression values cannot be independently reconstructed.','lr_corcau')
add('confounding','03 · Association and causation','A common cause can create an association',diagram('confound')+note('Higher temperature may affect both ice-cream sales and exposure to swimming. This is a causal hypothesis to investigate.'),'Retains the illustrative causal explanation from the source. The directed graph is a proposed mechanism, not an empirical result established by the supplied scatter plot.')
add('adjustment','03 · Association and causation','Adjustment can change the apparent relationship',math('Shark attacks = β₀ + β₁ Ice-cream sales + β₂ Temperature + ε')+cols(card('Course interpretation','<p>After adjustment, the source reports weaker evidence for the ice-cream coefficient.</p><p>This is consistent with a shared-temperature explanation.</p>'),card('Evidence still needed','<p>The temperature data and study design are required to check that analysis.</p><p>Adding a covariate alone does not prove a causal mechanism.</p>','stat'))+note('The adjusted numeric table is not reproduced as a verified calculation because the required data are absent.'),'The source reports adjusted t≈0.9300, p≈0.3553 for ice cream and t≈4.8203, p<0.01 for temperature. These are discussed qualitatively rather than asserted as independently validated statistics. Lack of significance is not proof of no causal effect.')
add('assumptions','03 · Check the model','LINE describes classical regression assumptions','<div class="card-grid">'+card('L · Linearity','<p>The conditional mean is linear in the chosen coefficients and features.</p>')+card('I · Independence','<p>Errors across observations are independent in the classical model.</p>','stat')+card('N · Normality','<p>Normal errors support exact small-sample t and F inference.</p>','comp')+card('E · Equal variance','<p>The conditional error variance is constant: homoscedasticity.</p>','deep')+'</div>'+note('Also require E[ε | X] = 0 for the standard unbiased-coefficient interpretation.'),'OLS can be computed without normal errors; normality is not a prerequisite to minimize RSS. Full-rank design, zero conditional error mean and variance assumptions play different roles in estimation, inference and prediction.')
lab('diagnostics-lab','Read residual patterns, not just one score','diagnostics','Change the synthetic scenario and horizontal axis. Look for curvature, a widening spread or an ordered pattern.','Added deterministic diagnostic examples: well-behaved errors, omitted curvature, heteroscedasticity and serial structure. Each sample receives an OLS line; plotted values are actual residuals. These are visual teaching examples, not formal tests or automatic assumption certification.')
add('residual-reading','03 · Check the model','Residual plots suggest the next question',table(['Pattern','Possible concern','Next step'],[['Curved mean pattern','Misspecified conditional mean','Consider justified features or transformations'],['Widening spread','Unequal error variance','Inspect scale; use suitable variance modeling or inference'],['Pattern over time or order','Dependent errors','Account for the sampling or temporal structure'],['Unusual isolated points','Outlier or influential observation','Check data quality and sensitivity']])+note('A featureless plot does not prove every assumption. Normality requires different diagnostics, such as a Q–Q plot.'),'Residuals from an OLS fit are not mutually independent even if the underlying errors are. The diagnostic goal is evidence about the underlying error process and conditional mean, not a requirement that observed residuals be independent.')
add('workflow','Putting it together','A defensible regression workflow',bullets('Define the prediction or association question and relevant units.','Split data to match the intended use.','Fit a suitable family using a numerically reliable solver.','Compare validation error and inspect residual behavior.','Assess the final procedure and report uncertainty with assumptions.')+note('Prediction quality, coefficient significance and causal evidence are separate claims.'))
add('practice','Check your understanding','Reason before calculating','<ol class="exercise-list"><li>A degree-5 polynomial has how many coefficients? What is the full-rank RSE denominator?</li><li>Can held-out R² be negative for a correctly implemented model?</li><li>Does a singular XᵀX mean no least-squares solution exists?</li><li>Does p &lt; 0.05 for an ice-cream coefficient show that ice cream causes shark attacks?</li></ol>')
add('answers','Check your understanding','Explain the distinctions','<div class="card-grid">'+card('01 · Parameter count','<p>Six coefficients, including the intercept.<br>RSE denominator: n − 6, if n &gt; 6 and rank is full.</p>')+card('02 · Baseline','<p>Yes. Its predictions can be worse than the mean-response baseline on that held-out dataset.</p>','stat')+card('03 · Existence','<p>No. Least squares still has solutions; the coefficients may not be unique. A pseudoinverse selects the minimum-norm one.</p>','comp')+card('04 · Causality','<p>No. The test concerns association under assumptions. Confounding and study design remain relevant.</p>','deep')+'</div>')
add('summary','Lesson 4 · Takeaways','Fit carefully. Evaluate separately. Interpret precisely.',cols(bullets('Least squares minimizes squared residuals.','Polynomial features remain linear in coefficients.','Flexibility can improve fit and amplify instability.','Use validation for choices and testing for assessment.','Inference needs assumptions; association is not causation.'),diagram('cover'))+note('Next lecture: classification changes the target and the loss.'))
add('references','Sources & further reading','Continue exploring',card('Primary course resource','<p><a href="https://www.aretor.it/courses/aiml2526/lessons/04_regression/" target="_blank" rel="noopener">AIML 2025/26 · Lesson 04 — Regression</a></p><p class="small">All seven original chart datasets and curves are included locally.</p>')+card('References and checks','<p><a href="https://www.statlearning.com/" target="_blank" rel="noopener">James et al. · An Introduction to Statistical Learning · Chapter 3</a><br><a href="https://online.stat.psu.edu/stat501/" target="_blank" rel="noopener">Penn State · STAT 501: Regression Methods</a><br><a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html" target="_blank" rel="noopener">NumPy · Least squares and rank</a></p>','stat')+'<p class="small">The notes folder documents corrections and numerical discrepancies.<br>Use the HTML presentation for interactivity; the PDF is static.</p>')

html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 4 — Regression · AIML</title><link rel="stylesheet" href="lib/reveal/reset.min.css"><link rel="stylesheet" href="lib/reveal/reveal.min.css"><link rel="stylesheet" href="css/theme-base.css"><link rel="stylesheet" href="css/search.css"><link rel="stylesheet" href="css/regression.css"></head><body><div class="reveal"><div class="slides">'
for s in slides:html+=f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div><aside class="notes">{escape(s["notes"])}</aside></section>'
html+='</div></div><div class="lesson-tag">AIML · Lesson 4 — Regression</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav><script src="lib/reveal/reveal.min.js"></script><script src="lib/plotly.min.js"></script><script src="js/course-data.js"></script><script src="js/engine.js"></script><script src="js/visuals.js"></script><script src="js/widgets.js"></script><script src="js/deck.js"></script></body></html>'
(ROOT/'index.html').write_text(html,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 4 — Regression\n\n'+''.join(f'## {i}. {s["title"]}\n\n{s["notes"] or "Discuss the example and connect it to the preceding result."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],indent=2),encoding='utf-8')
print('Built',len(slides),'slides.')
