(function(){'use strict';
const E=CLEngine,C=['#6ea8fe','#f4a261','#45d6c0','#ba8cff'],fmt=(v,n=3)=>Number.isFinite(v)?v.toFixed(n):'undefined',pct=v=>fmt(v*100,1)+'%',clone=o=>JSON.parse(JSON.stringify(o)),lin=(a,b,n=101)=>Array.from({length:n},(_,i)=>a+(b-a)*i/(n-1));
const range=(key,label,min,max,step,value)=>`<label>${label}<input aria-label="${label}" data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output data-output="${key}">${value}</output></label>`;
const select=(key,label,values,value)=>`<label>${label}<select aria-label="${label}" data-setting="${key}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`;
const button=(key,label,cls='')=>`<button type="button" data-action="${key}" class="${cls}">${label}</button>`;
const box=(title,body)=>`<div class="rg-box"><div class="rg-heading">${title}</div>${body}</div>`,metric=(title,v)=>box(title,`<div class="rg-metric">${v}</div>`);
const points=COURSE_DATA.cls_two_class.data.flatMap((t,c)=>t.x.map((x,i)=>({x,y:t.y[i],c,id:c*25+i}))),binary=COURSE_DATA.lr_logreg.data[0];
function markers(ps){return [0,1].map(c=>({type:'scatter',mode:'markers',name:'Class '+c,x:ps.filter(p=>p.c===c).map(p=>p.x),y:ps.filter(p=>p.c===c).map(p=>p.y),marker:{color:C[c],size:10,symbol:c?'x':'circle',line:{width:1,color:C[c]}}}));}
function layout(x='Feature 1',y='Feature 2'){return {paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'#0b0f17',font:{family:'Segoe UI, sans-serif',size:19,color:'#e8ecf4'},margin:{l:92,r:30,t:35,b:110},xaxis:{title:{text:x,standoff:18},gridcolor:'#273144',zerolinecolor:'#586680',automargin:false,nticks:7},yaxis:{title:{text:y,standoff:15},gridcolor:'#273144',zerolinecolor:'#586680',automargin:false,nticks:6},legend:{orientation:'h',x:0,y:-.23,font:{size:18}},dragmode:'zoom',hovermode:'closest',showlegend:true};}
class Widget{
 constructor(el){this.el=el;this.kind=el.dataset.kind;this.ready=Promise.resolve();this.locked=false;let controls='',foot='',hint='Drag to zoom · Hover to inspect';
 if(this.kind==='source'){this.raw=COURSE_DATA[el.dataset.source];this.isBinary=el.dataset.source.startsWith('lr_');this.traces=this.raw.data.filter(t=>t.type==='scatter'&&t.x.length&&String(t.mode).includes('markers'));controls=select('set','Inspect',this.traces.map(t=>t.name),this.traces[0].name)+select('point','Point',Array.from({length:this.traces[0].x.length},(_,i)=>String(i+1)),'1');foot='Original course data · all numerical arrays retained';}
 if(this.kind==='decision'){controls=range('p','P(class 1)',0,1,.01,.7)+range('cost','False-negative cost',1,10,.5,1);foot='Illustrative losses · false-positive cost = 1';hint='Minimum expected loss determines the decision';}
 if(this.kind==='naive'){controls=range('x1','Feature 1',-3,3,.1,.6)+range('x2','Feature 2',-3,3,.1,-.2)+range('prior','Prior P(1)',.05,.95,.05,.5);foot='Specified Gaussian model · μ₀ = (−1,−1), μ₁ = (1,1), σ = 1';hint='Contributions add in log space';}
 if(this.kind==='logistic'){controls=range('mid','Midpoint',0,1,.02,.5)+range('slope','Slope',-20,20,1,15)+range('threshold','Threshold',.1,.9,.05,.5);foot='Original observations · illustrative slider parameters';hint='Scores describe training data, not held-out performance';}
 if(this.kind==='neighbors'){controls=select('k','K',[1,3,5,9,15,25,49,50].map(String),'5')+select('weight','Vote',['Uniform','Inverse distance'],'Uniform')+select('scale','Feature 2 ×',['0.25','1','4'],'1')+range('x','Query x',-1.2,2.2,.1,.5)+range('y','Query y',-.8,1.3,.1,.2);foot='All 50 source points · ring = selected neighbor · star = query';hint='Background shows the computed decision regions';}
 if(this.kind==='regression'){controls=select('k','K',[1,3,7,15,25].map(String),'3')+range('q','Query x',-2,2,.1,.4);foot='25 deterministic illustrative observations · uniform weights';hint='The curve is the actual neighbor mean';}
 if(this.kind==='validation'){this.split=E.split(points);this.candidates=[1,3,5,7,9,15,29];this.scores=this.candidates.map(k=>({k,train:E.accuracy(this.split.train,this.split.train,k),validation:E.accuracy(this.split.train,this.split.validation,k)}));this.best=this.scores.reduce((a,b)=>b.validation>a.validation?b:a);controls=select('k','Candidate K',this.candidates.map(String),String(this.best.k))+button('lock','Lock K & reveal test','primary')+button('restart','Restart demonstration');foot='Fixed stratified split · 30 train / 10 validation / 10 test';hint='No test score is used to choose the suggested K';}
 controls+=`<span class="end">${button('zoom','Zoom')}${button('pan','Pan')}${button('view','Reset view')}</span>`;
 el.innerHTML=`<div class="rg-toolbar">${controls}</div><div class="rg-main"><div class="rg-graphic"><div class="rg-plot" role="img" aria-label="${this.kind} interactive chart"></div></div><div class="rg-side" aria-live="polite"></div></div><div class="rg-bottom"><span>${foot}</span><span>${hint}</span></div>`;
 this.plot=el.querySelector('.rg-plot');this.side=el.querySelector('.rg-side');el.querySelectorAll('[data-setting]').forEach(s=>s.addEventListener(s.type==='range'?'input':'change',()=>{if(this.locked&&this.kind==='validation')return;if(s.dataset.setting==='set'){const t=this.traces.find(t=>t.name===s.value);this.setting('point').innerHTML=t.x.map((_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');}this.render();}));
 el.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;if(['zoom','pan','view'].includes(action)){this.ready=this.ready.then(()=>Plotly.relayout(this.plot,action==='view'?{'xaxis.autorange':true,'yaxis.autorange':true}: {dragmode:action}));return;}if(action==='lock'){this.locked=true;this.lockedK=+this.setting('k').value;this.setting('k').disabled=true;b.disabled=true;}if(action==='restart'){this.locked=false;this.setting('k').disabled=false;el.querySelector('[data-action="lock"]').disabled=false;}this.render();}));this.render();
 }
 setting(k){return this.el.querySelector(`[data-setting="${k}"]`);}v(k){return +this.setting(k).value;}
 render(){this.el.querySelectorAll('[data-output]').forEach(o=>o.textContent=this.setting(o.dataset.output).value);let data=[],l=layout(),side='';
 if(this.kind==='source'){
  data=clone(this.raw.data);for(const t of data){if(t.type==='contour'){t.colorscale=[[0,'#263951'],[1,'#513726']];t.line={color:'#b6c3d8',width:2};t.hoverinfo='skip';}else if(String(t.mode).includes('lines')){t.line={...t.line,color:C[2],width:4};}else{const c=t.name==='Class 1'?1:0;t.marker={...t.marker,color:C[c],size:10};}t.showlegend=!!t.x.length;}
  l=layout(this.isBinary?'Predictor x (illustrative scale)':'Feature 1',this.isBinary?'Binary outcome / probability':'Feature 2');if(this.isBinary)l.yaxis.range=[-.12,1.12];const t=this.traces.find(t=>t.name===this.setting('set').value),i=this.v('point')-1;
  side=box('Original resource',`<p>${this.isBinary?'100 training observations.<br>No test observations supplied.':'25 observations per class.<br>50 observations in total.'}</p>`)+box('Selected observation',`<p>${t.name} · point ${i+1}</p><div class="point-values">x = ${fmt(t.x[i],4)}<br>${this.isBinary?'y':'Feature 2'} = ${fmt(t.y[i],4)}</div>`)+box('Inspect the chart',`<p>Hover for coordinates.<br>Click a legend entry to hide or show its trace.</p>`);if(this.isBinary)side+=box('Context','<p class="rg-small">Course cholesterol/disease illustration. The scale is not a validated clinical measurement.</p>');
 }
 if(this.kind==='decision'){const p=this.v('p'),cost=this.v('cost'),loss0=p*cost,loss1=1-p,threshold=1/(1+cost);this.result={loss0,loss1,threshold,label:loss1<=loss0?1:0};data=[{type:'bar',x:['Predict 0','Predict 1'],y:[loss0,loss1],marker:{color:[C[0],C[1]]},showlegend:false}];l=layout('Decision','Expected loss');l.yaxis.range=[0,Math.max(1.15,loss0*1.2)];side=metric('Minimum-loss decision','Class '+this.result.label)+box('Expected losses',`<p>Predict 0: ${fmt(p,2)} × ${fmt(cost,1)} = ${fmt(loss0,2)}<br>Predict 1: ${fmt(1-p,2)} × 1 = ${fmt(loss1,2)}</p>`)+metric('Probability threshold',fmt(threshold,3))+box('Decision rule','<p>Predict 1 when its expected loss is no larger. At equal losses, this demo chooses 1.</p>');}
 if(this.kind==='naive'){const x=[this.v('x1'),this.v('x2')],prior=this.v('prior'),r=E.gaussianNB(x,prior);this.result=r;const parts=[0,1].map(c=>[Math.log(c?prior:1-prior),...x.map(v=>-.5*Math.log(2*Math.PI)-.5*(v-(c?1:-1))**2)]);data=parts.map((a,c)=>({type:'bar',x:['Prior','Feature 1','Feature 2'],y:a,name:'Class '+c,marker:{color:C[c]}}));l=layout('Contribution to the log score','Log contribution');l.barmode='group';side=metric('Normalized P(class 1 | x)',pct(r.p))+box('Sum the contributions',`<p>Class 0 score: ${fmt(r.scores[0])}<br>Class 1 score: ${fmt(r.scores[1])}</p>`)+box('Log odds',`<p>Prior: ${fmt(Math.log(prior/(1-prior)))}<br>Feature 1: ${fmt(r.contributions[0])}<br>Feature 2: ${fmt(r.contributions[1])}</p>`)+box('Prediction',`<p>Class ${r.p>=.5?1:0} at threshold 0.5.</p>`);}
 if(this.kind==='logistic'){const mid=this.v('mid'),slope=this.v('slope'),threshold=this.v('threshold'),xs=lin(0,1),p=binary.x.map(x=>E.sigmoid(slope*(x-mid))),r=E.decisions(binary.y,p,threshold),loss=binary.x.reduce((s,x,i)=>{const z=slope*(x-mid);return s+E.softplus(z)-binary.y[i]*z;},0)/binary.x.length;this.result={...r,loss,p};data=[{type:'scatter',mode:'markers',x:binary.x,y:binary.y,name:'Observed label',marker:{color:C[0],size:8,opacity:.75}},{type:'scatter',mode:'lines',x:xs,y:xs.map(x=>E.sigmoid(slope*(x-mid))),name:'P(class 1)',line:{color:C[2],width:4}},{type:'scatter',mode:'lines',x:[0,1],y:[threshold,threshold],name:'Threshold',line:{color:C[3],dash:'dash',width:2}}];l=layout('Predictor x (illustrative scale)','Outcome / probability');l.yaxis.range=[-.12,1.12];const boundary=slope?mid+Math.log(threshold/(1-threshold))/slope:null;side=metric('Training accuracy',pct(r.accuracy))+box('Confusion counts',`<table><tr><th></th><th>Predict 0</th><th>Predict 1</th></tr><tr><td>Actual 0</td><td>${r.tn}</td><td>${r.fp}</td></tr><tr><td>Actual 1</td><td>${r.fn}</td><td>${r.tp}</td></tr></table>`)+box('Average training log loss',`<div class="rg-metric">${fmt(loss)}</div>`)+box('Threshold crossing',`<p>${boundary===null?'Constant probability 0.5':`x = ${fmt(boundary)}${boundary<0||boundary>1?' (outside displayed x)':''}`}</p>`);}
 if(this.kind==='neighbors'){const q=[this.v('x'),this.v('y')],k=this.v('k'),scale=this.v('scale'),weighted=this.setting('weight').value==='Inverse distance',r=E.knn(points,q,k,scale,weighted),xx=lin(-1.3,2.3,101),yy=lin(-.9,1.4,71);this.result=r;data=[{type:'heatmap',x:xx,y:yy,z:yy.map(y=>xx.map(x=>E.knn(points,[x,y],k,scale,weighted).label)),colorscale:[[0,'#20364f'],[1,'#4c3325']],zmin:0,zmax:1,showscale:false,hoverinfo:'skip'},...markers(points),{type:'scatter',mode:'markers',x:r.near.map(n=>n.p.x),y:r.near.map(n=>n.p.y),name:'Neighbors',marker:{symbol:'circle-open',size:19,color:C[2],line:{width:2}}},{type:'scatter',mode:'markers',x:[q[0]],y:[q[1]],name:'Query',marker:{symbol:'star',size:19,color:C[3],line:{color:'#fff',width:1}}}];side=metric('Predicted class',String(r.label))+metric(weighted?'Weighted class 1 fraction':'Class 1 neighbor fraction',pct(r.p))+box('Selected neighborhood',`<p>${r.near.filter(n=>n.p.c===0).length} class 0 · ${r.near.filter(n=>n.p.c===1).length} class 1<br>K-th distance: ${fmt(r.near[k-1].d)}</p>`)+box('Metric and ties',`<p class="rg-small">d² = Δx² + (${scale} × Δy)².<br>Tied votes choose class 0.<br>Distance ties use source order.</p>`);}
 if(this.kind==='regression'){const ps=E.regressionData(),k=this.v('k'),q=this.v('q'),r=E.regress(ps,q,k),xx=lin(-2,2,201);this.result=r;data=[{type:'scatter',mode:'lines',x:xx,y:xx.map(x=>E.regress(ps,x,k).y),name:'KNN mean',line:{color:C[2],width:3}},{type:'scatter',mode:'markers',x:ps.map(p=>p.x),y:ps.map(p=>p.y),name:'Observations',marker:{color:C[0],size:9}},{type:'scatter',mode:'markers',x:r.near.map(n=>n.p.x),y:r.near.map(n=>n.p.y),name:'Neighbors',marker:{symbol:'circle-open',size:18,color:C[1],line:{width:2}}},{type:'scatter',mode:'markers',x:[q],y:[r.y],name:'Prediction',marker:{symbol:'star',size:17,color:C[3]}}];l=layout('Query x','Numeric target y');side=metric('Neighbor mean',fmt(r.y))+box('Local average',`<p>Query x = ${fmt(q,1)}<br>K = ${k} observations<br>Sum of selected y = ${fmt(r.y*k)}</p>`)+box('Try the endpoints','<p>K = 1 copies one nearby target.<br>K = 25 gives the same global mean at every query.</p>');}
 if(this.kind==='validation'){const k=this.locked?this.lockedK:this.v('k'),r=this.scores.find(s=>s.k===k);this.result={...r,locked:this.locked};data=[{type:'scatter',mode:'lines+markers',x:this.candidates,y:this.scores.map(s=>s.train),name:'Training',line:{color:C[0],width:3}},{type:'scatter',mode:'lines+markers',x:this.candidates,y:this.scores.map(s=>s.validation),name:'Validation',line:{color:C[3],width:3}}];l=layout('Candidate K','Accuracy');l.yaxis.range=[0,1.05];l.xaxis.tickmode='array';l.xaxis.tickvals=this.candidates;side=metric('Candidate K',String(k))+box('Development scores',`<p>Training: ${pct(r.train)}<br>Validation: ${pct(r.validation)}</p>`)+box('Validation suggestion',`<p>K = ${this.best.k} (${pct(this.best.validation)}).<br>Equal scores prefer smaller K.</p>`);if(this.locked){const a=E.accuracy(this.split.train,this.split.test,k);this.result.test=a;side+=box('Locked · final test result',`<div class="rg-metric">${pct(a)}</div><p class="rg-small">${Math.round(a*10)} of 10 correct. K is now fixed.</p>`);}else side+=box('Final test remains hidden','<p>Lock a candidate before revealing the test score.</p>');}
 this.side.innerHTML=side;this.ready=this.ready.then(()=>Plotly.react(this.plot,data,l,{responsive:false,displayModeBar:false,scrollZoom:false,displaylogo:false}));return this.ready;
 }
}
window.CLWidgets={instances:[],points,mount(){this.instances=[...document.querySelectorAll('.rg-widget')].map(el=>new Widget(el));return Promise.all(this.instances.map(w=>w.ready));},resize(){const s=window.Reveal&&Reveal.getCurrentSlide();if(!s)return;for(const w of this.instances)if(s.contains(w.el))w.ready=w.ready.then(()=>Plotly.Plots.resize(w.plot));}};
})();
