(function(){'use strict';const E=ClusterEngine,C=['#6ea8fe','#f4a261','#45d6c0','#ba8cff','#f0759b','#d5d96b','#d992ef','#8bccf0','#edc69b','#97dba9'],clone=o=>JSON.parse(JSON.stringify(o)),fmt=(v,n=3)=>v===null?'not defined':Number(v).toFixed(n),pct=v=>fmt(v*100,1)+'%',xy=t=>t.x.map((x,i)=>[x,t.y[i]]);
const select=(k,label,values,value)=>`<label>${label}<select aria-label="${label}" data-setting="${k}">${values.map(v=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${v}</option>`).join('')}</select></label>`,range=(k,label,min,max,step,value)=>`<label>${label}<input aria-label="${label}" data-setting="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output data-output="${k}">${value}</output></label>`,button=(k,t)=>`<button type="button" data-action="${k}">${t}</button>`,box=(l,t)=>`<div class="rg-box"><div class="rg-heading">${l}</div>${t}</div>`,metric=(l,v)=>box(l,`<div class="rg-metric">${v}</div>`),small=t=>`<p class="rg-small">${t}</p>`;
function layout(){return {paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'#0b0f17',font:{family:'Segoe UI, sans-serif',size:19,color:'#e8ecf4'},margin:{l:84,r:30,t:30,b:104},xaxis:{title:{text:'Feature 1',standoff:14},gridcolor:'#263148',zerolinecolor:'#59647a',nticks:5},yaxis:{title:{text:'Feature 2',standoff:14},gridcolor:'#263148',zerolinecolor:'#59647a',nticks:5,scaleanchor:'x',scaleratio:1},legend:{orientation:'h',x:0,y:-.23,font:{size:17}},dragmode:'zoom',hovermode:'closest'};}
function scatter(points,labels=null,name='Observations'){return {type:'scatter',mode:'markers',name,x:points.map(p=>p[0]),y:points.map(p=>p[1]),marker:{color:labels?labels.map(k=>C[k%C.length]):C[0],size:8,opacity:.8},customdata:points.map((_,i)=>i+1),hovertemplate:'Point %{customdata}<br>x = %{x:.3f}<br>y = %{y:.3f}<extra></extra>'};}
function centers(c){return {...scatter(c,null,'Centroids'),marker:{symbol:'x',color:c.map((_,k)=>C[k]),size:18,line:{width:3,color:'#edf2fa'}}};}
function selected(points,i){return {...scatter([points[i]],null,'Selected observation'),marker:{color:'rgba(0,0,0,0)',size:20,line:{color:'#ffffff',width:2}},hoverinfo:'skip',showlegend:false};}
function ellipse(m,s,k){const tr=s[0][0]+s[1][1],d=Math.hypot(s[0][0]-s[1][1],2*s[0][1]),a=Math.sqrt((tr+d)/2),b=Math.sqrt((tr-d)/2),theta=.5*Math.atan2(2*s[0][1],s[0][0]-s[1][1]),p=Array.from({length:81},(_,i)=>{const t=2*Math.PI*i/80,x=a*Math.cos(t),y=b*Math.sin(t);return [m[0]+x*Math.cos(theta)-y*Math.sin(theta),m[1]+x*Math.sin(theta)+y*Math.cos(theta)];});return {type:'scatter',mode:'lines',name:'Component '+(k+1),x:p.map(p=>p[0]),y:p.map(p=>p[1]),line:{color:C[k],width:3}};}
class Widget{
 constructor(el){this.el=el;this.kind=el.dataset.kind;this.name=el.dataset.source;this.ready=Promise.resolve();this.cursor=0;this.lines=true;let controls='';
 if(this.kind==='frames')controls=select('frame','Frame',[0,1,2,3,4],0)+button('step','Step')+button('play','Play')+button('reset','Reset');
 if(this.kind==='kmeans')controls=select('k','K',[2,3,4],3)+select('seed','Start',[0,7,19],7)+button('step','Step')+button('play','Play')+button('reset','Reset');
 if(this.kind==='selection')controls=select('k','K',[1,2,3,4,5,6,7,8,9,10],3)+select('view','View',['Partition','Distortion','Silhouette'],'Partition');
 if(this.kind==='silhouette')controls=select('k','K',[2,3,4,5,6,7,8,9,10],3)+select('point','Point',Models.points.map((_,i)=>i+1),1);
 if(this.kind==='gmm')controls=range('iteration','EM iteration',0,40,1,0)+select('point','Point',Models.points.map((_,i)=>i+1),1)+button('step','Step')+button('play','Play')+button('reset','Reset');
 if(this.kind==='hierarchy')controls=select('linkage','Linkage',['single','complete','average','centroid'],'average')+range('merges','Merges',0,5,1,3);
 if(this.kind==='pca')controls=select('data','Data',['Rotated','Axis-aligned'],'Rotated')+range('angle','Angle °',-90,90,1,0)+button('best','Best PC')+button('lines','Hide projections');
 if(this.kind==='panel')controls=select('panel','Transform',['Original','Min–max','Standardized','Whitened'],'Original');
 controls+=`<span class="end">${button('zoom','Zoom')}${button('pan','Pan')}${button('view','Reset view')}</span>`;
 const original=['source','frames','panel'].includes(this.kind);el.innerHTML=`<div class="rg-toolbar">${controls}</div><div class="rg-main"><div class="rg-graphic"><div class="rg-plot" role="img" aria-label="${el.closest('section').querySelector('h2').textContent}"></div></div><div class="rg-side" aria-live="polite"></div></div><div class="rg-bottom"><span>${original?'Original course resource · coordinates retained':'Added experiment · original course observations'}</span><span>Hover to inspect · drag to zoom</span></div>`;this.plot=el.querySelector('.rg-plot');this.side=el.querySelector('.rg-side');
 el.querySelectorAll('[data-setting]').forEach(s=>s.addEventListener(s.type==='range'?'input':'change',()=>{this.pause();if(['k','seed'].includes(s.dataset.setting))this.cursor=0;if(s.dataset.setting==='angle'||s.dataset.setting==='data')this.exact=null;this.render();}));el.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>this.action(b.dataset.action)));this.render();
 }
 setting(k){return this.el.querySelector(`[data-setting="${k}"]`);}value(k){return this.setting(k).value;}num(k){return +this.value(k);}
 pause(){clearInterval(this.timer);this.timer=null;const b=this.el.querySelector('[data-action="play"]');if(b)b.textContent='Play';}
 advance(){if(this.kind==='kmeans')this.cursor=Math.min(this.cursor+1,this.trace.length-1);if(this.kind==='frames')this.setting('frame').value=Math.min(this.num('frame')+1,4);if(this.kind==='gmm')this.setting('iteration').value=Math.min(this.num('iteration')+1,40);}
 atEnd(){return this.kind==='kmeans'?this.cursor===this.trace.length-1:this.kind==='frames'?this.num('frame')===4:this.num('iteration')===40;}
 reset(){this.cursor=0;for(const key of ['frame','iteration'])if(this.setting(key))this.setting(key).value=0;}
 action(a){if(a==='view'){this.ready=this.ready.then(()=>{const d=clone(this.plot.data);Plotly.purge(this.plot);return Plotly.newPlot(this.plot,d,clone(this.baseLayout),this.config);});return;}if(a==='zoom'||a==='pan'){this.ready=this.ready.then(()=>Plotly.relayout(this.plot,{dragmode:a}));return;}
 if(a==='reset'){this.pause();this.reset();}if(a==='step'){this.pause();this.advance();}
 if(a==='play'){if(this.timer){this.pause();return;}if(this.atEnd())this.reset();this.el.querySelector('[data-action="play"]').textContent='Pause';this.timer=setInterval(()=>{if(this.atEnd()){this.pause();return;}this.advance();this.render();},750);}
 if(a==='best'){const p=Models.pca[this.value('data')==='Rotated'?'gaussian_points_rot30':'gaussian_points'];this.exact=Math.atan2(p.components[0][1],p.components[0][0]);this.setting('angle').value=this.exact*180/Math.PI;}
 if(a==='lines'){this.lines=!this.lines;this.el.querySelector('[data-action="lines"]').textContent=this.lines?'Hide projections':'Show projections';}this.render();
 }
 render(){this.el.querySelectorAll('[data-output]').forEach(o=>o.textContent=this.value(o.dataset.output));let l=layout(),d=[],side='';
 if(this.kind==='source'||this.kind==='frames'||this.kind==='panel'){
  const raw=CourseData[this.name];this.raw=raw;d=clone(raw.data);
  if(this.kind==='frames'){const f=raw.frames[this.num('frame')];d=d.map((t,i)=>({...t,...clone(f.data[i]),marker:{...t.marker,...f.data[i].marker}}));side=metric('Source snapshot',`${this.num('frame')+1} / 5`)+box('Read the animation','<p>Points are colored by assignment; crosses mark the three supplied centers.</p>')+box('Source timing',small('These are the five supplied frames. Use the next lab to separate the two update operations.'));}
  if(this.kind==='panel'){const j=['Original','Min–max','Standardized','Whitened'].indexOf(this.value('panel'));d=d.slice(2*j,2*j+2).map((t,k)=>({...t,xaxis:'x',yaxis:'y',name:'Source group '+(k+1),showlegend:true}));const s=Models.panelStats[j];l.xaxis.title.text=j===3?'Whitened component 1':'Feature 1';l.yaxis.title.text=j===3?'Whitened component 2':'Feature 2';side=metric('Source view',this.value('panel'))+box('Sample covariance',`<p>[ ${fmt(s.covariance[0][0])} &nbsp; ${fmt(s.covariance[0][1])} ]<br>[ ${fmt(s.covariance[1][0])} &nbsp; ${fmt(s.covariance[1][1])} ]</p>`)+box('All points retained',small('600 observations in each view. All original coordinates retained.'+(j>=2?' Population variances are one; sample variances are about 1.002.':' Sample covariance is reported above.')));this.panelIndex=j;}
  d.forEach((t,i)=>{if(t.mode?.includes('markers'))t.marker={...t.marker,size:t.name==='centroids'?17:8,opacity:.85,color:Array.isArray(t.marker?.color)?t.marker.color.map(c=>({'#1f77b4':C[0],'#ff7f0e':C[1],'#2ca02c':C[2]}[c]||c)):C[i%3]};if(t.mode?.includes('lines'))t.line={...t.line,color:C[i%3],width:3};if(t.mode?.includes('text'))t.textfont={size:17,color:'#e8ecf4'};});
  if(this.name==='hc_dendogram'){l=this.treeLayout();d[6].textposition='bottom center';side=metric('Original observations','6')+box('Read the height','<p>A branch’s height is the supplied between-cluster distance at that merge.</p>')+box('Source tree',small('All five merge heights and six leaf labels are retained. The tree corresponds to average linkage.'));}
  else if(this.name==='elbow'){delete l.yaxis.scaleanchor;l.xaxis.title.text='Number of clusters K';l.yaxis.title.text='Distortion';d[0].name='Source highlight';d[0].marker={color:C[2],size:16};side=metric('Candidate counts','1–10')+box('Inspect the curve','<p>Hover over a value to read the supplied distortion.</p>')+box('Interpretation',small('The bend is a heuristic. Original fit settings are not supplied; the later comparison lab uses explicitly documented new fits.'));}
  else if(this.kind==='source'){const n=d.reduce((s,t)=>s+(t.x?.length||0),0);side=metric('Observations',n)+box('Explore the data','<p>Hover for coordinates. Use Pan or drag a rectangle to zoom.</p>')+box('Representation',small(this.name==='two_gaussian_blobs'?'Source colors identify the two generating groups for illustration. Equal axis units reveal the difference in feature scales.':'Original observations, displayed with equal axis units. Reset view restores the complete dataset.'));}
 }
 if(this.kind==='kmeans'){this.trace=Models.kmeans[`${this.num('k')}-${this.num('seed')}`];const s=this.trace[this.cursor];this.result=s;d=[scatter(Models.points,s.labels),centers(s.centers)];side=metric('Distortion J',fmt(s.inertia,2))+box('Current operation',`<p>${s.phase}</p>`)+box('Progress',`<p>Iteration ${s.iteration} · state ${this.cursor+1}/${this.trace.length}</p>`)+box('Stopping',small(this.atEnd()?'Assignments are stable after a mean update. This is a local endpoint.':'Assignment and mean updates appear separately. Colors refer to cluster indices.'));}
 if(this.kind==='selection'||this.kind==='silhouette'){const s=Models.selection[this.num('k')-1];this.result=s;d=[scatter(Models.points,s.labels),centers(s.centers)];if(this.kind==='selection'){side=metric('Distortion J',fmt(s.inertia,2))+metric('Mean silhouette',s.silhouette===null?'Not defined':fmt(s.silhouette))+box('Fitting protocol',small('30 initializations per K; best fitted distortion retained. All models use the same 240 raw points. K=1 has no silhouette.'));if(this.value('view')!=='Partition'){const sil=this.value('view')==='Silhouette',models=Models.selection.filter(m=>!sil||m.k>1);d=[{type:'scatter',mode:'lines+markers',name:sil?'Mean silhouette':'Distortion',x:models.map(m=>m.k),y:models.map(m=>sil?m.silhouette:m.inertia),line:{color:C[0],width:3},marker:{size:9}}];if(!sil||s.k>1)d.push({type:'scatter',mode:'markers',showlegend:false,x:[s.k],y:[sil?s.silhouette:s.inertia],marker:{size:16,color:C[2]}});delete l.yaxis.scaleanchor;l.xaxis.title.text='Number of clusters K';l.yaxis.title.text=sil?'Mean silhouette':'Distortion';}}
  else {const i=this.num('point')-1,r=E.silhouette(Models.points,s.labels,i);this.result=r;d.push(selected(Models.points,i));side=metric('Point silhouette',fmt(r.s))+box('Average distances',`<p>a(i) = ${fmt(r.a)}<br>b(i) = ${fmt(r.b)}</p>`)+box('Membership',`<p>Own group: ${s.labels[i]+1}<br>Nearest other: ${r.neighbor+1}</p>`)+box('Distance convention',small('Ordinary Euclidean distance, excluding the selected point from its own-group average.'));}}
 if(this.kind==='gmm'){const s=Models.gmm[this.num('iteration')],i=this.num('point')-1,r=E.responsibility(s,Models.points[i]);this.result={model:s,responsibilities:r};const labels=s.responsibilities.map(r=>r.indexOf(Math.max(...r)));d=[scatter(Models.points,labels),...s.means.map((m,k)=>ellipse(m,s.covariances[k],k)),selected(Models.points,i)];side=metric('Log likelihood',fmt(s.logLikelihood,2))+box('Selected point probabilities',r.map((v,k)=>`<div class="prob-row"><span style="color:${C[k]}">Component ${k+1}</span><strong>${pct(v)}</strong></div>`).join(''))+box('Mixture weights',`<p>${s.weights.map(v=>pct(v)).join(' · ')}</p>`)+box('Read the contours',small('Ellipses have Mahalanobis radius 1. Point color is the most probable component. A tiny diagonal covariance regularizer is used.'));}
 if(this.kind==='hierarchy'){const h=Models.hierarchy[this.value('linkage')],m=this.num('merges'),labels=E.partition(h.merges,6,m);this.result={labels,clusters:6-m};l=this.treeLayout();d=[{...scatter(Models.hierarchyPoints,labels),mode:'markers+text',text:Models.hierarchyPoints.map((_,i)=>'P'+i),textposition:'top center',textfont:{size:17},showlegend:false}];const xpos={};h.leafOrder.forEach((v,i)=>xpos[v]=5+10*i);const heights={};for(let j=0;j<6;j++)heights[j]=0;h.merges.forEach(([a,b,height],i)=>{d.push({type:'scatter',mode:'lines',x:[xpos[a],xpos[a],xpos[b],xpos[b]],y:[heights[a],height,height,heights[b]],xaxis:'x2',yaxis:'y2',showlegend:false,line:{color:i<m?C[2]:'#65718a',width:i<m?4:2},hovertemplate:'Merge height: %{y:.4f}<extra></extra>'});xpos[6+i]=(xpos[a]+xpos[b])/2;heights[6+i]=height;});d.push({type:'scatter',mode:'text',x:h.leafOrder.map(v=>xpos[v]),y:h.leafOrder.map(()=>-.10),text:h.leafOrder.map(v=>'P'+v),textfont:{size:17,color:'#e8ecf4'},xaxis:'x2',yaxis:'y2',showlegend:false,hoverinfo:'skip'});l.yaxis2.range=[-.16,Math.max(...h.merges.map(r=>r[2]))*1.15];const below=m?h.merges[m-1][2]:0,above=m<5?h.merges[m][2]:below*1.15;if(above>below+1e-10){const cut=(below+above)/2;l.shapes=[{type:'line',xref:'x2',yref:'y2',x0:0,x1:60,y0:cut,y1:cut,line:{color:C[1],width:2,dash:'dash'}}];}side=metric('Clusters remaining',6-m)+metric('Last merge height',m?fmt(h.merges[m-1][2],4):'No merges')+box('Read both views',small('Colored branches mark completed merges. A dashed cut appears where consecutive heights allow one; tied heights may merge several groups at once.'));}
 if(this.kind==='pca'){const p=Models.pca[this.value('data')==='Rotated'?'gaussian_points_rot30':'gaussian_points'],angle=this.exact??this.num('angle')*Math.PI/180,r=E.projection(p.points,angle);this.result=r;if(this.exact!==null&&this.exact!==undefined)this.el.querySelector('[data-output="angle"]').textContent=fmt(angle*180/Math.PI,2);d=[scatter(p.points,null,'Original points')];if(this.lines){const x=[],y=[];p.points.forEach((p,i)=>{x.push(p[0],r.projected[i][0],null);y.push(p[1],r.projected[i][1],null);});d.unshift({type:'scatter',mode:'lines',x,y,showlegend:false,hoverinfo:'skip',line:{color:'rgba(186,140,255,.23)',width:1}});d.push({...scatter(r.projected,null,'Projections'),marker:{color:C[1],size:5,opacity:.65}});}const len=Math.max(...r.scores.map(Math.abs))*1.05;d.push({type:'scatter',mode:'lines',name:'Projection axis',x:[r.mean[0]-len*r.u[0],r.mean[0]+len*r.u[0]],y:[r.mean[1]-len*r.u[1],r.mean[1]+len*r.u[1]],line:{color:C[2],width:3}});side=metric('Explained variance',pct(r.ratio))+metric('Projected variance',fmt(r.variance))+metric('Reconstruction SSE',fmt(r.sse,2))+box('Best possible in 1D',small(pct(p.eigenvalues[0]/p.eigenvalues.reduce((a,b)=>a+b))+' · centered sample covariance. The sign of a principal direction is arbitrary.'));}
 const b=this.el.querySelector('[data-action="step"]');if(b)b.disabled=this.atEnd();this.side.innerHTML=side;this.baseLayout=clone(l);this.config={responsive:false,displayModeBar:false,scrollZoom:false,displaylogo:false,showTips:false};this.ready=this.ready.then(()=>Plotly.react(this.plot,d,l,this.config));return this.ready;
 }
 treeLayout(){const l=layout();delete l.yaxis.scaleanchor;l.showlegend=false;l.xaxis.domain=[0,.4];l.yaxis.domain=[0,1];l.xaxis.range=[-.15,1.35];l.yaxis.range=[-.2,1.35];l.xaxis.nticks=4;l.yaxis.nticks=4;l.xaxis2={...clone(l.xaxis),domain:[.59,1],anchor:'y2',range:[0,60],showticklabels:false,title:{text:'Leaves',standoff:15}};l.yaxis2={...clone(l.yaxis),anchor:'x2',range:[-.16,1.45],title:{text:'Merge distance',standoff:12},side:'right'};l.margin.r=90;return l;}
}
const instances=[];window.C2Widgets={instances,mount(){document.querySelectorAll('.rg-widget').forEach(el=>instances.push(new Widget(el)));return Promise.all(instances.map(w=>w.ready));},pause(){instances.forEach(w=>w.pause());},resize(){for(const w of instances)if(w.el.closest('section').classList.contains('present'))w.ready=w.ready.then(()=>Plotly.Plots.resize(w.plot));}};
})();
