(function(){'use strict';const E=C2Engine,C=['#6ea8fe','#f4a261','#45d6c0','#ba8cff'],clone=o=>JSON.parse(JSON.stringify(o)),fmt=(x,n=3)=>Number.isFinite(x)?(Math.abs(x)<.5*10**(-n)?0:x).toFixed(n):'undefined',pct=x=>fmt(x*100,1)+'%',lin=(a,b,n=81)=>Array.from({length:n},(_,i)=>a+(b-a)*i/(n-1));
const ps=name=>COURSE_DATA[name].data.filter(t=>t.name.startsWith('Class ')).flatMap((t,c)=>t.x.map((x,i)=>({x,y:t.y[i],c}))),range=(k,label,min,max,step,value)=>`<label>${label}<input aria-label="${label}" data-setting="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output data-output="${k}">${value}</output></label>`,select=(k,label,values,value)=>`<label>${label}<select aria-label="${label}" data-setting="${k}">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`,button=(k,t,cls='')=>`<button type="button" data-action="${k}" class="${cls}">${t}</button>`,box=(label,t)=>`<div class="rg-box"><div class="rg-heading">${label}</div>${t}</div>`,metric=(label,v)=>box(label,`<div class="rg-metric">${v}</div>`);
function markers(points,size=9){return [0,1].map(c=>({type:'scatter',mode:'markers',name:'Class '+c,x:points.filter(p=>p.c===c).map(p=>p.x),y:points.filter(p=>p.c===c).map(p=>p.y),marker:{color:C[c],size,symbol:c?'x':'circle',opacity:.85}}));}
function layout(x='Feature 1',y='Feature 2'){return {paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'#0b0f17',font:{family:'Segoe UI, sans-serif',size:19,color:'#e8ecf4'},margin:{l:84,r:28,t:30,b:108},xaxis:{title:{text:x,standoff:16},gridcolor:'#263148',zerolinecolor:'#59647a',nticks:6},yaxis:{title:{text:y,standoff:16},gridcolor:'#263148',zerolinecolor:'#59647a',nticks:6},legend:{orientation:'h',x:0,y:-.23,font:{size:18}},dragmode:'zoom',hovermode:'closest'};}
function line(w,b,bounds,name,color,dash='solid'){const a=E.clippedLine(w,b,bounds);return {type:'scatter',mode:'lines',name,x:a.map(p=>p[0]),y:a.map(p=>p[1]),line:{color,width:3,dash}};}
class Widget{
 constructor(el){this.el=el;this.kind=el.dataset.kind;this.ready=Promise.resolve();this.plane=true;this.cursor=0;let controls='',foot='',hint='Hover to inspect · drag to zoom';
 if(this.kind==='source'||this.kind==='source3d'){this.raw=COURSE_DATA[el.dataset.source];this.traces=this.raw.data.filter(t=>t.name.startsWith('Class '));controls=select('set','Inspect',this.traces.map(t=>t.name),this.traces[0].name)+select('point','Point',this.traces[0].x.map((_,i)=>String(i+1)),'1');foot='Original source chart · all numerical coordinates retained';if(this.kind==='source3d'){controls+=button('plane','Hide plane');hint='Drag to orbit · scroll to zoom';}}
 if(this.kind==='threshold'){controls=select('task','Target',['AND','OR'],'AND')+range('theta','Threshold θ',-.5,2.5,.1,1.9);foot='Four original binary inputs · fixed weights (1,1)';hint='Predict 1 at the threshold';}
 if(this.kind==='training'){controls=select('dataset','Data',['AND','Noisy AND','XOR'],'AND')+select('eta','η',['0.25','1','4'],'1')+select('order','Order',['Source','Reverse'],'Source')+button('step','Step')+button('epoch','Epoch')+button('play','Play','primary')+button('reset','Reset');foot='Original course points · zero initialization · 25-epoch budget';hint='A quiet full epoch certifies convergence';}
 if(this.kind==='margin'){controls=range('angle','Normal angle',-60,80,1,17)+range('offset','Offset d',-1.5,1.5,.05,-.4)+button('fit','Fit max-margin','primary');foot='Original ten-point dataset · distances use a unit normal';hint='The width is valid only for positive clearance';}
 if(this.kind==='kernel'){controls=range('a1','x₁',-2,2,.25,1)+range('a2','x₂',-2,2,.25,2)+range('b1','z₁',-2,2,.25,2)+range('b2','z₂',-2,2,.25,-1);foot='Homogeneous quadratic map · ψ(x) = (x₁², √2x₁x₂, x₂²)';hint='Compute in feature space or use the kernel';}
 if(this.kind==='svm'){controls=select('kernel','Kernel',['Linear','Quadratic','RBF'],'RBF')+select('C','C',['0.1','1','100'],'1')+select('gamma','RBF γ',['0.1','1','10'],'1');foot='All 300 original points · fitted models evaluated locally';hint='Training accuracy is not a validation result';}
 controls+=`<span class="end">${button('zoom',this.kind==='source3d'?'Orbit':'Zoom')}${button('pan','Pan')}${button('view',this.kind==='source3d'?'Reset camera':'Reset view')}</span>`;
 el.innerHTML=`<div class="rg-toolbar">${controls}</div><div class="rg-main"><div class="rg-graphic"><div class="rg-plot" role="img" aria-label="${this.kind} interactive chart"></div></div><div class="rg-side" aria-live="polite"></div></div><div class="rg-bottom"><span>${foot}</span><span>${hint}</span></div>`;this.plot=el.querySelector('.rg-plot');this.side=el.querySelector('.rg-side');
 el.querySelectorAll('[data-setting]').forEach(s=>s.addEventListener(s.type==='range'?'input':'change',()=>{if(s.dataset.setting==='set'){const t=this.traces.find(t=>t.name===s.value);this.setting('point').innerHTML=t.x.map((_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');}if(this.kind==='training'){this.pause();this.trace=null;this.cursor=0;}if(this.kind==='margin')this.exact=null;this.render();}));
 el.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>this.action(b.dataset.action)));this.render();
 }
 setting(k){return this.el.querySelector(`[data-setting="${k}"]`);}v(k){return +this.setting(k).value;}
 pause(){if(this.timer)clearInterval(this.timer);this.timer=null;const b=this.el.querySelector('[data-action="play"]');if(b)b.textContent='Play';}
 action(a){if(a==='view'&&this.kind!=='source3d'){this.ready=this.ready.then(()=>{const data=clone(this.plot.data);Plotly.purge(this.plot);return Plotly.newPlot(this.plot,data,clone(this.baseLayout),{responsive:false,displayModeBar:false,scrollZoom:false,displaylogo:false});});return;}if(['zoom','pan','view'].includes(a)){let d;if(this.kind==='source3d')d=a==='view'?{'scene.camera':{eye:{x:1.5,y:1.5,z:1.05}}}:{'scene.dragmode':a==='pan'?'pan':'orbit'};else d=a==='view'?{'xaxis.range':this.home?.x,'yaxis.range':this.home?.y,'xaxis.autorange':!this.home?.x,'yaxis.autorange':!this.home?.y}:{dragmode:a};this.ready=this.ready.then(()=>Plotly.relayout(this.plot,d));return;}
 if(a==='plane'){this.plane=!this.plane;this.el.querySelector('[data-action="plane"]').textContent=this.plane?'Hide plane':'Show plane';}
 if(a==='fit'){this.exact=FITTED_MODELS.margin;this.setting('angle').value=Math.atan2(this.exact.normal[1],this.exact.normal[0])*180/Math.PI;this.setting('offset').value=this.exact.offset;}
 if(a==='step')this.cursor=Math.min(this.cursor+1,this.trace.states.length-1);
 if(a==='epoch')this.cursor=Math.min((Math.floor(this.cursor/this.points.length)+1)*this.points.length,this.trace.states.length-1);
 if(a==='reset'){this.pause();this.cursor=0;}
 if(a==='play'){if(this.timer){this.pause();return;}if(this.cursor===this.trace.states.length-1)this.cursor=0;this.el.querySelector('[data-action="play"]').textContent='Pause';this.timer=setInterval(()=>{if(this.cursor===this.trace.states.length-1){this.pause();return;}this.cursor++;this.render();},650);}
 this.render();
 }
 render(){this.el.querySelectorAll('[data-output]').forEach(o=>o.textContent=this.setting(o.dataset.output).value);let data=[],l=layout(),side='';
 if(this.kind==='source'||this.kind==='source3d'){
  data=clone(this.raw.data);for(const t of data){if(t.name.startsWith('Class ')){const c=t.name==='Class 1'?1:0;t.marker={...t.marker,color:C[c],size:this.kind==='source3d'?4:t.x.length>20?7:13,symbol:c?'x':'circle',opacity:.85};}else if(t.fill==='toself'){t.fillcolor='rgba(220,205,100,.16)';t.line={color:'rgba(0,0,0,0)'};}else{t.line={...t.line,color:t.name==='Separator 2'?C[3]:t.name.startsWith('Margin ')?'#c9bc75':C[2],width:t.name.startsWith('Margin ')?2:3};if(t.marker)t.marker={...t.marker,color:C[3],size:11};}}
  const t=this.traces.find(t=>t.name===this.setting('set').value),i=this.v('point')-1,total=this.traces.reduce((s,t)=>s+t.x.length,0);side=box('Original observations',`<p>${total} points in two classes.</p>`)+box('Selected point',`<p>${t.name} · point ${i+1}<br>x₁ = ${fmt(t.x[i],4)}<br>x₂ = ${fmt(t.y[i],4)}${this.kind==='source3d'?`<br>z = ${fmt(t.z[i],4)}`:''}</p>`);
  if(this.kind==='source3d'){
   const threshold=FITTED_MODELS.lift.threshold;if(this.plane)data.push({type:'surface',name:'Added separating plane',x:[-1.4,1.4],y:[-1.4,1.4],z:[[threshold,threshold],[threshold,threshold]],colorscale:[[0,C[2]],[1,C[2]]],opacity:.22,showscale:false,hoverinfo:'skip',showlegend:false});
   const ax=title=>({title:{text:title,font:{size:20}},tickfont:{size:16},gridcolor:'#394459',zerolinecolor:'#59647a',backgroundcolor:'#101722',showbackground:true});l={paper_bgcolor:'rgba(0,0,0,0)',font:{family:'Segoe UI',color:'#e8ecf4',size:18},margin:{l:5,r:5,t:5,b:55},legend:{orientation:'h',y:0},scene:{xaxis:ax('Feature 1'),yaxis:ax('Feature 2'),zaxis:ax('z = x₁² + x₂²'),aspectmode:'cube',camera:clone(this.plot._fullLayout?.scene?._scene?.getCamera()||this.plot._fullLayout?.scene?.camera||{eye:{x:1.5,y:1.5,z:1.05}}),dragmode:'orbit'},uirevision:'lift'};
   side+=box('Added separating plane',`<p>z = ${fmt(threshold,5)}<br>Inner maximum: ${fmt(FITTED_MODELS.lift.innerMax,5)}<br>Outer minimum: ${fmt(FITTED_MODELS.lift.outerMin,5)}</p>`)+box('Explore in 3D','<p class="rg-small">Drag to rotate; scroll to zoom.<br>The plane lies in the gap. It is a valid separator, not a fitted maximum-margin claim.</p>');
  }else{const source=elSource(this);if(source==='cls_svm_margin'){l.xaxis.range=[-1.68,2.28];l.yaxis.range=[-1.35,1.35];l.yaxis.scaleanchor='x';l.yaxis.scaleratio=1;l.annotations=[{x:.454,y:.479,text:'w',showarrow:false,yshift:20,font:{color:C[3],size:21}}];}else{const xx=this.traces.flatMap(t=>t.x),yy=this.traces.flatMap(t=>t.y),xmin=Math.min(...xx),xmax=Math.max(...xx),ymin=Math.min(...yy),ymax=Math.max(...yy),pad=.15*Math.max(xmax-xmin,ymax-ymin);l.xaxis.range=[xmin-pad,xmax+pad];l.yaxis.range=[ymin-pad,ymax+pad];if(this.raw.layout.yaxis?.scaleanchor){l.yaxis.scaleanchor='x';l.yaxis.scaleratio=1;}}side+=box('Inspect the geometry','<p>Hover for coordinates.<br>Use the legend to hide or show traces.</p>');if(source==='cls_svm_both_mod')side+=box('Measured minimum clearance','<p>Separator 1: 0.2537<br>Separator 2: 0.0600<br>Both have 100% training accuracy.</p>');}
 }
 if(this.kind==='threshold'){const theta=this.v('theta'),task=this.setting('task').value,points=ps('cls_and').map(p=>({...p,c:task==='AND'?p.x*p.y:Math.max(p.x,p.y)})),xx=lin(-.3,1.3,41),yy=lin(-.3,1.3,41);this.result=points.map(p=>({...p,pred:p.x+p.y>=theta?1:0}));data=[{type:'heatmap',x:xx,y:yy,z:yy.map(y=>xx.map(x=>x+y>=theta?1:0)),colorscale:[[0,'#20364f'],[1,'#4c3325']],showscale:false,hoverinfo:'skip'},...markers(points,15),line([1,1],-theta,[-.3,1.3,-.3,1.3],'Threshold',C[2])];l.xaxis.range=[-.3,1.3];l.yaxis.range=[-.3,1.3];side=metric('Accuracy on '+task,pct(this.result.filter(p=>p.c===p.pred).length/4))+box('Truth table',`<table><tr><th>x₁</th><th>x₂</th><th>Target</th><th>Output</th></tr>${this.result.map(p=>`<tr><td>${p.x}</td><td>${p.y}</td><td>${p.c}</td><td>${p.pred}</td></tr>`).join('')}</table>`)+box('Threshold interval',`<p>${task==='AND'?'AND requires 1 < θ ≤ 2.':'OR requires 0 < θ ≤ 1.'}<br>Current additive bias b = ${fmt(-theta,1)}.</p>`);}
 if(this.kind==='training'){
  if(!this.trace){this.points=ps({'AND':'cls_and','Noisy AND':'cls_and_noisy','XOR':'cls_xor'}[this.setting('dataset').value]);this.trace=E.training(this.points,this.v('eta'),this.setting('order').value==='Reverse');}const s=this.trace.states[this.cursor],bounds=[-.4,1.45,-.4,1.45],last=s.last;this.result=s;data=[...markers(this.points,this.points.length>10?6:14),line(s.w.slice(1),s.w[0],bounds,'Current boundary',C[2])];if(last)data.push({type:'scatter',mode:'markers',name:'Last example',x:[last.x],y:[last.y],marker:{symbol:'circle-open',size:23,color:C[3],line:{width:3}}});l.xaxis.range=bounds.slice(0,2);l.yaxis.range=bounds.slice(2);const correct=this.points.filter(p=>E.predict(s.w,p)===p.c).length;
  side=box('Progress',`<p>${this.cursor} examples processed · ${s.updates} updates<br>Completed epochs: ${Math.floor(this.cursor/this.points.length)} / 25</p>`)+box('Current weights',`<p>b = ${fmt(s.w[0])}<br>w₁ = ${fmt(s.w[1])} · w₂ = ${fmt(s.w[2])}<br>Training accuracy: ${pct(correct/this.points.length)}</p>`)+box('Last update',last?`<p>Target ${last.c} · predicted ${last.guess}<br>Δ(b,w₁,w₂) = (${last.delta.map(v=>fmt(v,2)).join(', ')})</p>`:'<p>No example processed yet.<br>At zero score, output is 1.</p>')+box('Status',`<p class="rg-small">${s.converged?'Converged: a full epoch made no updates.':this.cursor===this.trace.states.length-1?'Epoch limit reached; no convergence certificate.':'Continue through the dataset. A single correct point is not convergence.'}</p>`);
  for(const a of ['step','epoch'])this.el.querySelector(`[data-action="${a}"]`).disabled=this.cursor===this.trace.states.length-1;if(this.cursor===this.trace.states.length-1)this.pause();
 }
 if(this.kind==='margin'){const angle=this.v('angle')*Math.PI/180,u=this.exact?this.exact.normal:[Math.cos(angle),Math.sin(angle)],d=this.exact?this.exact.offset:this.v('offset'),points=ps('cls_svm_margin'),r=E.margin(points,u,d),bounds=[-1.7,2.3,-1.4,1.4];this.result=r;l.legend.y=-.30;l.margin.b=130;data=[...markers(points,12),line(u,d,bounds,'Separator',C[2])];if(r.width){data.push(line(u,d-r.clearance,bounds,'Margin +','#c9bc75','dot'),line(u,d+r.clearance,bounds,'Margin -','#c9bc75','dot'));}l.xaxis.range=bounds.slice(0,2);l.yaxis.range=bounds.slice(2);l.yaxis.scaleanchor='x';l.yaxis.scaleratio=1;l.xaxis.constrain='domain';l.yaxis.constrain='domain';side=metric('Minimum signed clearance',fmt(r.clearance,4))+metric('Full symmetric margin',r.width?fmt(r.width,4):'Not separating')+box('Training geometry',`<p>${r.correct} / ${points.length} correctly classified.<br>u = (${u.map(v=>fmt(v)).join(', ')})<br>d = ${fmt(d,4)}</p>`)+box('Independent optimum',`<p class="rg-small">Maximum width: ${fmt(FITTED_MODELS.margin.width,4)}.<br>${this.exact?'Exact optimum is active. Moving a slider returns to its rounded setting.':'Fit max-margin restores the exact solution.'}</p>`);}
 if(this.kind==='kernel'){const a=[this.v('a1'),this.v('a2')],b=[this.v('b1'),this.v('b2')],pa=E.psi(a),pb=E.psi(b),con=pa.map((v,i)=>v*pb[i]),mapped=E.dot(pa,pb),direct=E.kernel(a,b,'poly');this.result={a,b,pa,pb,mapped,direct};data=[{type:'bar',x:['x₁²z₁²','2x₁x₂z₁z₂','x₂²z₂²'],y:con,marker:{color:[C[0],C[3],C[1]]},showlegend:false}];l=layout('Coordinate contribution','Product');side=box('Mapped vectors',`<p>ψ(x) = (${pa.map(v=>fmt(v,2)).join(', ')})<br>ψ(z) = (${pb.map(v=>fmt(v,2)).join(', ')})</p>`)+metric('Mapped dot product',fmt(mapped,4))+metric('(xᵀz)²',fmt(direct,4))+box('Agreement',`<p class="rg-small">Absolute difference: ${Math.abs(mapped-direct).toExponential(1)}.<br>Cross terms may be negative; their sum is the squared dot product.</p>`);}
 if(this.kind==='svm'){const type={Linear:'linear',Quadratic:'poly',RBF:'rbf'}[this.setting('kernel').value];this.setting('gamma').disabled=type!=='rbf';const m=FITTED_MODELS.models.find(m=>m.kernel===type&&m.C===this.v('C')&&(type!=='rbf'||m.gamma===this.v('gamma'))),points=ps('cls_circle_clusters');this.result=m;if(this.model!==m){this.model=m;const xx=lin(-1.5,1.5,81),yy=lin(-1.5,1.5,81);this.surface={type:'contour',x:xx,y:yy,z:yy.map(y=>xx.map(x=>E.score(m,[x,y]))),contours:{start:0,end:0,size:1,coloring:'fill'},colorscale:[[0,'#20364f'],[1,'#4c3325']],line:{color:C[2],width:2},showscale:false,hoverinfo:'skip',name:'Decision boundary'};}data=[this.surface,...markers(points,6),{type:'scatter',mode:'markers',name:'Support vectors',x:m.support.map(i=>points[i].x),y:m.support.map(i=>points[i].y),marker:{symbol:'circle-open',size:12,color:C[2],line:{width:1}}}];l.xaxis.range=[-1.5,1.5];l.yaxis.range=[-1.5,1.5];l.yaxis.scaleanchor='x';l.yaxis.scaleratio=1;l.xaxis.constrain='domain';l.yaxis.constrain='domain';side=metric('Training accuracy',pct(m.accuracy))+metric('Support vectors',m.support.length+' / 300')+box('Fitted settings',`<p>${this.setting('kernel').value} kernel<br>C = ${m.C}${type==='rbf'?'<br>γ = '+m.gamma:type==='poly'?'<br>κ(x,z) = (xᵀz)²':''}</p>`)+box('Interpretation','<p class="rg-small">Same source data, different fitted models. No test or validation score is supplied. Use held-out data to select settings.</p>');}
 this.side.innerHTML=side;this.baseLayout=clone(l);this.home={x:l.xaxis?.range?.slice(),y:l.yaxis?.range?.slice()};this.ready=this.ready.then(()=>Plotly.react(this.plot,data,l,{responsive:false,displayModeBar:false,scrollZoom:this.kind==='source3d',displaylogo:false}));return this.ready;
 }
}
function elSource(w){return w.el.dataset.source;}
window.C2Widgets={instances:[],mount(){this.instances=[...document.querySelectorAll('.rg-widget')].map(el=>new Widget(el));return Promise.all(this.instances.map(w=>w.ready));},pause(){this.instances.forEach(w=>w.pause());},resize(){const s=window.Reveal&&Reveal.getCurrentSlide();if(s)for(const w of this.instances)if(s.contains(w.el))w.ready=w.ready.then(()=>Plotly.Plots.resize(w.plot));}};
})();
