from pathlib import Path
import html
import json

ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''):
    slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'):
    return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items):return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items):return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(text):return '<p class="takeaway">'+text+'</p>'
def math(text):return '<div class="formula">'+text+'</div>'
def diagram(name):return f'<div class="static-diagram" data-diagram="{name}"></div>'
def demo(id,title,algo,prompt,kind='course'):
    add(id,'Interactive lab · '+('Uninformed' if algo in ['BFS','DFS','IDS','UCS'] else 'Informed search'),title,
        f'<p class="lab-prompt">{prompt}</p><div class="search-demo" data-algorithm="{algo}" data-graph="{kind}"></div>',
        'Use Next to select one path and update the frontier. Back restores the entire prior state. Play can be paused; leaving the slide pauses automatically. The frontier is displayed in selection order, next path first. Course-tree children are inserted left to right; stack-based DFS and IDS therefore visit rightmost siblings first. Priority ties use insertion order. Heuristic DFS orders only newly generated siblings. Green marks processed nodes, yellow marks frontier endpoints, an orange ring marks the currently selected node, and teal marks the solution. The goal test is applied on selection, not generation.', 'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 1','Search algorithms',
    '<div class="cover-layout"><div><p class="eyebrow">From possible actions to a solution</p><h1 class="search-title grad">Which path<br>should we explore?</h1><p class="cover-sub">Graphs · Frontiers · Heuristics</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · Model the problem</span><span>02 · Search without hints</span><span>03 · Search with heuristics</span></div>',
    'This deck follows the course lesson 01_search. The six original interactive examples are adapted into local, presentation-sized widgets. Lowest-cost-first and branch-and-bound also receive interactive examples. All diagrams, controls and Reveal.js assets are local; no login or network is needed to present.', 'cover-slide')
add('map','The road ahead','One engine, different selection rules',
    cols(card('01 · Representation',bullets('States and directed edges','Paths, costs and goals','The frontier'),'stat'),card('02 · Uninformed search',bullets('Breadth-first and depth-first','Iterative deepening','Lowest-cost-first'),'neural'),card('03 · Informed search',bullets('Greedy and heuristic DFS','A* and its guarantees','Depth-first branch-and-bound'),'comp'))+note('In each lab, predict the next selected path before pressing <strong>Next</strong>.'))
add('state-space','01 · Model the problem','A state must contain what matters',
    '<div class="card-grid">'+card('Navigation','<p>State: current intersection.<br>Action: take an outgoing road.<br>Cost: travel time.</p>','stat')+card('Robot delivery','<p>State: position and carried item.<br>Action: move, pick up, deliver.<br>Cost: energy or distance.</p>','neural')+card('Video game','<p>State: location, inventory, tasks.<br>Action: move or interact.<br>Goal: required tasks complete.</p>','comp')+card('Traveling salesperson','<p>State: city and visited-city set.<br>Action: travel to another city.<br>Goal: visit all, then return.</p>','cyber')+'</div>',
    'The source introduces games, navigation, delivery and the traveling salesperson problem. The location alone may not determine the legal next actions or whether the goal is reached. For a standard traveling salesperson tour, the final state also requires return to the origin. A search node can record the full path and cost even when its state is much smaller.')
add('directed-graphs','01 · Model the problem','Directed edges encode legal moves',
    cols('<p>A graph is a pair <strong>G = (V, E)</strong>.</p>'+math('V = {A, B, C, D}<br>E ⊆ V × V')+bullets('Vertices represent states.','An edge (A, B) permits A → B.','B → A needs its own edge.'),diagram('directed')),
    'The source example uses edges A→B, A→C, B→D, C→D and D→A. This graph is cyclic. Ordered pairs matter: directed reachability is not symmetric. A directed path follows each edge in its permitted direction.')
add('paths-costs','01 · Model the problem','A path is a solution; its cost measures quality',
    cols(diagram('weighted'),'<p>Start at <strong>A</strong>. Reach <strong>D</strong>.</p>'+math('g(p) = ∑ edge costs along p')+card('Two valid paths','<p>A → B → D &nbsp; <b class="teal">1 + 5 = 6</b><br>A → C → D &nbsp; <b class="orange">10 + 8 = 18</b></p>')+note('Equal edge counts can hide very different costs.')),
    'We use g(p) for accumulated cost, h(n) for estimated remaining cost and f(p)=g(p)+h(end(p)). The source calls accumulated cost c(p) and the combined A* score g(p). The deck changes only the symbols to match common usage, not the selection rule. Unless explicitly stated, weighted-search guarantees assume non-negative edge costs.')
add('trees','01 · Model the problem','A rooted tree makes the choices visible',
    cols('<p>One root. One path from the root to every node.</p>'+bullets('Depth = number of edges from the root.','A leaf has no children.','Every non-root node has one parent.')+math('A → B → F → P → S<br><span class="formula-small">4 edges · goal S at depth 4</span>'),diagram('course')),
    'The course web widgets contain a 19-node tree. S is a child of P in the executable widget data; the earlier static Mermaid diagram places S under O instead. This deck consistently follows the executable widget: A–B–F–P–S. Children and all original edge costs and heuristic values are retained.')
add('graph-versus-tree','01 · Model the problem','A search tree can repeat a graph state',
    cols(diagram('unfold'),bullets('The state graph describes the environment.','The search tree describes possible paths.','Different paths may end in the same state.','A cycle can create infinitely many paths.'))+note('Cycle pruning rejects a state already on the <strong>current path</strong>.'),
    'A finite cyclic graph can induce an infinite search tree. Path-cycle pruning and global duplicate detection are distinct. Later slides explain why cost-sensitive global pruning must allow improved paths. The teaching engine uses path-cycle pruning; its supplied examples are finite trees.')
add('generic-search','01 · Model the problem','The generic search loop',
    cols('<pre class="pseudocode"><code>frontier ← [path(start)]\nwhile frontier is not empty:\n    p ← select_and_remove(frontier)\n    if goal(last(p)):\n        return p\n    for each successor v of last(p):\n        add p extended by v to frontier\nreturn failure</code></pre>',card('The key design choice',math('Which path comes next?')+bullets('Oldest or newest?','Cheapest so far?','Most promising estimate?'))),
    'This is a tree-search skeleton. Add appropriate cycle or duplicate handling for graph search. The goal is tested after selecting a path from the frontier. For UCS and A*, stopping when a goal is merely generated can return a more expensive path. Empty frontier represents failure, not a path.')
add('frontier','01 · Model the problem','The frontier holds paths waiting to be selected',
    '<div class="frontier-story"><div>'+card('Before selecting A',math('[ ⟨A⟩ ]'),'comp')+'</div><div class="story-arrow">→</div><div>'+card('After expanding A',math('[ ⟨A,B⟩, ⟨A,C⟩, ⟨A,D⟩ ]'),'neural')+'</div></div>'+cols(card('Select','<p>Remove one waiting path and inspect its endpoint.</p>'),card('Expand','<p>If it is not a goal, generate its permitted extensions.</p>'))+note('A discovered node is not necessarily an expanded node.'),
    'The source widgets have separate queue and frontier displays. Here they are unified into a frontier of complete paths, with the next selection first and numerical priorities where relevant. The selected and expanded counters are distinct. A goal is selected but not expanded.')
add('criteria','01 · Model the problem','Four questions to ask of any search strategy',
    '<div class="card-grid">'+card('Completeness','<p>Will it find a solution whenever one exists?</p>','stat')+card('Optimality','<p>Will it return a minimum-cost solution?</p>','deep')+card('Time','<p>How much search must it perform?</p>','neural')+card('Memory','<p>How much of the frontier must it retain?</p>','comp')+'</div>'+note('Every guarantee depends on assumptions about the graph, costs and implementation.')+'<p class="small">b = branching factor; d = shallowest goal depth; m = maximum search depth</p>',
    'For implicit search trees, b denotes a finite branching bound, d the shallowest goal depth and m the maximum depth. DFS is complete on finite search spaces with suitable cycle handling, but not generally on infinite branches. We state the setting explicitly rather than assigning unconditional yes/no guarantees.')
add('uninformed','02 · Uninformed search','Search without an estimate of the goal',
    '<p class="chapter-lead">Choose systematically, using arrival order,<br>depth or cost already paid.</p><div class="chiprow"><span class="chip">BFS</span><span class="chip">DFS</span><span class="chip">IDS</span><span class="chip">Lowest-cost-first</span></div>',cls='chapter-slide')
add('bfs','02 · Uninformed search','Breadth-first: finish the shallow layers first',
    cols(card('FIFO queue',math('first in → first out')+bullets('Append children to the back.','Remove the oldest path from the front.','Depth never decreases in selection order.')),card('What you get',bullets('Complete with finite branching and a finite-depth goal.','Finds the fewest-edge solution.','Minimum cost when every edge has the same positive cost.','The frontier can grow exponentially.'),'stat')),
    'For the generic goal-on-selection version, time and frontier memory can be O(b^(d+1)): nodes selected at depth d before the goal can generate depth d+1. With goal testing on generation, the familiar O(b^d) bound applies. Both express exponential growth in solution depth. Do not interpret fewest edges as minimum weighted cost.')
demo('bfs-lab','BFS · watch the queue expand','BFS','Predict: after A, B, C and D, which node is selected? Try goal B as well as S.')
add('dfs','02 · Uninformed search','Depth-first: commit to one branch',
    cols(card('LIFO stack',math('last in → first out')+bullets('Push children onto the stack.','Pop the most recently inserted path.','Backtrack when a branch ends.')),card('The trade-off',bullets('Small frontier: O(bm) search records.','Order strongly affects time to a goal.','No shortest-path guarantee.','An infinite branch can prevent success.'),'comp'))+note('Our labs insert A’s children as B, C, D. Therefore DFS visits <strong>D first</strong>.'),
    'Depth-first search does not inherently prefer the leftmost or rightmost child. That choice follows from insertion order. The labs preserve the website’s left-to-right insertion and rightmost-first removal. O(bm) space assumes parent-linked path records; copying full paths incurs additional storage. Worst-case time is O(b^m) on a finite tree.')
demo('dfs-lab','DFS · follow the stack','DFS','Predict the first four selections. Then set goal B and compare with BFS.')
add('breadth-depth','02 · Uninformed search','Same tree, different exploration order',
    cols(card('BFS · layers',diagram('breadth'),'neural'),card('DFS · branches',diagram('depth'),'comp'))+note('The solution path may be the same. The work performed before finding it can be very different.'),
    'The small tree is illustrative. Numbers show selection order with left-to-right child insertion. The left image uses a queue. The right image uses a stack and therefore explores the right branch first. Neither picture is a universal claim about left-to-right preference.')
add('ids','02 · Uninformed search','Iterative deepening: increase a depth limit',
    cols('<div class="limit-ladder"><span>Limit 0</span><span>Limit 1</span><span>Limit 2</span><span>…</span></div>'+bullets('Run depth-limited DFS from the root.','If a deeper branch was cut off, increase the limit.','Restart the search; stop at the first goal.'),card('Shallowest solution, small frontier',bullets('Complete for finite branching and a finite-depth goal.','Fewest edges; cost-optimal for equal positive edge costs.','O(bd) search records, with repeated work.'),'stat')),
    'Depth-limited search must distinguish cutoff from exhausted failure. A cutoff means unsearched deeper successors exist; exhausted failure means none remain. The widget has no arbitrary depth-10 cap and stops if the finite tree is exhausted. Its goal check happens before the depth cutoff. Like DFS, memory bounds assume shared parent records, not a full stored animation history.')
demo('ids-lab','IDS · replay the search at each depth','IDS','Watch the limit change from 0 to 4. Back also restores the previous depth limit.')
add('ids-overhead','02 · Uninformed search','Repeated work can be a reasonable price',
    cols('<p>Most nodes in a branching tree live near the bottom.</p>'+math('1 + 10 + 100 + 1000 = 1111')+math('4 + 3·10 + 2·100 + 1000 = 1234'),card('A complete tree · b = 10, d = 3','<p>One pass through depth 3:<br><strong>1111 node visits</strong></p><p>Deepening through limits 0–3:<br><strong>1234 node visits</strong></p><p class="teal">About 11% extra visits.</p>','stat'))+note('For b &gt; 1, overhead tends toward b/(b − 1). A long single chain is a less favorable case.'),
    'These totals illustrate complete traversal of each depth limit, not the exact counts of the irregular course tree or early termination at a goal. For a full b-ary tree, iterative deepening visits sum((d+1-i)b^i) nodes; one full traversal visits sum(b^i). Their ratio tends to b/(b−1) for b>1. For b=1, IDS repeats increasingly long prefixes and has quadratic work in depth.')
add('ucs','02 · Uninformed search','Lowest-cost-first: spend the smallest total so far',
    cols(card('Also called uniform-cost search',math('select p with minimum g(p)')+bullets('Use a priority queue.','Add the next edge cost to the path cost.','Test the goal when its path is selected.')),card('Why it differs from BFS',bullets('Few edges can still be expensive.','The priority is the entire path cost.','With equal edge costs, it behaves like BFS.'),'deep'))+note('Non-negative costs support optimality on finite graphs. Infinite spaces need additional conditions.'),
    'The course calls this LCFS. The queue must be ordered by accumulated path cost, not the individual edge weight. On finite graphs, standard UCS with best-cost duplicate handling is optimal for non-negative edges. A sufficient condition for completeness on infinite, finitely branching spaces is every edge costing at least ε>0. Negative edges invalidate the ordinary first-goal guarantee.')
demo('ucs-lab','Lowest-cost-first · compare cumulative costs','UCS','Compare A → C → H with A → B → F. Which is cheaper so far?')
demo('weighted-lab','One problem · compare four selection rules','UCS','All three exits are acceptable. Switch algorithms: fewest edges, smallest h, and minimum cost need not agree.','routes')
add('uninformed-summary','02 · Uninformed search','The uninformed toolkit',
    '<table class="comparison"><thead><tr><th>Method</th><th>Select by</th><th>Solution guarantee</th><th>Frontier memory</th></tr></thead><tbody><tr><td>BFS</td><td>Oldest path</td><td>Fewest edges</td><td>Exponential in depth</td></tr><tr><td>DFS</td><td>Newest path</td><td>Any solution, if it terminates</td><td>Linear in depth*</td></tr><tr><td>IDS</td><td>DFS, increasing limit</td><td>Fewest edges</td><td>Linear in depth*</td></tr><tr><td>Lowest-cost-first</td><td>Minimum g</td><td>Least cost**</td><td>Can be exponential</td></tr></tbody></table>'+note('* For fixed branching and parent-linked records. ** Under the cost and termination assumptions discussed.'),
    'The table describes frontier/search-record storage, not the extra snapshots a visualization records for rewind. BFS and IDS minimize total cost only with equal positive edge costs. The difference between search complexity and UI history storage is stated in implementation notes. All finite teaching examples terminate.')
add('informed','03 · Informed search','Give the search a useful estimate',
    '<p class="chapter-lead">The frontier still holds possible paths.<br>A heuristic changes which one looks promising.</p>'+math('h(n) ≈ remaining cost from n to a goal'),cls='chapter-slide')
add('heuristic','03 · Informed search','A heuristic estimates the work still ahead',
    cols(diagram('heuristic'),bullets('h(n) estimates the cheapest remaining cost.','It must use information available at n.','It should be cheaper to compute than solving the problem.','A relaxed problem often gives a useful lower bound.'))+note('Straight-line distance is a lower bound for route distance, using the same units.'),
    'Straight-line distance is appropriate when route costs measure geometric distance and legal routes cannot be shorter than the straight line. For travel time, distance alone has the wrong units; divide by a valid upper bound on speed to obtain a time lower bound. It does not automatically give a bound for arbitrary energy or monetary costs.')
add('greedy','03 · Informed search','Greedy best-first: follow the smallest estimate',
    cols(card('A global frontier priority',math('select p with minimum h(end(p))')+bullets('Compare all waiting paths.','Prefer the endpoint that looks closest.','Ignore the cost already paid.')),card('Fast-looking can be expensive','<p>A tiny remaining estimate says nothing about how much the route has already cost.</p><p>Greedy search has <strong>no general optimality guarantee</strong>.</p>','cyber')),
    'Greedy best-first can also fail to terminate in infinite spaces or without cycle handling. It is complete on a finite graph with adequate duplicate/cycle handling, but the heuristic alone guarantees neither completeness in general nor minimum cost.')
demo('greedy-lab','Greedy best-first · use h alone','GBFS','After E is explored, F has a smaller h than E’s children. Does the search stay in E’s branch?')
add('heuristic-dfs','03 · Informed search','Heuristic DFS: order siblings, then go deep',
    cols(card('Local ordering',math('best new child goes on top')+bullets('Keep a LIFO frontier.','Sort newly generated children by h.','Explore the chosen subtree before older alternatives.')),card('Compare with greedy search','<p><strong>Greedy:</strong> choose the best endpoint across the entire frontier.</p><p><strong>Heuristic DFS:</strong> order the newest siblings, then follow the stack.</p>','comp'))+note('It retains DFS’s memory advantage and its lack of a general optimality guarantee.'),
    'The implementation pushes siblings in descending h so that the smallest h is popped next. Equal heuristic siblings use source insertion order as the next-visit tie-break. This local ordering is not equivalent to sorting the complete frontier by h.')
demo('heuristic-dfs-lab','Heuristic DFS · local priority, deep commitment','HDFS','Compare with greedy: after reaching E, which nodes must be tried before returning to F?')
add('astar','03 · Informed search','A*: combine the cost paid and the cost ahead',
    '<div class="score-equation"><div>'+math('g(p)')+'<p>Actual cost so far</p></div><span>+</span><div>'+math('h(end(p))')+'<p>Estimated remaining cost</p></div><span>=</span><div>'+math('f(p)')+'<p>Estimated total cost</p></div></div>'+note('Select the frontier path with the <strong>smallest f</strong>. With h = 0, A* becomes lowest-cost-first.'),
    'The slides use conventional f=g+h notation. The source webpage instead names the sum g and the paid cost c. A* does not simply average BFS and greedy search; it orders by the sum of actual and estimated costs.')
add('astar-scores','03 · Informed search','The first A* decision',
    '<p>After expanding A in the course tree:</p><table class="comparison score-table"><thead><tr><th>Path</th><th>g · paid</th><th>h · estimate</th><th>f = g + h</th></tr></thead><tbody><tr class="highlight"><td>A → B</td><td>1</td><td>2</td><td>3 ← select</td></tr><tr><td>A → C</td><td>2</td><td>4</td><td>6</td></tr><tr><td>A → D</td><td>4</td><td>3</td><td>7</td></tr></tbody></table>'+note('After B: E has f = 3 + 1 = 4; F has f = 7 + 2 = 9; G has f = 4 + 9 = 13.'),
    'The edge costs and h values match the webpage widget exactly. After B is expanded, C and D remain on the frontier and must still participate in the comparison. The lab shows the full frontier in sorted order rather than just B’s new children.')
demo('astar-lab','A* · inspect g, h and f together','ASTAR','Why does A* return to C before exploring F? Toggle h = 0 and compare the order.')
add('admissibility','03 · Informed search','Admissible means “never overestimate”',
    cols(math('0 ≤ h(n) ≤ h*(n)<br>h(goal) = 0')+'<p>h*(n) is the true least remaining cost.</p>'+card('A lower bound','<p>Then f(p) cannot exceed the cheapest complete solution that extends p.</p>','stat'),card('A sufficient tree-search guarantee',bullets('Finite branching.','Each edge costs at least ε &gt; 0.','An admissible heuristic.','Select minimum f and test the goal on selection.'))),
    'These are sufficient conditions for optimal and complete A* tree search when a solution exists. Finite graphs can use weaker termination assumptions, such as non-negative costs with suitable best-cost duplicate handling. If no route to any goal exists from n, the true remaining cost is infinite. h=0 is admissible for non-negative costs, though it gives no directional guidance.')
add('consistency','03 · Informed search','Consistency checks each edge',
    cols(math('h(u) ≤ cost(u,v) + h(v)')+bullets('The estimate cannot fall faster than the edge cost.','Together with h(goal) = 0, consistency implies admissibility.','For graph A*, it supports closing a state after its best path is selected.'),card('The course tree is a useful counterexample','<p>For A → B:</p>'+math('h(A) = 5<br>cost(A,B) + h(B) = 1 + 2 = 3')+'<p class="orange">5 &gt; 3: not consistent.</p>','cyber'))+note('An admissible heuristic can be inconsistent. Tree search still works under the stated conditions.'),
    'For goal S, the only goal path has remaining costs A=12, B=11, F=5, P=3, S=0. The source heuristic gives 5,2,2,2,0 on those nodes, all lower bounds. All other nodes are dead ends relative to S and have infinite true remaining cost. Thus this particular h is admissible for the course tree but inconsistent on A→B and C→H. A graph-search implementation that permanently discards later better paths needs consistency or must reopen states.')
add('graph-cautions','03 · Informed search','Graph search must keep better routes alive',
    cols(card('Duplicates are not all equivalent',bullets('Track the best known g for each state.','Update the frontier when a cheaper route is found.','With an inconsistent h, reopen a previously expanded state if its g improves.')),card('Negative edges need different reasoning','<p>Ordinary UCS and A* guarantees assume non-negative edge costs.</p><p>Cycle detection alone does <strong>not</strong> restore those guarantees when negative edges exist.</p>','cyber'))+note('A reachable negative cycle on a route to the goal can make the minimum path cost unbounded.'),
    'This corrects the webpage suggestion that handling negative-cost cycles is enough to support ordinary A*. Even without a negative cycle, a negative edge can break the usual first-goal stopping rule. For non-negative graph search, remember best costs and handle stale queue entries or priority updates. The lab is intentionally a tree, so a global closed set is unnecessary.')
add('branch-bound','03 · Informed search','Branch-and-bound: improve, then prune',
    cols('<ol class="steps"><li>Start with bound B = ∞.</li><li>Explore paths depth first.</li><li>Prune if g(p) + h(end(p)) ≥ B.</li><li>At a better goal, save its path and set B = g(p).</li><li>Continue until no candidate remains.</li></ol>',card('What makes pruning safe',bullets('The estimate must be a lower bound.','The incumbent is the best solution found so far.','The first solution is not necessarily the best.','DFS keeps frontier storage small.'),'stat')),
    'The source calls this DFBBS. We use depth-first branch-and-bound (DFBnB) in prose and BNB in code. For finite examples with non-negative costs and admissible h, exhausting all candidates proves optimality. With a strict f<B test, a supplied finite bound must be greater than the optimum to guarantee finding a solution; setting it exactly to the optimal cost without an incumbent can return no solution below the bound. Infinite spaces still require termination assumptions.')
demo('branch-bound-lab','Branch-and-bound · watch the incumbent improve','BNB','The stack tries the rightmost branch first. Watch the best cost improve from 12 to 6, then prune B.','routes')
add('selection-matrix','03 · Informed search','The frontier rule explains the algorithm',
    '<table class="comparison"><thead><tr><th>Algorithm</th><th>Container / order</th><th>Information used</th></tr></thead><tbody><tr><td>BFS / DFS</td><td>Queue / stack</td><td>Insertion order</td></tr><tr><td>IDS</td><td>Repeated depth-limited DFS</td><td>Depth bound</td></tr><tr><td>Lowest-cost-first</td><td>Minimum g</td><td>Cost already paid</td></tr><tr><td>Greedy best-first</td><td>Minimum h</td><td>Estimated remaining cost</td></tr><tr><td>Heuristic DFS</td><td>Stack; order new siblings by h</td><td>Local heuristic guidance</td></tr><tr><td>A*</td><td>Minimum g + h</td><td>Estimated total cost</td></tr><tr><td>Branch-and-bound</td><td>DFS; prune against an incumbent</td><td>Lower bounds and best solution</td></tr></tbody></table>')
add('choose','Putting it together','Choose from the problem’s requirements',
    '<div class="card-grid">'+card('Fewest steps · equal costs','<p>Try <strong>BFS</strong> when its frontier fits in memory.<br>Try <strong>IDS</strong> when depth is unknown and memory is tight.</p>','neural')+card('Weighted costs · no useful h','<p>Use <strong>lowest-cost-first</strong> with non-negative costs and correct duplicate handling.</p>','deep')+card('Weighted costs · useful lower bound','<p>Use <strong>A*</strong> when you can afford its frontier.<br>Check admissibility and graph-search behavior.</p>','stat')+card('Memory tight · optimization needed','<p>Consider <strong>depth-first branch-and-bound</strong>.<br>Neighbor ordering and early incumbents matter.</p>','comp')+'</div>',
    'These are starting points, not universal recommendations. A finite tree with plentiful goals may also be well served by DFS or heuristic DFS if any solution is acceptable. Good heuristic computation has a cost, and the best practical choice depends on the actual state space.')
add('practice','Check your understanding','Predict first, then use the labs',
    '<ol class="exercise-list"><li>Set goal B in the course tree. Why does DFS do more work than BFS?</li><li>In the three-exit lab, can BFS return a path costing 9 when a path costing 6 exists?</li><li>After A and B are expanded, why does A* choose E before F?</li><li>In branch-and-bound, what happens if the initial strict bound is 6?</li></ol>'+note('For each answer, name the rule that selects or rejects the next path.'))
add('answers','Check your understanding','Explain the behavior using the frontier',
    '<div class="card-grid">'+card('01 · Stack order','<p>DFS explores D and the C subtree before B. BFS selects B immediately after A.</p>','comp')+card('02 · Edge count ≠ total cost','<p>BFS finds A → B → G1: two edges, cost 9. A → C → D → G2 has three edges, cost 6.</p>','deep')+card('03 · Compare total estimates','<p>E has f = 3 + 1 = 4.<br>F has f = 7 + 2 = 9.<br>E wins the next comparison.</p>','neural')+card('04 · Strict bound','<p>The lab searches only for costs below 6. It finds none; this does not mean that no solution exists.</p>','stat')+'</div>')
add('summary','Lesson 1 · Takeaways','Search is controlled exploration',
    cols(bullets('Model the right states, actions and costs.','Keep track of paths waiting on the frontier.','Select using order, cost, heuristic — or a combination.','Match guarantees to their assumptions.','Use the demos to explain what happens next.'),diagram('cover'))+note('Next time you see a search algorithm, ask: <strong>what does it keep, and what does it select?</strong>'))
add('references','Sources & further reading','Continue exploring',
    card('Primary course resource','<p><a href="https://www.aretor.it/courses/aiml2526/lessons/01_search/" target="_blank" rel="noopener">AIML 2025/26 · Lesson 01 — Search</a></p><p class="small">Content sequence, six original interactive examples, course-tree topology, edge costs and heuristic values.</p>')+
    card('Textbook reference','<p><a href="https://artint.info/3e/html/ArtInt3e.Ch3.html" target="_blank" rel="noopener">Poole &amp; Mackworth · Artificial Intelligence: Foundations of Computational Agents, 3rd ed. · Chapter 3</a></p><p class="small">Search strategies, heuristic conditions and pruning.</p>','stat')+
    '<p class="small">Adaptation notes, complete slide notes and source mapping are included in the <strong>notes</strong> folder.<br>The interactive slides run locally; the gallery and PDF are static review copies.</p>',
    'No website password or authenticated request headers are included in the presentation. The six original widgets are reimplemented with their course data and intended traversal rules, retaining play, reset, back, next, frontier and solution displays. New local controls add pause, speed, selected-goal options for uninformed examples, and A* with h=0. New examples are identified in notes. Original diagrams use native SVG, preserving the history deck’s palette and typography.')

sections=[]
for s in slides:
    sections.append(f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div></section>')
document='''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 1 — Search Algorithms · AIML</title>
<link rel="stylesheet" href="lib/reveal/reset.min.css"><link rel="stylesheet" href="lib/reveal/reveal.min.css"><link rel="stylesheet" href="css/theme-base.css"><link rel="stylesheet" href="css/search.css"></head>
<body><div class="reveal"><div class="slides">'''+''.join(sections)+'''</div></div>
<div class="lesson-tag">AIML · Lesson 1 — Search Algorithms</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview" aria-label="Slide overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav>
<script src="lib/reveal/reveal.min.js"></script><script src="js/source-tree.js"></script><script src="js/search-engine.js"></script><script src="js/visuals.js"></script><script src="js/widgets.js"></script><script src="js/deck.js"></script></body></html>'''
(ROOT/'index.html').write_text(document,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 1 — Search algorithms\n\n'+''.join(f'## {i:02d}. {s["title"]}\n\n{s["notes"] or "Use the slide to synthesize the preceding definitions and examples."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],indent=2),encoding='utf-8')
print(f'Built {len(slides)} slides.')
