const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const puppeteer=require(path.join(process.env.LOCALAPPDATA,'Temp/node_modules/puppeteer-core'));
const audit=require('./audit-function.js'),root=path.resolve(__dirname,'..'),out=path.join(root,'_review'),delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,pipe:true,args:['--no-sandbox','--disable-gpu']});try{
 const page=await browser.newPage();await page.setViewport({width:1920,height:1080});const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));await page.setRequestInterception(true);page.on('request',r=>{if(/^https?:/.test(r.url())){network.push(r.url());r.abort();}else r.continue();});const url=pathToFileURL(path.join(root,'index.html')).href;await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>Reveal.isReady());await page.evaluate(async()=>{await deckReady;Reveal.configure({transition:'none'});});
 async function settle(){await page.evaluate(async()=>{CLWidgets.resize();await Promise.all(CLWidgets.instances.map(w=>w.ready));});await delay(30);}
 async function go(id){await page.evaluate(id=>Reveal.slide(Reveal.getSlides().findIndex(s=>s.id===id)),id);await settle();}
 async function check(){const a=await page.evaluate(audit),extra=await page.evaluate(()=>{const issues=[];for(const p of Reveal.getCurrentSlide().querySelectorAll('.rg-plot')){const b=p.getBoundingClientRect(),labels=[...p.querySelectorAll('.xtick text,.ytick text,.g-xtitle text,.g-ytitle text,.legendtext')].map(t=>({b:t.getBoundingClientRect(),text:t.textContent}));for(const {b:r,text}of labels)if(r.width&&r.height&&(r.left<b.left-2||r.right>b.right+2||r.top<b.top-2||r.bottom>b.bottom+2))issues.push({type:'chart-label-clipping',label:text});for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],c=labels[j];if(Math.min(a.b.right,c.b.right)-Math.max(a.b.left,c.b.left)>2&&Math.min(a.b.bottom,c.b.bottom)-Math.max(a.b.top,c.b.top)>2)issues.push({type:'chart-label-overlap',a:a.text,b:c.text});}}return issues;});a.issues.push(...extra);return a;}
 const count=await page.evaluate(()=>Reveal.getTotalSlides()),slides=[];for(let i=0;i<count;i++){await page.evaluate(i=>Reveal.slide(i),i);await settle();const s=await check();slides.push(s);await page.screenshot({path:path.join(out,`${String(i+1).padStart(2,'0')}-${s.slide}.png`)});}fs.writeFileSync(path.join(out,'initial-audit.json'),JSON.stringify({count,errors,network,slides},null,2));console.log(JSON.stringify({stage:'rendered',count,errors,issues:slides.filter(s=>s.issues.length)},null,2));if(process.argv.includes('--quick'))return;
 const responsive=[];for(const [width,height]of [[1366,768],[1024,768]]){await page.setViewport({width,height});for(let i=0;i<count;i++){await page.evaluate(i=>{Reveal.slide(i);Reveal.layout();},i);await settle();const s=await check();if(s.issues.length)responsive.push({viewport:[width,height],...s});}}await page.setViewport({width:1920,height:1080});
 let stateCount=0;const stateIssues=[],interactions=[];async function inspect(variant){await settle();const s=await check();if(s.issues.length)stateIssues.push({variant,...s});stateCount++;}
 async function settings(id,values){await page.evaluate(({id,values})=>{const w=CLWidgets.instances.find(w=>w.el.closest('section').id===id);for(const [k,v]of Object.entries(values))w.setting(k).value=v;w.render();},{id,values});await inspect(id+'/'+JSON.stringify(values));}
 const sources=await page.evaluate(()=>CLWidgets.instances.filter(w=>w.kind==='source').map(w=>({id:w.el.closest('section').id,sets:w.traces.map(t=>t.name)})));
 for(const s of sources){await go(s.id);for(const set of s.sets){await page.select(`#${s.id} [data-setting="set"]`,set);const n=await page.$$eval(`#${s.id} [data-setting="point"] option`,es=>es.length);for(let i=1;i<=n;i++){await page.select(`#${s.id} [data-setting="point"]`,String(i));await inspect(s.id+'/'+set+'/'+i);}}}
 await go('decision-lab');for(const p of [0,.1,.5,.7,1])for(const cost of [1,3,10])await settings('decision-lab',{p,cost});
 await go('naive-lab');for(const x1 of [-3,0,3])for(const x2 of [-3,0,3])for(const prior of [.05,.5,.95])await settings('naive-lab',{x1,x2,prior});
 await go('logistic-lab');for(const mid of [0,.5,1])for(const slope of [-20,0,20])for(const threshold of [.1,.5,.9])await settings('logistic-lab',{mid,slope,threshold});
 await go('neighbors-lab');for(const k of [1,3,5,9,15,25,49,50])for(const weight of ['Uniform','Inverse distance'])for(const scale of [.25,1,4])for(const [x,y]of [[-1.2,-.8],[.5,.2],[2.2,1.3]])await settings('neighbors-lab',{k,weight,scale,x,y});
 await go('regression-lab');for(const k of [1,3,7,15,25])for(const q of [-2,0,2])await settings('regression-lab',{k,q});
 await go('validation-lab');for(const k of [1,3,5,7,9,15,29]){await page.click('#validation-lab [data-action="restart"]');await page.select('#validation-lab [data-setting="k"]',String(k));await inspect('validation/'+k+'/hidden');assert.equal(await page.evaluate(()=>CLWidgets.instances.find(w=>w.kind==='validation').result.test),undefined);await page.click('#validation-lab [data-action="lock"]');await inspect('validation/'+k+'/locked');assert(await page.$eval('#validation-lab [data-setting="k"]',s=>s.disabled));assert(await page.$eval('#validation-lab [data-action="lock"]',s=>s.disabled));assert.equal(typeof await page.evaluate(()=>CLWidgets.instances.find(w=>w.kind==='validation').result.test),'number');}interactions.push('Validation candidate locking, hidden test and explicit restart');
 // Exercise native range inputs, not only their render handlers.
 for(const [id,key]of [['decision-lab','p'],['naive-lab','x1'],['logistic-lab','mid'],['neighbors-lab','x'],['regression-lab','q']]){await go(id);await page.focus(`#${id} [data-setting="${key}"]`);await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await settle();assert.equal(await page.$eval(`#${id} [data-output="${key}"]`,e=>e.textContent),await page.$eval(`#${id} [data-setting="${key}"]`,e=>e.value));interactions.push(id+': keyboard range control');}
 for(const id of ['data-lab','fit-lab','plane-lab','boundary-lab','decision-lab','naive-lab','logistic-lab','neighbors-lab','regression-lab','validation-lab']){await go(id);await page.click(`#${id} [data-action="pan"]`);await settle();assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.dragmode),'pan');await page.click(`#${id} [data-action="zoom"]`);await settle();const p=await page.$eval(`#${id} .rg-plot`,p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a._length*.2)*s,y:b.top+(y._offset+y._length*.2)*s,xx:b.left+(a._offset+a._length*.65)*s,yy:b.top+(y._offset+y._length*.7)*s};});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.xx,p.yy,{steps:7});await page.mouse.up();await delay(90);assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.autorange),false);await page.click(`#${id} [data-action="view"]`);await settle();assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.autorange),true);interactions.push(id+': pan, drag zoom and reset');}
 await go('fit-lab');await page.click('#fit-lab .legend .traces:first-child');await delay(350);assert.equal(await page.$eval('#fit-lab .rg-plot',p=>p.data[0].visible),'legendonly');interactions.push('Original model legend toggle');
 await go('data-lab');const h=await page.$eval('#data-lab .rg-plot',p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a.l2p(p.data[0].x[0]))*s,y:b.top+(y._offset+y.l2p(p.data[0].y[0]))*s};});await page.mouse.move(h.x,h.y);await delay(120);assert(await page.$('#data-lab .hoverlayer .hovertext'));interactions.push('Original data hover tooltip');
 await page.evaluate(()=>{for(const w of CLWidgets.instances.filter(w=>w.kind==='source'))for(let i=0;i<w.raw.data.length;i++)for(const k of ['x','y','z'])if(JSON.stringify(w.plot.data[i][k])!==JSON.stringify(w.raw.data[i][k]))throw Error('Source coordinates changed');});
 await page.evaluate(()=>{document.activeElement.blur();Reveal.slide(0);});for(let i=1;i<count;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),count-1);for(const id of ['boundary-lab','neighbors-lab','validation-lab','references']){await page.goto('about:blank');await page.goto(url+'#/'+id,{waitUntil:'load'});await page.waitForFunction(id=>Reveal.isReady()&&Reveal.getCurrentSlide().id===id,{},id);await page.evaluate(()=>deckReady);}
 const report={count,errors,offlineRequests:network,slides,responsive,stateIssues,stateCount,interactions,keyboardNavigation:true,directEntry:true};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({count,errors,network,issues:slides.filter(s=>s.issues.length),responsive,stateIssueCount:stateIssues.length,stateIssues:stateIssues.slice(0,5),stateCount,interactions:interactions.length},null,2));
 const files=slides.map((s,i)=>`${String(i+1).padStart(2,'0')}-${s.slide}.png`);fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>AIML · Classification 1 · Gallery</title><style>body{margin:0;background:#0b0f17;color:#e8ecf4;font:18px system-ui}header{padding:24px}a{color:#45d6c0}img{display:block;width:100%;height:auto}figure{margin:0 0 30px}figcaption{padding:12px 24px}@media print{@page{size:1920px 1080px;margin:0}header,figcaption{display:none}figure{margin:0;break-after:page}img{height:1080px}}</style><header>Lesson 5 · Classification 1 · ${count} slides · static previews<br><a href="../index.html">Open interactive presentation</a></header>${files.map((f,i)=>`<figure><img src="${f}" alt="Slide ${i+1}: ${slides[i].slide}"><figcaption>${i+1} / ${count} · ${slides[i].slide}</figcaption></figure>`).join('')}</html>`);await page.goto(pathToFileURL(path.join(out,'index.html')).href,{waitUntil:'load'});await page.pdf({path:path.join(out,'AIML-Classification-1-reviewed.pdf'),printBackground:true,preferCSSPageSize:true});assert.equal(errors.length+network.length+slides.filter(s=>s.issues.length).length+responsive.length+stateIssues.length,0,'Inspect audit.json for layout issues');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
