from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''): slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'): return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items): return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items): return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(t): return '<p class="takeaway">'+t+'</p>'
def math(t): return '<div class="formula">'+t+'</div>'
def diagram(k): return f'<div class="static-diagram" data-diagram="{k}"></div>'
def table(headers,rows): return '<table class="comparison"><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table>'
def lab(id,title,kind,prompt,notes,source=''): add(id,'Interactive lab · Classification',title,f'<p class="lab-prompt">{prompt}</p><div class="rg-widget" data-kind="{kind}" data-source="{source}"></div>',notes,'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 5','Classification 1','<div class="cover-layout"><div><p class="eyebrow">From observations to probabilities to decisions.</p><h1 class="search-title grad">Where do we<br>draw the line?</h1><p class="cover-sub">Bayes · Logistic regression · Neighbors</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · Reason with probabilities</span><span>02 · Estimate a classifier</span><span>03 · Choose and evaluate</span></div>','Based on course lesson 05_classification. The four original Plotly resources are preserved locally. Added labs use explicit illustrative assumptions; they are not medical decision tools.','cover-slide')
add('map','The road ahead','Three routes to a class prediction',cols(card('Naive Bayes','<p>Model how features look within each class, then apply Bayes’ theorem.</p>'),card('Logistic regression','<p>Model the probability of a class directly through a sigmoid.</p>','stat'),card('K-nearest neighbors','<p>Look at nearby training cases and aggregate their labels.</p>','comp'))+note('The model estimates a pattern. The decision rule turns that pattern into a label.'))
lab('data-lab','A numeric predictor, a categorical outcome','source','Inspect the original observations with hover, zoom or the point selector.','Source lr_logreg.json: 100 training observations; its test trace is empty. Labels and coordinates preserved. The course describes a cholesterol/disease illustration but provides no validated provenance or physical measurement definition. The displayed x scale is identified as illustrative.','lr_logreg')
add('classification','01 · The classification problem','A class label is not a continuous quantity',cols(card('Regression',math('ŷ ∈ ℝ')+'<p>Predict an amount: yield, price or duration.</p>'),card('Classification',math('ŷ ∈ {0, 1, …, C − 1}')+'<p>Predict a category: a label from a finite set.</p>','comp'))+note('Coding a class as 0 or 1 does not make ordinary least squares a probability model.'),'A linear probability model is possible, but its predictions can fall outside [0,1] and its error variance depends on the mean. Category numbers need not have quantitative spacing.')
add('uncertainty','01 · A probabilistic perspective','The same observed x may have different labels',cols(card('Aleatoric uncertainty','<p>Variation in Y remaining at a given X under the chosen description of the task.</p><p>More of the same data does not eliminate it.</p>','stat'),card('Epistemic uncertainty','<p>Uncertainty about the model or its parameters because our knowledge is limited.</p><p>More informative data can reduce it.</p>','comp'))+note('The distinction depends on what is observed and modeled; measurement error alone does not define the two categories.'),'Refines the source definitions. Improving measurements or observing new features can change the conditional task and its residual uncertainty. Finite-sample model uncertainty differs from inherent outcome variability under a fixed model.')
add('posterior','01 · From data to probabilities','Estimate the class distribution at x',math('p꜀(x) = P(Y = c | X = x)<br>p꜀(x) ≥ 0  Σ꜀ p꜀(x) = 1')+cols(card('Prediction','<p>Choose a label using the estimated probabilities and the cost of mistakes.</p>'),card('Confidence','<p>A concentrated distribution expresses confidence in the model’s own terms.</p>','stat'))+note('A confident prediction can still be wrong. Calibration asks whether predicted probabilities match observed frequencies.'),'This deck uses p for a true distribution and p̂ for an estimate. Probability at a continuous X is described by a conditional distribution, not by dividing two positive point probabilities.')
add('bayes-rule','01 · The optimal Bayes classifier','Under equal error costs, choose the largest probability',math('f*(x) = argmax꜀ P(Y = c | X = x)')+cols(card('Binary case',math('Predict 1 when p₁(x) ≥ ½')+'<p>A tie can be broken consistently either way.</p>','stat'),card('An ideal benchmark','<p>The rule assumes the true conditional probabilities are known.</p><p>Learned classifiers only estimate them.</p>','comp'))+note('“Optimal” here means minimum expected 0–1 loss for the given information X.'))
add('bayes-proof','01 · Why the rule is optimal','Minimize error separately at each x',cols(card('If we predict 0',math('P(error | x) = p₁(x)')),card('If we predict 1',math('P(error | x) = 1 − p₁(x)'),'stat'))+math('R(f) = Eₓ[P(Y ≠ f(X) | X)]')+note('Choose the smaller conditional error at every x. Averaging those minima gives the smallest overall risk.'),'Recasts the source expandable derivation using the law of total expectation. For C classes the conditional minimum error is 1−max_c p_c(x).')
add('bayes-error','01 · Limits of prediction','Even the ideal classifier can make mistakes',diagram('bayes')+note('At x with P(Y = 1 | x) = 0.7, predicting 1 still has a 30% conditional error probability.'),'Bayes risk is E[1−max_c p_c(X)]. It is not necessarily zero; overlapping class distributions create irreducible error for the given features.')
lab('decision-lab','Change the costs and the best decision changes','decision','Move the probability and false-negative cost. Compare the two expected losses.','Added binary decision-theory lab. False-positive cost is fixed at 1; false-negative cost ranges 1–10, correct decisions have zero cost. These are hypothetical costs, not medical recommendations. The Bayes cost threshold is C_FP/(C_FP+C_FN).')
add('accuracy','01 · Evaluate a classifier','Accuracy counts correct labels',math('Accuracy = (1/N) Σᵢ 𝟙(yᵢ = ŷᵢ)<br>Error rate = 1 − Accuracy')+cols(card('A useful summary','<p>Evaluate predictions on observations excluded from fitting and model selection.</p>','stat'),card('A possible blind spot','<p>If 95 of 100 labels are 0, always predicting 0 gives 95% accuracy.</p>','cyber'))+note('Also inspect which classes are missed and whether the decision costs match the task.'),'Accuracy is an empirical estimate of performance for a representative evaluation distribution, not a guarantee about deployment.')
add('confusion','01 · See the kinds of mistakes','A confusion matrix adds the missing detail',table(['Actual label','Predict 0','Predict 1'],[['0','True negative (TN)','False positive (FP)'],['1','False negative (FN)','True positive (TP)']])+cols(math('Precision = TP / (TP + FP)'),math('Recall = TP / (TP + FN)'))+note('If a denominator is zero, report the metric as undefined or state the convention used.'),'A brief addition to support threshold interpretation. Recall is sensitivity for the positive class; precision depends on the class prevalence in the evaluated population.')
add('bayes-theorem','02 · Naive Bayes','Reverse the direction with Bayes’ theorem',math('p(c | x) = p(x | c) p(c) / p(x)')+cols(card('Likelihood p(x | c)','<p>How compatible are the features with class c?</p>'),card('Prior p(c)','<p>How common is the class before observing x?</p>','comp'),card('Evidence p(x)','<p>Normalizes the scores across all classes.</p>','stat'))+note('For continuous features, p(x | c) and p(x) are densities; a density can exceed 1.'))
add('independence','02 · Naive Bayes','“Naive” means independent given the class',math('p(x₁, …, xₘ | c) ≈ ∏ⱼ p(xⱼ | c)')+diagram('naive')+note('This is conditional independence, not a claim that features are independent in the pooled dataset.'),'Naive Bayes uses mutual conditional independence of the features given the class. Pairwise independence alone is not sufficient for the full factorization.')
add('nb-score','02 · Naive Bayes','Compare log scores to avoid tiny products',math('s꜀(x) = log p(c) + Σⱼ log p(xⱼ | c)<br>ŷ = argmax꜀ s꜀(x)')+cols(card('For a label','<p>The evidence is the same for every class, so it cancels in the comparison.</p>','comp'),card('For a probability','<p>Normalize the class scores. Use a stable log-sum-exp calculation.</p>','stat'))+note('Dropping the evidence is valid for argmax; unnormalized scores are not posterior probabilities.'))
add('estimate','02 · Estimate the distributions','Choose a likelihood suited to each feature',table(['Feature','Example model','Estimated from training data'],[['Continuous','Gaussian within each class','Class-specific mean μⱼ꜀ and variance σ²ⱼ꜀'],['Continuous','Kernel density estimate','Density shape and bandwidth'],['Categorical','Class-conditional frequency','Counts with an explicit smoothing rule']])+note('Estimate class priors from representative training proportions, or specify justified prior probabilities.'),'The source includes parametric Gaussian, nonparametric density and categorical options. Gaussian parameters depend on both feature and class; source notation omitted the class subscript.')
add('smoothing','02 · Estimate the distributions','One unseen category should not erase a class',cols(card('Raw frequency',math('p̂(v | c) = nᵥ꜀ / n꜀')+'<p>An unseen category gives a zero probability and a zero product.</p>','cyber'),card('Additive smoothing',math('p̂(v | c) = (nᵥ꜀ + α) / (n꜀ + αV)')+'<p>V possible categories; α &gt; 0 is the smoothing strength.</p>','stat'))+note('This formula applies to a categorical feature with one observed category per case.'),'Added numerical stability and zero-frequency clarification. Gaussian Naive Bayes instead requires positive variances; implementations commonly apply variance smoothing.')
lab('naive-lab','Watch two features update a class probability','naive','Move the two feature values or change the prior. Inspect each contribution to the log score.','Added Gaussian Naive Bayes lab with explicitly specified independent conditional normals: class 0 means (−1,−1), class 1 means (1,1), all standard deviations 1. It illustrates assumed distributions, not a fit to course observations. The posterior log odds is logit(prior)+2x₁+2x₂.')
add('nb-limits','02 · Read Naive Bayes responsibly','Simple assumptions can work—and still mislead',cols(card('Why it can be useful',bullets('Few distribution parameters.','Fast class-score evaluation.','Works with suitable feature likelihoods.')),card('What to check',bullets('Correlated features can double-count evidence.','Probability calibration can be poor.','A wrong likelihood changes the scores.'),'cyber'))+note('Good classification accuracy does not by itself establish well-calibrated probabilities.'))
add('logistic','03 · Logistic regression','A linear score becomes a probability',math('z = β₀ + β₁x₁ + ⋯ + βₘxₘ<br>p̂₁(x) = σ(z) = 1 / (1 + e<sup>−z</sup>)')+cols(card('Score z','<p>A real-valued linear combination of features.</p>'),card('Sigmoid σ(z)','<p>Maps finite scores into the open interval (0, 1).</p>','stat'))+note('Model Y | X = x as Bernoulli(p̂₁(x)); randomness is expressed by the outcome distribution.'))
add('log-odds','03 · Logistic regression','The log odds are linear in the features',math('log[p̂₁(x) / (1 − p̂₁(x))] = β₀ + Σⱼ βⱼxⱼ')+cols(card('One unit more in xⱼ','<p>Holding the other features fixed, the modeled odds are multiplied by e<sup>βⱼ</sup>.</p>','stat'),card('Not a fixed probability change','<p>The probability change also depends on the starting score and the other features.</p>','comp'))+note('With a 0.5 threshold, the decision boundary is z = 0 in the chosen feature space.'),'Logistic regression is a generalized linear model. The probabilities are nonlinear in beta, but the log odds are linear. Intercept column x_i0=1 is explicit in the formula.')
lab('logistic-lab','Explore a sigmoid and its decision threshold','logistic','Change the midpoint, slope and threshold. The labels stay fixed while probabilities and predictions change.','Added explorer using the original 100 binary observations. Parameterization z=slope×(x−midpoint); β₀=−slope×midpoint and β₁=slope. Slider settings are illustrative and are not claimed to be an optimized fit. Training log loss and confusion counts are computed live.')
add('likelihood','03 · Maximum likelihood estimation','Reward the probability assigned to each observed label',math('L(β) = ∏ᵢ p̂ᵢ<sup>yᵢ</sup> (1 − p̂ᵢ)<sup>1−yᵢ</sup><br>β̂ = argmax<sub>β</sub> L(β)')+cols(card('When yᵢ = 1','<p>The contribution is p̂ᵢ. Higher probability for class 1 improves the likelihood.</p>','stat'),card('When yᵢ = 0','<p>The contribution is 1 − p̂ᵢ. Lower probability for class 1 improves the likelihood.</p>','comp'))+note('The product assumes conditionally independent outcomes given their features and the model.'),'Corrects max to argmax in the source estimator definition. Max is the objective value; argmax is a parameter vector attaining it.')
add('log-loss','03 · Maximum likelihood estimation','Minimize negative log likelihood',math('ℓ(β) = −Σᵢ [yᵢ log p̂ᵢ + (1 − yᵢ) log(1 − p̂ᵢ)]')+cols(card('Log loss','<p>Confident mistakes receive a large penalty.</p><p>Divide by n to report average log loss.</p>','cyber'),card('Numerical optimization','<p>Iterative solvers find coefficients.</p><p>A regularization penalty can control coefficient size.</p>','stat'))+note('Perfect separation can prevent an unregularized finite maximum-likelihood estimate from existing.'),'For a linear score the negative log likelihood is convex, but uniqueness and existence need conditions. Use stable softplus(z)−y*z in code. Multiclass extensions are deferred to later material.')
lab('fit-lab','Inspect the source’s supplied logistic curve','source','Compare probabilities along the supplied S-curve with the original binary observations.','Source lr_logreg_mod.json: original 100-point curve and 100 training observations retained. Test trace is empty. The source does not provide its fitting code, penalty or exact parameter settings, so the curve is labeled supplied rather than claimed to be a freshly computed unregularized MLE.','lr_logreg_mod')
add('thresholds','03 · From probability to decision','Fitting and threshold selection are different steps',cols(card('Fit the probability model','<p>Use training data to estimate coefficients.</p><p>Check predictive performance and calibration.</p>'),card('Choose the decision rule','<p>Select a threshold using costs or validation data.</p><p>Assess the complete procedure on final test data.</p>','stat'))+note('Changing the threshold changes predicted labels; it does not change the fitted probabilities.'))
lab('plane-lab','Two features create a geometric problem','source','Inspect both classes in the original two-dimensional dataset. Class 1 uses crosses as well as a different color.','Source cls_two_class.json: 25 observations in each of two classes. All coordinates and labels preserved. Axis notation translated from source X_0,X_1 into slide-wide feature 1,feature 2 labels.','cls_two_class')
add('knn-rule','04 · K-nearest neighbors','Let nearby training cases vote',math('p̂꜀(x) = K꜀(x) / K  ŷ = argmax꜀ p̂꜀(x)')+cols(card('Find neighbors','<p>Compute distances from the query to training observations; keep K nearest cases.</p>','comp'),card('Aggregate labels','<p>Count each class in that neighborhood.</p><p>K is a hyperparameter selected through validation.</p>','stat'))+note('The stored training set is part of the model. “Nonparametric” does not mean there is nothing to learn.'))
lab('boundary-lab','The original 1-neighbor decision regions','source','Pan and zoom the supplied separator. Toggle the class markers in the legend to inspect the regions.','Source cls_two_class_mod.json: all original coordinates and the full 200×200 contour grid preserved. This is the source K=1 boundary, not a refit on a subsample.','cls_two_class_mod')
lab('neighbors-lab','Move a query and inspect the neighbors that vote','neighbors','Adjust the query, K and distance scale. Rings mark the selected neighbors; the star is the query.','Added exact nearest-neighbor lab using all 50 source observations. Uniform and inverse-distance voting are available. Distance ties are broken by stable source order; vote ties choose class 0. Exact coordinate matches receive all weight under inverse-distance voting. Feature 2 scaling changes the metric and the colored decision regions.')
add('metric','04 · Geometry is part of the model','Distance depends on units and relevance',math('d(x, x′) = √[Σⱼ (xⱼ − x′ⱼ)²]')+cols(card('Scale thoughtfully','<p>A feature with large numerical units can dominate Euclidean distance.</p><p>Estimate any standardization from training data only.</p>','comp'),card('Choose meaningful features','<p>Irrelevant dimensions can make useful neighbors harder to identify.</p><p>A distance metric encodes a notion of similarity.</p>','stat'))+note('Changing units should trigger a review of the metric; scaling is not a universal guarantee of improvement.'))
add('ties','04 · Define edge cases','Odd K does not solve every tie',table(['Situation','What a complete implementation specifies'],[['Binary, uniform votes, odd K','Class-count tie is avoided'],['Multiclass or weighted voting','Vote ties can remain; use a deterministic rule'],['Equal distances at the K-th position','Choose a stable rule for which observations enter'],['Inverse distance with a zero distance','Define how exact matches are handled']])+note('Weighting neighbors by distance can help locally, but does not guarantee that ties disappear.'),'Corrects the blanket source tie advice. This deck uses source order for distance ties, the lowest label for tied votes, and only zero-distance neighbors when any are present under inverse-distance weighting.')
add('knn-density','04 · A probabilistic interpretation','A local density argument explains the vote',math('p̂(x) ≈ K / (nV)  p̂(x | c) ≈ K꜀ / (n꜀V)<br>p̂(c) = n꜀ / n')+math('p̂(c | x) ≈ [K꜀ / (n꜀V)] [n꜀ / n] / [K / (nV)] = K꜀ / K')+note('V is a small neighborhood volume around x. The density approximation motivates the empirical neighbor fraction.'),'The source treats the estimated fraction as the true posterior; this is an estimate. For a fixed region, the point count is binomial. In adaptive KNN the radius is random and K is fixed, so that fixed-region argument is heuristic rather than an exact finite-sample proof.')
add('knn-regression','04 · The same neighbors, a numeric target','For regression, average their outcomes',math('ŷ(x) = (1/K) Σ<sub>i ∈ Nₖ(x)</sub> yᵢ')+cols(card('Uniform average','<p>Every selected neighbor contributes equally.</p>'),card('Weighted average',math('ŷ(x) = Σᵢ wᵢyᵢ / Σᵢ wᵢ')+'<p>Use nonnegative weights with positive total.</p>','stat'))+note('The neighbor search is unchanged. Only the way their targets are aggregated changes.'))
lab('regression-lab','See a neighbor average become smoother','regression','Move the query and change K. Highlighted observations contribute to the prediction.','Added deterministic synthetic one-dimensional regression illustration with 25 points, y=sin(1.5x)+0.18cos(8x). No real-world units or empirical noise distribution are claimed. The curve is the actual uniform KNN prediction on a dense grid.')
add('complexity','05 · Choose K with validation','Small and large neighborhoods make different compromises',cols(card('K = 1',bullets('Highly local decisions.','Sensitive to particular training cases.','Can reproduce training labels.'),'cyber'),card('K = n',bullets('One global class majority.','One global mean for regression.','Ignores where the query is.'),'comp'))+note('Increasing K usually smooths the model: bias tends to rise and variance tends to fall.'),'The endpoint claims are for uniform weights. Duplicate coordinates with conflicting labels can prevent perfect K=1 training classification. Bias is task-dependent; larger K does not mathematically guarantee a monotone bias increase on every dataset.')
add('splits','05 · Choose K with validation','Keep the final test set out of model selection',diagram('splits')+cols(card('Train','<p>Fit preprocessing and store the reference cases.</p>'),card('Validate','<p>Compare candidate K values, metrics and thresholds.</p>','comp'),card('Test','<p>Assess the selected procedure once.</p>','stat'))+note('Repeatedly choosing a model from its test score turns that set into development data.'))
lab('validation-lab','Select K before revealing the test score','validation','Compare training and validation scores. Lock a K to reveal its result on the untouched test split.','Added reproducible class-stratified 30/10/10 split of the 50 source points. Candidates K=1,3,5,7,9,15,29. Uniform Euclidean voting. Ties in validation accuracy prefer smaller K. The selected classifier remains trained on the same 30 cases. Test labels never affect selection. Locking disables candidate changes; resetting is explicitly a fresh classroom demonstration, not a new independent test.')
add('validation-notes','05 · Choose K with validation','A small validation win may be unstable',cols(card('One split','<p>Useful for a transparent demonstration.</p><p>With 10 validation points, one prediction changes accuracy by 10 percentage points.</p>','comp'),card('Cross-validation','<p>Compare candidates across several training/validation folds.</p><p>Fit preprocessing inside each fold.</p>','stat'))+note('After model selection, a final refit on development data is possible; evaluate that exact refitted procedure on the held-out test.'))
add('tradeoffs','05 · Practical characteristics','Compare what each method must store and assume',table(['Method','What it uses','What deserves attention'],[['Naive Bayes','Priors + feature distributions per class','Likelihood choice; dependence; calibration'],['Logistic regression','Coefficients for a fixed feature map','Feature form; separation; regularization'],['K-nearest neighbors','Training cases + metric + K','Memory; query time; scale; dimension']])+note('A simple parametric model can be preferable when its structure fits the task; flexibility alone is not a reason to choose KNN.'))
add('cost','05 · Practical characteristics','Neighbor search can become expensive',cols(card('Storage',math('O(nm)')+'<p>Store n observations with m features, plus labels.</p>','comp'),card('Brute-force query',math('O(nm) + neighbor selection')+'<p>Compute distances to all training cases, then find the nearest K.</p>','stat'))+note('Tree indexes and approximate search can help, but their benefit depends on dimension, metric and required accuracy.'),'Full sorting adds O(n log n); partial selection or a heap can reduce that part. A precomputed all-pairs distance matrix requires quadratic storage and does not remove the need to compute distances for arbitrary new queries.')
add('workflow','05 · A reliable classification workflow','Make the entire prediction procedure reviewable','<ol class="steps"><li>Define labels, target population and the cost of mistakes.</li><li>Split data before fitting preprocessing or choosing a model.</li><li>Fit candidates and compare them on validation data.</li><li>Select the model, preprocessing and decision threshold.</li><li>Report held-out performance and the kinds of errors.</li></ol>','Predictive performance, probability calibration and causal explanation are different goals. A classifier trained on observational data is not by itself evidence of a causal mechanism.')
add('practice','Check your understanding','Four questions before you leave','<ol class="exercise-list"><li>Why can the optimal Bayes classifier still be wrong?</li><li>Which independence assumption makes Naive Bayes naive?</li><li>Does changing a threshold change logistic probabilities?</li><li>Why should K be selected using validation data?</li></ol>')
add('answers','Check your understanding','What a strong answer includes',table(['Question','Answer'],[['Bayes errors','The realized label can be the less probable class at x.'],['Naive assumption','Features are mutually independent conditional on the class.'],['Threshold change','It changes labels, while the fitted probabilities remain fixed.'],['Selecting K','Using test performance to choose K leaks evaluation feedback into selection.']]))
add('summary','The ideas to keep','Estimate uncertainty. Make a decision. Check it.',cols(card('Probabilities','<p>Bayes’ theorem connects class priors, likelihoods and posteriors.</p>'),card('Models','<p>Naive Bayes, logistic regression and KNN estimate class probabilities differently.</p>','comp'),card('Evaluation','<p>A threshold, a distance metric and K are part of the procedure that must be validated.</p>','stat'))+note('The best model is the one whose assumptions and measured behavior suit the intended task.'))
add('references','Sources and further reading','Follow the derivations and the original examples',bullets('<a href="https://www.aretor.it/courses/aiml2526/lessons/05_classification/">Alessandro Torcinovich · Classification 1 course resource</a>','<a href="https://www.statlearning.com/">James et al. · An Introduction to Statistical Learning · Chapter 4</a>','<a href="https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/">Bishop · Pattern Recognition and Machine Learning · Chapters 1 and 4</a>','<a href="https://scikit-learn.org/stable/modules/naive_bayes.html">scikit-learn · Naive Bayes</a> and <a href="https://scikit-learn.org/stable/modules/neighbors.html">Nearest Neighbors</a>')+note('The source map records the original resources, added demonstrations and technical clarifications. Use the HTML deck for interactivity; the PDF is static.'),'Adapted for the user’s existing course presentation. Attribution and the source site license notice are recorded in notes/source-map.md. No third-party decorative photographs are used.')

html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 5 — Classification 1 · AIML</title><link rel="stylesheet" href="lib/reveal/reset.min.css"><link rel="stylesheet" href="lib/reveal/reveal.min.css"><link rel="stylesheet" href="css/theme-base.css"><link rel="stylesheet" href="css/search.css"><link rel="stylesheet" href="css/regression.css"><link rel="stylesheet" href="css/classification.css"></head><body><div class="reveal"><div class="slides">'
for s in slides: html+=f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div><aside class="notes">{escape(s["notes"])}</aside></section>'
html+='</div></div><div class="lesson-tag">AIML · Lesson 5 — Classification 1</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav><script src="lib/reveal/reveal.min.js"></script><script src="lib/plotly.min.js"></script><script src="js/course-data.js"></script><script src="js/engine.js"></script><script src="js/visuals.js"></script><script src="js/widgets.js"></script><script src="js/deck.js"></script></body></html>'
(ROOT/'index.html').write_text(html,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 5 — Classification 1\n\n'+''.join(f'## {i}. {s["title"]}\n\n{s["notes"] or "Discuss the example and relate it to the model’s assumptions."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],ensure_ascii=False,indent=2),encoding='utf-8')
print('Built',len(slides),'slides.')
