from pathlib import Path
from html import escape
import json, math as pymath
ROOT=Path(__file__).resolve().parents[1]
slides=[]
def add(id,kicker,title,body,notes='',cls=''):slides.append(dict(id=id,kicker=kicker,title=title,body=body,notes=notes,cls=cls))
def card(label,text,tone='neural'):return f'<div class="card card-{tone}"><span class="label">{label}</span>{text}</div>'
def cols(*items):return '<div class="cols">'+''.join('<div class="col">'+i+'</div>' for i in items)+'</div>'
def bullets(*items):return '<ul class="tight">'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def note(t):return '<p class="takeaway">'+t+'</p>'
def math(t):return '<div class="formula">'+t+'</div>'
def diagram(k):return f'<div class="static-diagram" data-diagram="{k}"></div>'
def table(headers,rows):return '<table class="comparison"><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table>'
def lab(id,title,kind,prompt,notes,source=''):add(id,'Interactive lab · Classification 2',title,f'<p class="lab-prompt">{prompt}</p><div class="rg-widget" data-kind="{kind}" data-source="{source}"></div>',notes,'lab-slide')

add('title','AI &amp; Machine Learning · Lesson 6','Classification 2','<div class="cover-layout"><div><p class="eyebrow">Learn a boundary. Widen the margin. Change the space.</p><h1 class="search-title grad">A better way<br>to separate.</h1><p class="cover-sub">Neurons · Perceptrons · SVMs · Kernels</p></div>'+diagram('cover')+'</div><div class="chapter-strip"><span>01 · Learn a separator</span><span>02 · Maximize the margin</span><span>03 · Transform the geometry</span></div>','Adapted from course 06_classification2. All nine original Plotly charts are retained locally, including the rotatable 3D feature map. Five added labs explain thresholds, perceptron updates, margins, a kernel identity and fitted SVM decision regions.','cover-slide')
add('map','The road ahead','Three questions about a decision boundary',cols(card('Can we learn it?','<p>A perceptron adjusts a linear separator when a training example is misclassified.</p>'),card('Which separator?','<p>A support vector machine seeks a large margin while controlling violations.</p>','stat'),card('Which space?','<p>Feature maps and kernels let linear methods create nonlinear boundaries.</p>','comp'))+note('A decision score is not automatically a calibrated probability.'))
lab('and-lab','Start with the four cases of logical AND','source','Inspect the truth-table points. Only (1, 1) belongs to class 1.','Original cls_and.json: all four observations, labels and coordinates preserved.','cls_and')
add('threshold','01 · A threshold neuron','Aggregate the inputs, then apply a step',math('g(x) = x₁ + x₂  ŷ = 𝟙(g(x) ≥ θ)')+cols(card('AND requires',math('1 &lt; θ ≤ 2')+'<p>The sums are 0, 1, 1 and 2.</p>'),card('Threshold versus bias',math('ŷ = 𝟙(x₁ + x₂ + b ≥ 0)')+'<p>The equivalent additive bias is b = −θ.</p>','stat'))+note('This is the course’s simplified McCulloch–Pitts threshold unit; its settings are specified by hand.'),'Uses theta for the source’s threshold b to distinguish it from an additive bias. The original historical neuron model has more structure; this is the simplified teaching version in the resource.')
lab('threshold-lab','Move the threshold and change the logic','threshold','Adjust θ and compare the output with AND or OR. Inputs exactly on the threshold predict 1.','Added exact truth-table explorer with fixed weights (1,1), threshold −0.5 to 2.5 and AND/OR targets. A filled region shows x₁+x₂≥θ; all four predictions and their accuracy update.')
lab('and-fit-lab','Inspect the source’s AND separator','source','The supplied line uses θ = 1.9. Both points with input sum 1 remain on the class-0 side.','Original cls_and_mod.json, including the exact supplied separator endpoints. The line equation is x₁+x₂=1.9.','cls_and_mod')
add('perceptron','01 · A neuron that learns','Let the weights and bias adapt',math('s(x) = w₁x₁ + ⋯ + wₘxₘ + b<br>ŷ = 𝟙(s(x) ≥ 0)')+cols(card('Weights w','<p>Control the orientation of the separating hyperplane.</p>'),card('Bias b','<p>Moves the hyperplane away from the origin.</p>','comp'))+note('For the update rule, append x₀ = 1 and collect b with the other weights.'),'Following the source’s 0/1 perceptron convention. In two dimensions s(x)=0 is a line. The score is not passed through a sigmoid and is not a class probability.')
lab('noisy-lab','Replace ideal corners with noisy observations','source','Inspect the four clouds around the AND inputs. The upper-right cloud is class 1.','Original cls_and_noisy.json: 270 class-0 and 90 class-1 observations. All 360 original points retained.','cls_and_noisy')
add('update','01 · The perceptron update','Correct mistakes in the direction of the example',math('w̃ ← w̃ + η(yᵢ − ŷᵢ)x̃ᵢ  η &gt; 0')+table(['Observed / predicted','Update','Effect on this example’s score'],[['y = ŷ','No change','Already classified correctly'],['y = 1, ŷ = 0','Add ηx̃ᵢ','Increase the score'],['y = 0, ŷ = 1','Subtract ηx̃ᵢ','Decrease the score']])+note('x̃ includes the constant input, so the bias is updated too.'),'The source describes inspiration from Hebbian learning; the implemented rule is a supervised error-correction update using the observed label.')
add('update-intuition','01 · Why an update helps locally','The score moves by a squared input length',math('s<sub>new</sub>(xᵢ) = s<sub>old</sub>(xᵢ) + η(yᵢ − ŷᵢ)‖x̃ᵢ‖²')+cols(card('A missed class 1','<p>The score increases by a positive amount.</p>','stat'),card('A false class 1','<p>The score decreases by a positive amount.</p>','cyber'))+note('One update need not cross zero, and it can change predictions for other observations.'),'Makes the source intuition precise without implying a single update always fixes an error or improves total accuracy.')
lab('training-lab','Step through the perceptron’s learning process','training','Choose a dataset, then use Step, Epoch or Play. The sidebar shows the last example and its weight update.','Added exact 0/1 perceptron implementation using original AND, noisy AND or XOR points. Zero initialization; η=0.25,1,4; source or reversed order. A complete epoch without updates certifies convergence. Runs stop at 25 epochs if that has not occurred. Animation pauses when leaving the slide.')
lab('perceptron-fit-lab','Compare with the supplied trained perceptron','source','Inspect the original separator against all 360 noisy AND observations.','Original cls_and_noisy_mod.json. The finite endpoints and observations are unchanged. This supplied line is distinguished from the learning trace in the preceding lab; source training settings are not provided.','cls_and_noisy_mod')
add('convergence','01 · What convergence means','A complete quiet epoch is the stopping signal',cols(card('Separable training data','<p>Under the standard perceptron assumptions, a separator is reached after finitely many updates.</p>','stat'),card('Nonseparable training data','<p>A perfect linear separator does not exist. Repeated updates need a budget or another stopping rule.</p>','cyber'))+note('One correctly classified example is not convergence. Training convergence also does not establish test performance.'),'A finite dataset, a positive separating margin and cycling through all examples support the classical convergence guarantee. The source’s approximate single-weight-change stopping description is replaced by a no-update full pass.')
add('learning-rate','01 · Learning rate','A larger η does not always mean faster learning',math('w̃<sub>t</sub>(η) = η w̃<sub>t</sub>(1)')+cols(card('In this demonstration','<p>Start from zero, keep a positive constant η and use the same example order.</p><p>Scaling η scales the weights.</p>','stat'),card('The predicted labels','<p>The sign of the score is unchanged by a positive scale.</p><p>The mistake sequence is therefore the same in exact arithmetic.</p>','comp'))+note('Learning-rate effects depend on initialization, update rules and numerical precision.'),'Corrects the source’s universal claim that smaller η requires more updates and larger η speeds convergence. In the zero-initialized, unregularized standard perceptron, a constant positive factor rescales every iterate. The lab uses powers of two to avoid introducing rounding-driven differences between its η choices.')
lab('xor-lab','XOR exposes the limit of one linear separator','source','Opposite corners share a class. Try to imagine one line separating both pairs.','Original cls_xor.json: four original XOR points. The training lab can also be switched to these exact observations.','cls_xor')
add('xor-proof','01 · Why XOR is not linearly separable','The required inequalities contradict one another',cols(card('Class 0 at (0,0) and (1,1)',math('b &lt; 0<br>w₁ + w₂ + b &lt; 0')),card('Class 1 at (1,0) and (0,1)',math('w₁ + b ≥ 0<br>w₂ + b ≥ 0'),'comp'))+note('Adding the class-1 inequalities gives w₁+w₂+b ≥ −b &gt; 0, contradicting the class-0 condition.'),'This proof uses the deck’s predict-1-at-zero convention. Nonlinear features or multiple units can represent XOR. A multilayer perceptron is deferred to the later part of the course.')
lab('separators-lab','Equal training accuracy can hide different geometry','source','Compare the two supplied separators. Inspect how close each line comes to the classes.','Original cls_svm_both_mod.json: 180 observations per class and both source separators. The source calls the second line more vulnerable; the deck treats margin as a geometric criterion, not a guaranteed ordering of future test errors.','cls_svm_both_mod')
add('hyperplane','02 · Support vector machines','The weight vector is normal to the boundary',math('h(x) = wᵀx + b = 0')+diagram('normal')+note('w contains the feature weights. The bias b is kept separate and is not included in ‖w‖.'),'Clarifies the source’s notation switch: augmented weights are useful for the perceptron update, but the SVM regularizer and geometric norm exclude the bias.')
lab('margin-source-lab','Inspect the source’s margin construction','source','The solid line is the separator. Dashed lines bound the highlighted margin; the arrow shows its normal direction.','Original cls_svm_margin.json: ten observations, polygon, separator, both margin lines and weights-vector endpoints preserved. The source fixed viewport is retained to show the intended geometry rather than remote polygon vertices.','cls_svm_margin')
add('distance','02 · Measure a geometric margin','Normalize the score by the length of w',math('Signed distance = (wᵀx + b) / ‖w‖<br>Distance to the boundary = |wᵀx + b| / ‖w‖')+cols(card('Rescale the equation','<p>Multiplying w and b by a positive constant leaves the line and distances unchanged.</p>'),card('Fix a useful scale','<p>For a separable dataset, choose the closest class scores to be −1 and +1.</p>','stat'))+note('The formulas require ‖w‖ &gt; 0. A raw score is not itself a geometric distance.'))
add('margin-width','02 · Measure a geometric margin','The two support planes are 2 / ‖w‖ apart',math('wᵀx + b = −1  wᵀx + b = +1<br>Full margin width = 2 / ‖w‖')+cols(card('Relabel the classes',math('tᵢ = 2yᵢ − 1 ∈ {−1,+1}')),card('Write one constraint',math('tᵢ(wᵀxᵢ + b) ≥ 1'),'stat'))+note('These are hard-margin constraints: every training observation must lie on or beyond its class’s support plane.'))
lab('margin-lab','Rotate a separator and measure its clearance','margin','Adjust its normal angle and offset. Fit max-margin restores an independently solved optimum for these ten points.','Added geometric explorer using all ten source margin observations. The unit normal is (cos θ,sin θ); h=uᵀx+d. Signed clearance is min_i t_i h(x_i). Positive clearance yields full symmetric empty-strip width 2×clearance. Nonpositive clearance is explicitly not a separating margin. The optimum is solved and checked independently in Python.')
add('primal','02 · The hard-margin optimization','Minimize weight length subject to separation',math('minimize<sub>w,b</sub> ½‖w‖²<br>subject to tᵢ(wᵀxᵢ + b) ≥ 1 for every i')+cols(card('Objective','<p>A smaller weight norm means a wider margin under this scaling.</p>','stat'),card('Constraints','<p>Enforce the correct side and at least unit signed functional margin.</p>','comp'))+note('If the classes are not linearly separable in the selected feature space, this hard-margin problem is infeasible.'))
add('support-vectors','02 · Which points determine the solution?','Support vectors carry the boundary information',math('w = Σᵢ αᵢtᵢxᵢ  αᵢ ≥ 0')+cols(card('Positive multiplier','<p>In a hard-margin optimum, αᵢ &gt; 0 implies that the point touches its support plane.</p>','stat'),card('Zero multiplier','<p>The point does not contribute to this dual representation of w.</p>','comp'))+note('A point on a margin can have a zero multiplier in a degenerate solution.'),'Defines support vectors through nonzero dual multipliers and avoids asserting that every margin-touching observation must have a strictly positive alpha.')
add('soft-margin','02 · Allow imperfect separation','Slack variables make room for violations',math('minimize<sub>w,b,ξ</sub> ½‖w‖² + C Σᵢ ξᵢ<br>subject to tᵢ(wᵀxᵢ+b) ≥ 1 − ξᵢ, ξᵢ ≥ 0')+cols(card('Larger C','<p>Penalizes violations more strongly relative to the weight norm.</p>','cyber'),card('Smaller C','<p>Allows a stronger preference for a small norm, even with more violations.</p>','stat'))+note('C is a positive hyperparameter. Choose it with validation, together with preprocessing and the kernel.'),'Added bridge from the source’s hard-margin derivation to the practical SVM examples. C does not directly prescribe an exact number of classification errors.')
add('hinge','02 · Allow imperfect separation','A margin violation need not be a wrong label',math('ξᵢ = max(0, 1 − tᵢsᵢ)  at the minimum-slack choice')+table(['Signed functional margin tᵢsᵢ','Interpretation'],[['≥ 1','Correct side, on or beyond the margin'],['Between 0 and 1','Correct side, inside the margin'],['&lt; 0','Wrong side of the decision boundary']])+note('At score zero, classification depends on the stated tie rule. Hinge loss is not a probability loss.'),'For soft-margin SVM the dual box constraints are 0≤alpha_i≤C. Those with 0<alpha_i<C are on a support plane; points at alpha_i=C may lie within the margin or be misclassified.')
lab('circle-lab','Some class arrangements need a curved boundary','source','Inspect the inner cluster and surrounding ring. All 300 source observations are retained.','Original cls_circle_clusters.json. The squared-radius ranges of the two classes are disjoint, which allows the particular horizontal separating plane used later.','cls_circle_clusters')
add('feature-map','03 · Change the representation','Lift a circle into a third coordinate',math('ψ(x₁,x₂) = (x₁, x₂, x₁²+x₂²)')+diagram('lift')+note('A horizontal threshold z = τ becomes a circle x₁²+x₂² = τ when viewed in the original plane.'),'The source data are centered around the origin. A different center would require using centered coordinates or an appropriate feature map. The illustrative horizontal plane is not claimed to be the unique maximum-margin plane in the full three-dimensional space.')
lab('lift-lab','Rotate the original data in the lifted space','source3d','Drag to orbit, use Pan to move the view, or reset the camera. Toggle the separating plane to see the gap.','Original cls_circle_clusters_3d.json: all x,y,z arrays preserved and independently checked against z=x²+y². An optional added plane is placed midway between the maximum inner squared radius and minimum outer squared radius. The plane is a valid separator, not a claim to reproduce an unknown SVM fit.','cls_circle_clusters_3d')
add('mapping-limits','03 · Change the representation','A feature map offers a possibility, not a guarantee',cols(card('For this example','<p>The classes have disjoint squared-radius ranges, so a horizontal plane separates them.</p>','stat'),card('For an arbitrary dataset','<p>A chosen map may still leave overlap, noise or contradictory labels.</p>','cyber'))+note('More dimensions do not automatically make a useful model. Validation still decides whether the representation helps.'))
add('mapped-primal','03 · SVM in a feature space','Replace x with ψ(x) in the constraints',math('minimize<sub>w,b</sub> ½‖w‖²<br>subject to tᵢ[wᵀψ(xᵢ)+b] ≥ 1')+cols(card('Feature dimension d','<p>w now has one coordinate per mapped feature.</p>'),card('Original input dimension m','<p>Prediction can be nonlinear in the original m input coordinates.</p>','comp'))+note('The bias remains separate; the same soft-margin extension is available when the mapped data are not separable.'))
add('feature-explosion','03 · Why use a kernel?','Explicit polynomial features grow quickly',cols(card('m inputs, degree at most p',math('Number of monomials = (m+p choose p)')+'<p>This count includes the constant feature.</p>'),card('100 inputs, degree at most 10',f'<div class="big-number">{pymath.comb(110,10):,}</div><p>Distinct monomials, before any selection.</p>','cyber'))+note('A kernel can compute the needed inner product without materializing every mapped coordinate.'),'The count is binomial(110,10)=46,897,636,623,981 including the constant, or one less if the constant is handled as a separate intercept. Kernel computation does not remove dependence on sample size.')
add('lagrangian','03 · Derive a dual formulation','Attach one multiplier to each margin constraint',math('L(w,b,α) = ½‖w‖² − Σᵢ αᵢ{tᵢ[wᵀψ(xᵢ)+b] − 1}')+cols(card('Multipliers',math('αᵢ ≥ 0')+'<p>One multiplier for each training observation.</p>','comp'),card('Saddle-point problem',math('maximize<sub>α≥0</sub> minimize<sub>w,b</sub> L')+'<p>The constraints reappear in the dual.</p>','stat'))+note('This derivation assumes the feasible hard-margin problem. It does not turn the dual into an unconstrained optimization.'),'Corrects the source’s unconstrained-problem description. Feasibility and convexity support strong duality here; zero gradients of the Lagrangian alone do not constitute all KKT conditions.')
add('stationarity','03 · Derive a dual formulation','Eliminate the feature-space weights',math('∂L/∂w = 0 ⇒ w = Σᵢ αᵢtᵢψ(xᵢ)<br>∂L/∂b = 0 ⇒ Σᵢ αᵢtᵢ = 0')+note('The optimal normal lies in the span of the mapped training observations.'),'The bias stationarity equation is an equality constraint on alpha, not an expression that sets b=0. Bias is recovered separately from KKT conditions.')
add('dual','03 · Derive a dual formulation','Only pairwise inner products remain',math('maximize<sub>α</sub> Σᵢ αᵢ − ½ Σᵢ Σⱼ αᵢαⱼtᵢtⱼ ψ(xᵢ)ᵀψ(xⱼ)<br>subject to αᵢ ≥ 0, Σᵢ αᵢtᵢ = 0')+note('For soft-margin SVM, replace αᵢ ≥ 0 with 0 ≤ αᵢ ≤ C.'),'The input dimension is hidden in pairwise mapped inner products, but the dual has one coefficient per training observation. The bias is not included in the feature inner product unless a different model is explicitly defined.')
add('kernel-identity','03 · The kernel trick','Compute the inner product without the feature vector',math('κ(x,z) = ψ(x)ᵀψ(z)')+cols(card('A homogeneous quadratic map',math('ψ(x₁,x₂) = (x₁², √2 x₁x₂, x₂²)')),card('Its kernel',math('κ(x,z) = (xᵀz)²'),'stat'))+note('The √2 coefficient gives the cross term the correct weight.'),'This homogeneous quadratic map differs from the earlier paraboloid lift (x₁,x₂,x₁²+x₂²). Its associated kernel is the squared dot product. The paraboloid lift instead induces xᵀz+‖x‖²‖z‖².')
lab('kernel-lab','Check the quadratic kernel identity numerically','kernel','Move the two input vectors. Compare their mapped dot product with the squared original dot product.','Added live exact-formula explorer for ψ(x)=(x₁²,√2x₁x₂,x₂²). The chart shows contributions from its three coordinates; both calculations use the displayed vectors and agree to floating-point tolerance.')
add('kernel-prediction','03 · Predict with support vectors','Evaluate the boundary in terms of training cases',math('s(x) = Σᵢ αᵢtᵢ κ(xᵢ,x) + b<br>Predict +1 if s(x) ≥ 0; otherwise −1')+cols(card('Sparse representation','<p>Only nonzero αᵢ values contribute to the score.</p>','stat'),card('Recover the bias','<p>For a suitable margin support vector k:<br>b = tₖ − Σᵢ αᵢtᵢκ(xᵢ,xₖ).</p>','comp'))+note('This score is a signed decision value. Probability calibration is a separate step.'),'For a hard-margin support vector with positive alpha, t_k s(x_k)=1. For soft margin use a free support vector 0<alpha_k<C; if none exists, a bias can be chosen from the KKT-compatible interval.')
add('kernel-families','03 · Choose a kernel','Different kernels encode different geometry',table(['Kernel','Formula','Parameter or interpretation'],[['Linear','xᵀz','A hyperplane in the original features'],['Polynomial','(γxᵀz + r)ᵈ','d positive integer; γ,r ≥ 0'],['Gaussian / RBF','exp(−γ‖x−z‖²)','γ &gt; 0 controls the distance scale']])+note('The RBF kernel corresponds to an infinite-dimensional feature space, while each kernel evaluation is finite.'))
lab('svm-lab','Compare fitted boundaries on the same circular data','svm','Change the kernel, C and RBF γ. The rings identify support vectors of the selected fitted model.','Added offline explorer of 15 independently fitted scikit-learn SVC models on all 300 source circular observations. Linear and homogeneous degree-2 polynomial kernels each use C=0.1,1,100; RBF uses all nine C×gamma combinations, gamma=0.1,1,10. Raw coordinates, no hidden standardization. Support vectors and dual coefficients are stored; browser decision scores are evaluated from them and checked against Python references. Scores displayed are training scores, not validation estimates.')
add('valid-kernel','03 · What makes a valid kernel?','The Gram matrix must be positive semidefinite',math('Kᵢⱼ = κ(xᵢ,xⱼ)  K = Kᵀ<br>For every finite input set and vector v: vᵀKv ≥ 0')+cols(card('An inner-product kernel','<p>Symmetry and positive semidefiniteness support a feature-space interpretation.</p>','stat'),card('Not any similarity function','<p>A symmetric function alone need not be a valid kernel for the standard convex SVM.</p>','cyber'))+note('Mercer’s theorem gives related results under additional assumptions; the finite Gram-matrix condition is the useful criterion here.'))
add('kernel-cost','03 · What the trick saves—and what remains','Avoid huge feature vectors, keep an eye on n',cols(card('Feature computation','<p>A quadratic dot-product kernel costs O(m), while explicitly forming all quadratic features uses O(m²) coordinates.</p>','stat'),card('Training observations','<p>A dense n×n Gram matrix requires O(n²) storage. Solvers may cache only part of it.</p>','comp'))+note('Kernel methods can still be expensive on large datasets. Prediction cost grows with the number of support vectors.'),'Corrects the source’s exact 2m operation count and its conflation of feature count with operation count. Big-O expresses the relevant difference. Efficient solvers and approximate feature maps can reduce practical costs.')
add('workflow','Put the pieces together','Validate the representation and the classifier','<ol class="steps"><li>Define labels and separate development data from final test data.</li><li>Fit scaling or other preprocessing on training folds only.</li><li>Compare kernels and their parameters with validation.</li><li>Inspect margin violations, errors and support-vector counts.</li><li>Evaluate the complete chosen procedure on the held-out test.</li></ol>','Neither a visually clean boundary nor perfect training accuracy establishes generalization. Kernel and C settings in this deck are demonstrations, not selected recommendations.')
add('practice','Check your understanding','Four questions about separators','<ol class="exercise-list"><li>Why is one unchanged perceptron update not convergence?</li><li>Why does SVM divide a score by ‖w‖ to obtain a distance?</li><li>What happens to a hard-margin problem with overlapping labels?</li><li>Which computation does the kernel trick replace?</li></ol>')
add('answers','Check your understanding','What the answers should make clear',table(['Question','Answer'],[['Perceptron stopping','A complete pass with no errors is needed; later cases can still trigger updates.'],['Geometric distance','Rescaling the boundary equation must not change the distance.'],['Nonseparable data','Hard-margin constraints are infeasible in that feature space.'],['Kernel computation','Replace the mapped inner product ψ(x)ᵀψ(z) with κ(x,z).']]))
add('summary','The ideas to keep','Learn the line. Choose the margin. Change the space.',cols(card('Perceptron','<p>An error-correction rule can find a linear separator when one exists.</p>'),card('SVM','<p>A margin objective selects a separator; slack handles violations.</p>','stat'),card('Kernels','<p>Implicit feature-space inner products support nonlinear decision boundaries.</p>','comp'))+note('The geometry is useful only when the complete procedure performs well on the task you actually care about.'))
add('references','Sources and further reading','Return to the original charts and derivations',bullets('<a href="https://www.aretor.it/courses/aiml2526/lessons/06_classification2/">Alessandro Torcinovich · Classification 2 course resource</a>','<a href="https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/">Bishop · Pattern Recognition and Machine Learning · Chapters 4 and 7</a>','<a href="https://www.cs.cornell.edu/courses/cs4780/2018fa/lectures/lecturenote03.html">Cornell CS4780 · The Perceptron</a>','<a href="https://scikit-learn.org/stable/modules/svm.html">scikit-learn · Support Vector Machines</a>')+note('The source map records the original resources, added labs and technical clarifications. Use the HTML deck for interactivity; the PDF is static.'))

html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lesson 6 — Classification 2 · AIML</title>'+''.join(f'<link rel="stylesheet" href="{f}">' for f in ['lib/reveal/reset.min.css','lib/reveal/reveal.min.css','css/theme-base.css','css/search.css','css/regression.css','css/classification.css','css/classification2.css'])+'</head><body><div class="reveal"><div class="slides">'
for s in slides:html+=f'<section id="{s["id"]}" data-slide="{s["id"]}" class="{s["cls"]}"><span class="kicker">{s["kicker"]}</span><div class="slide-body"><h2>{s["title"]}</h2>{s["body"]}</div><aside class="notes">{escape(s["notes"])}</aside></section>'
html+='</div></div><div class="lesson-tag">AIML · Lesson 6 — Classification 2</div><nav class="deck-nav" aria-label="Slide navigation"><button data-nav="prev" aria-label="Previous slide">←</button><button data-nav="overview">Overview</button><button data-nav="next" aria-label="Next slide">→</button></nav>'+''.join(f'<script src="{f}"></script>' for f in ['lib/reveal/reveal.min.js','lib/plotly.min.js','js/course-data.js','js/models.js','js/engine.js','js/visuals.js','js/widgets.js','js/deck.js'])+'</body></html>'
(ROOT/'index.html').write_text(html,encoding='utf-8')
(ROOT/'notes/slide-notes.md').write_text('# Lesson 6 — Classification 2\n\n'+''.join(f'## {i}. {s["title"]}\n\n{s["notes"] or "Explain the displayed relationship and connect it to the preceding example."}\n\n' for i,s in enumerate(slides,1)),encoding='utf-8')
(ROOT/'notes/slide-manifest.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in slides],ensure_ascii=False,indent=2),encoding='utf-8')
print('Built',len(slides),'slides.')
