const assert=require('node:assert/strict'),E=require('../js/engine.js'),fs=require('fs'),path=require('path'),fitted=require('../data/fitted-models.json'),refs=require('./model-reference.json'),perceptron=require('./perceptron-reference.json');let checks=0;
function close(a,b,t=1e-8){assert(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);checks++;}function eq(a,b){assert.deepEqual(a,b);checks++;}
const ps=name=>require('../data/'+name+'.json').data.filter(t=>t.name.startsWith('Class ')).flatMap((t,c)=>t.x.map((x,i)=>({x,y:t.y[i],c})));
for(const r of refs){const m=fitted.models[r.index],points=ps('cls_circle_clusters');r.queries.forEach((x,i)=>close(E.score(m,x),r.scores[i]));points.forEach((p,i)=>close(E.score(m,[p.x,p.y]),r.trainScores[i]));close(points.filter(p=>(E.score(m,[p.x,p.y])>=0?1:0)===p.c).length/points.length,m.accuracy);close(m.dual.reduce((s,v)=>s+v,0),0,1e-6);}
for(const r of perceptron){const t=E.training(ps(r.name),r.eta,r.reverse),last=t.states.at(-1);eq(last.seen,r.seen);eq(last.updates,r.updates);eq(t.converged,r.converged);last.w.forEach((w,i)=>close(w,r.w[i]));for(const s of r.states){const actual=t.states[s.seen];actual.w.forEach((w,i)=>close(w,s.w[i]));eq(actual.updates,s.updates);eq(actual.last.guess,s.guess);}}
for(const name of ['cls_and','cls_and_noisy','cls_xor'])for(const reverse of [false,true]){const a=E.training(ps(name),1,reverse);for(const eta of [.25,4]){const b=E.training(ps(name),eta,reverse);eq(a.states.length,b.states.length);for(let i=0;i<a.states.length;i++){a.states[i].w.forEach((v,j)=>close(b.states[i].w[j],eta*v,1e-12));eq(a.states[i].last?.guess,b.states[i].last?.guess);}}}
const margin=E.margin(ps('cls_svm_margin'),fitted.margin.normal,fitted.margin.offset);close(margin.width,fitted.margin.width);eq(margin.correct,10);eq(E.margin(ps('cls_svm_margin'),[1,0],-1.4).width,null);close(E.margin(ps('cls_svm_margin'),fitted.margin.normal.map(v=>v*7),fitted.margin.offset*7).width,margin.width);
for(const a of [[0,0],[1,2],[-2,1],[.25,-.75]])for(const b of [[1,2],[2,-1],[-.5,.75],[0,0]])close(E.dot(E.psi(a),E.psi(b)),E.kernel(a,b,'poly'),1e-12);
eq(E.clippedLine([1,0],-.5,[-1,1,-1,1]),[[.5,-1],[.5,1]]);eq(E.clippedLine([0,0],0,[-1,1,-1,1]),[]);eq(E.clippedLine([1,1],-3,[-1,1,-1,1]),[]);
const lift=require('../data/cls_circle_clusters_3d.json');lift.data.forEach((t,c)=>t.x.forEach((x,i)=>{close(t.z[i],x*x+t.y[i]**2,1e-13);eq(t.z[i]>=fitted.lift.threshold?1:0,c);}));
const report={checks,modelCount:refs.length,independentDecisionScores:refs.length*(81+300),perceptronCases:perceptron.length,sourceLiftPoints:300};fs.writeFileSync(path.resolve(__dirname,'../_review/engine-audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
