const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
module.exports=async function({page,go,settle,check,count,slides,errors,network,root,out,url,delay}){
 const responsive=[];for(const [width,height]of [[1366,768],[1024,768]]){await page.setViewport({width,height});for(let i=0;i<count;i++){await page.evaluate(i=>{Reveal.slide(i);Reveal.layout();},i);await settle();const s=await check();if(s.issues.length)responsive.push({viewport:[width,height],...s});}}await page.setViewport({width:1920,height:1080});
 let stateCount=0;const stateIssues=[],interactions=[];async function inspect(variant){await settle();const s=await check();if(s.issues.length)stateIssues.push({variant,...s});stateCount++;}
 async function settings(id,values){await page.evaluate(({id,values})=>{const w=C2Widgets.instances.find(w=>w.el.closest('section').id===id);for(const [k,v]of Object.entries(values))w.setting(k).value=v;if(w.kind==='margin')w.exact=null;if(w.kind==='training'){w.pause();w.trace=null;w.cursor=0;}w.render();},{id,values});await inspect(id+'/'+JSON.stringify(values));}
 const sources=await page.evaluate(()=>C2Widgets.instances.filter(w=>w.kind.startsWith('source')).map(w=>({id:w.el.closest('section').id,sets:w.traces.map(t=>t.name)})));
 for(const s of sources){await go(s.id);for(const set of s.sets){await page.select(`#${s.id} [data-setting="set"]`,set);const n=await page.$$eval(`#${s.id} [data-setting="point"] option`,es=>es.length),indices=n<=10?Array.from({length:n},(_,i)=>i+1):[1,2,Math.floor(n/2),n-1,n];for(const i of indices){await page.select(`#${s.id} [data-setting="point"]`,String(i));await inspect(s.id+'/'+set+'/'+i);}}}
 console.log('Original chart selectors checked.');
 await go('threshold-lab');for(const task of ['AND','OR'])for(let i=0;i<=30;i++)await settings('threshold-lab',{task,theta:fmt(-.5+i*.1)});
 await go('training-lab');for(const dataset of ['AND','Noisy AND','XOR'])for(const eta of [.25,1,4])for(const order of ['Source','Reverse']){await settings('training-lab',{dataset,eta,order});const info=await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.kind==='training');return {n:w.points.length,last:w.trace.states.length-1};}),indices=[...new Set([0,1,2,3,4,info.n-1,info.n,info.n+1,Math.floor(info.last/2),info.last-1,info.last])].filter(i=>i<=info.last);for(const cursor of indices){await page.evaluate(cursor=>{const w=C2Widgets.instances.find(w=>w.kind==='training');w.cursor=cursor;w.render();},cursor);await inspect('training/'+[dataset,eta,order,cursor].join('/'));}const end=await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').result);assert.equal(end.converged,dataset!=='XOR');}
 console.log('Perceptron states checked.');
 await go('margin-lab');for(const angle of [-60,-30,0,17,45,80])for(const offset of [-1.5,-.4,0,.4,1.5])await settings('margin-lab',{angle,offset});await page.click('#margin-lab [data-action="fit"]');await inspect('margin/exact-optimum');assert(Math.abs(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='margin').result.width)-require('../data/fitted-models.json').margin.width)<1e-10);interactions.push('Exact maximum-margin restore');
 await go('kernel-lab');for(const a1 of [-2,0,2])for(const a2 of [-2,0,2])for(const b1 of [-2,0,2])for(const b2 of [-2,0,2])await settings('kernel-lab',{a1,a2,b1,b2});
 await go('svm-lab');for(const kernel of ['Linear','Quadratic','RBF'])for(const C of [.1,1,100])for(const gamma of kernel==='RBF'?[.1,1,10]:[1]){await settings('svm-lab',{kernel,C,gamma});assert.equal(await page.$eval('#svm-lab [data-setting="gamma"]',s=>s.disabled),kernel!=='RBF');await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.kind==='svm'),m=w.result;for(const [j,i]of [[0,0],[20,30],[40,40],[80,80]]){const v=C2Engine.score(m,[w.surface.x[i],w.surface.y[j]]);if(Math.abs(v-w.surface.z[j][i])>1e-10)throw Error('Boundary grid disagrees with selected model');}});}
 console.log('Margin and kernel configurations checked.');
 // Real control interactions.
 await go('training-lab');await page.select('#training-lab [data-setting="dataset"]','AND');await settle();await page.click('#training-lab [data-action="step"]');await settle();assert.equal(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').cursor),1);await page.click('#training-lab [data-action="epoch"]');await settle();assert.equal(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').cursor),4);await page.click('#training-lab [data-action="reset"]');await settle();assert.equal(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').cursor),0);interactions.push('Perceptron step, epoch and reset');
 await page.click('#training-lab [data-action="play"]');await delay(1500);await page.click('#training-lab [data-action="play"]');await settle();assert(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').cursor>=1));assert.equal(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').timer),null);interactions.push('Perceptron play and pause');await page.click('#training-lab [data-action="play"]');await go('convergence');assert.equal(await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='training').timer),null);interactions.push('Perceptron pauses on slide exit');
 for(const [id,key]of [['threshold-lab','theta'],['margin-lab','angle'],['kernel-lab','a1']]){await go(id);await page.focus(`#${id} [data-setting="${key}"]`);await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await settle();assert.equal(await page.$eval(`#${id} [data-output="${key}"]`,e=>e.textContent),await page.$eval(`#${id} [data-setting="${key}"]`,e=>e.value));interactions.push(id+': keyboard slider');}
 const ids=await page.evaluate(()=>C2Widgets.instances.filter(w=>w.kind!=='source3d').map(w=>w.el.closest('section').id));
 for(const id of ids){await go(id);await page.click(`#${id} [data-action="view"]`);await settle();const home=await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice());await page.click(`#${id} [data-action="pan"]`);await settle();assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.dragmode),'pan');await page.click(`#${id} [data-action="zoom"]`);await settle();const p=await page.$eval(`#${id} .rg-plot`,p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a._length*.2)*s,y:b.top+(y._offset+y._length*.2)*s,xx:b.left+(a._offset+a._length*.65)*s,yy:b.top+(y._offset+y._length*.7)*s};});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.xx,p.yy,{steps:7});await page.mouse.up();await delay(100);const zoom=await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice());assert.notDeepEqual(zoom,home);await page.click(`#${id} [data-action="view"]`);await settle();const restored=await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice());restored.forEach((v,i)=>{if(typeof v==='number')assert(Math.abs(v-home[i])<1e-5, id+': reset mismatch '+JSON.stringify({home,restored}));else assert.equal(v,home[i]);});interactions.push(id+': pan, drag zoom, reset');}
 await go('lift-lab');await page.click('#lift-lab [data-action="view"]');await settle();const camera=()=>page.$eval('#lift-lab .rg-plot',p=>JSON.parse(JSON.stringify(p._fullLayout.scene._scene.getCamera()))),homeCamera=await camera(),rect=await page.$eval('#lift-lab .rg-plot',p=>{const b=p.getBoundingClientRect();return{x:b.left+b.width*.5,y:b.top+b.height*.45};});await page.mouse.move(rect.x,rect.y);await page.mouse.down();await page.mouse.move(rect.x+90,rect.y+30,{steps:10});await page.mouse.up();await delay(200);assert.notDeepEqual(await camera(),homeCamera);interactions.push('Original 3D chart: pointer orbit');await page.click('#lift-lab [data-action="pan"]');await settle();assert.equal(await page.$eval('#lift-lab .rg-plot',p=>p._fullLayout.scene.dragmode),'pan');const beforePan=await camera();await page.mouse.move(rect.x,rect.y);await page.mouse.down();await page.mouse.move(rect.x+60,rect.y,{steps:7});await page.mouse.up();await delay(200);assert.notDeepEqual(await camera(),beforePan);interactions.push('Original 3D chart: pointer pan');await page.click('#lift-lab [data-action="zoom"]');await settle();const beforeZoom=await camera();await page.mouse.move(rect.x,rect.y);await page.mouse.wheel({deltaY:-180});await delay(300);assert.notDeepEqual(await camera(),beforeZoom);interactions.push('Original 3D chart: wheel zoom');await page.click('#lift-lab [data-action="view"]');await settle();{const actual=await camera();for(const key of ['eye','center','up'])for(const axis of ['x','y','z'])assert(Math.abs(actual[key][axis]-homeCamera[key][axis])<1e-8,'Camera reset '+key+'.'+axis);};interactions.push('Original 3D chart: camera reset');
 for(const visible of [false,true]){await page.click('#lift-lab [data-action="plane"]');await inspect('lift/plane/'+visible);assert.equal(await page.$eval('#lift-lab .rg-plot',p=>p.data.length),visible?3:2);}interactions.push('3D separating plane toggle');await page.screenshot({path:path.join(out,'3d-interaction-review.png')});
 await go('and-fit-lab');await page.click('#and-fit-lab .legend .traces:first-child');await delay(350);assert.equal(await page.$eval('#and-fit-lab .rg-plot',p=>p.data[0].visible),'legendonly');interactions.push('Original chart legend toggle');await go('and-lab');const h=await page.$eval('#and-lab .rg-plot',p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a.l2p(p.data[0].x[0]))*s,y:b.top+(y._offset+y.l2p(p.data[0].y[0]))*s};});await page.mouse.move(h.x,h.y);await delay(150);assert(await page.$('#and-lab .hoverlayer .hovertext'));interactions.push('Original chart point hover');
 await page.evaluate(()=>{for(const w of C2Widgets.instances.filter(w=>w.kind.startsWith('source')))for(let i=0;i<w.raw.data.length;i++)for(const k of ['x','y','z'])if(JSON.stringify(w.plot.data[i][k])!==JSON.stringify(w.raw.data[i][k]))throw Error('Source coordinates changed');});
 await page.evaluate(()=>{document.activeElement.blur();Reveal.slide(0);});for(let i=1;i<count;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),count-1);for(const id of ['training-lab','lift-lab','svm-lab','references']){await page.goto('about:blank');await page.goto(url+'#/'+id,{waitUntil:'load'});await page.waitForFunction(id=>Reveal.isReady()&&Reveal.getCurrentSlide().id===id,{},id);await page.evaluate(()=>deckReady);}
 const report={count,errors,offlineRequests:network,slides,responsive,stateIssues,stateCount,interactions,keyboardNavigation:true,directEntry:true};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({count,errors,network,issues:slides.filter(s=>s.issues.length),responsive,stateIssues:stateIssues.slice(0,10),stateIssueCount:stateIssues.length,stateCount,interactions:interactions.length},null,2));
 const files=slides.map((s,i)=>`${String(i+1).padStart(2,'0')}-${s.slide}.png`);fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>AIML · Classification 2 · Gallery</title><style>body{margin:0;background:#0b0f17;color:#e8ecf4;font:18px system-ui}header{padding:24px}a{color:#45d6c0}img{display:block;width:100%;height:auto}figure{margin:0 0 30px}figcaption{padding:12px 24px}@media print{@page{size:1920px 1080px;margin:0}header,figcaption{display:none}figure{margin:0;break-after:page}img{height:1080px}}</style><header>Lesson 6 · Classification 2 · ${count} slides · static previews<br><a href="../index.html">Open interactive presentation</a></header>${files.map((f,i)=>`<figure><img src="${f}" alt="Slide ${i+1}: ${slides[i].slide}"><figcaption>${i+1} / ${count} · ${slides[i].slide}</figcaption></figure>`).join('')}</html>`);await page.goto(pathToFileURL(path.join(out,'index.html')).href,{waitUntil:'load'});await page.pdf({path:path.join(out,'AIML-Classification-2-reviewed.pdf'),printBackground:true,preferCSSPageSize:true});assert.equal(errors.length+network.length+slides.filter(s=>s.issues.length).length+responsive.length+stateIssues.length,0,'Inspect audit.json for issues');
};
function fmt(v){return v.toFixed(1);}
