const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),E=require('../js/engine.js'),M=require('../data/teaching-models.json');let checks=0;
const close=(a,b,tol=1e-8)=>{assert(Number.isFinite(a)&&Number.isFinite(b));assert(Math.abs(a-b)<=tol*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);checks++;};
for(const s of M.selection){let total=0;M.points.forEach((p,i)=>{const ds=s.centers.map(c=>E.dist(p,c)**2),j=s.labels[i];close(ds[j],Math.min(...ds));total+=ds[j];if(s.k>1)close(E.silhouette(M.points,s.labels,i).s,s.samples[i]);});close(total,s.inertia);}
close(E.silhouette([[0,0],[1,0],[4,0]],[0,1,1],0).s,0);close(E.silhouette([[0,0],[0,0],[0,0]],[0,0,1],0).s,0);assert.equal(E.silhouette([[0,0],[1,0]],[0,0],0).s,null);
for(const states of Object.values(M.kmeans))for(let i=0;i<states.length;i++){const s=states[i];let total=0;M.points.forEach((p,j)=>total+=E.dist(p,s.centers[s.labels[j]])**2);close(total,s.inertia);if(i)assert(s.inertia<=states[i-1].inertia+1e-7);if(s.phase.startsWith('Assign'))M.points.forEach((p,j)=>close(E.dist(p,s.centers[s.labels[j]]),Math.min(...s.centers.map(c=>E.dist(p,c)))));if(s.phase.startsWith('Update'))s.centers.forEach((c,k)=>{const points=M.points.filter((_,j)=>s.labels[j]===k);if(points.length)for(let d=0;d<2;d++)close(c[d],points.reduce((s,p)=>s+p[d],0)/points.length);});}
let responsibilityVectors=0;for(const s of M.gmm){close(s.weights.reduce((a,b)=>a+b),1);M.points.forEach((p,i)=>{const r=E.responsibility(s,p);r.forEach((v,k)=>{assert(v>=0&&v<=1);close(v,s.responsibilities[i][k]);});close(r.reduce((a,b)=>a+b),1);responsibilityVectors++;});}
for(const [method,h]of Object.entries(M.hierarchy)){for(let count=0;count<=5;count++){const l=E.partition(h.merges,6,count);assert.equal(new Set(l).size,6-count);assert(l.every(v=>Number.isInteger(v)));}const clusters=new Map(M.hierarchyPoints.map((p,i)=>[i,[p]]));const distance=(a,b)=>{const ds=a.flatMap(x=>b.map(y=>E.dist(x,y)));if(method==='single')return Math.min(...ds);if(method==='complete')return Math.max(...ds);if(method==='average')return ds.reduce((a,b)=>a+b)/ds.length;const mean=p=>[0,1].map(j=>p.reduce((s,x)=>s+x[j],0)/p.length);return E.dist(mean(a),mean(b));};h.merges.forEach(([a,b,height],i)=>{close(height,distance(clusters.get(a),clusters.get(b)));const g=[...clusters.values()];let min=Infinity;g.forEach((a,j)=>g.slice(j+1).forEach(b=>min=Math.min(min,distance(a,b))));close(height,min);const merged=[...clusters.get(a),...clusters.get(b)];clusters.delete(a);clusters.delete(b);clusters.set(6+i,merged);});}
let pcaAngles=0;for(const p of Object.values(M.pca)){for(let deg=-90;deg<=90;deg++){const r=E.projection(p.points,deg*Math.PI/180),u=r.u,s=p.covariance;close(r.variance,u[0]**2*s[0][0]+2*u[0]*u[1]*s[0][1]+u[1]**2*s[1][1]);close(r.sse,(p.points.length-1)*(r.total-r.variance));close(r.mean[0],p.mean[0]);close(r.mean[1],p.mean[1]);r.projected.forEach((q,i)=>close((p.points[i][0]-q[0])*u[0]+(p.points[i][1]-q[1])*u[1],0));pcaAngles++;}const best=E.projection(p.points,Math.atan2(p.components[0][1],p.components[0][0]));close(best.variance,p.eigenvalues[0]);close(best.sse,(p.points.length-1)*p.eigenvalues[1]);}
const report={passed:true,assertions:checks,silhouetteComparisons:2160,responsibilityVectors,pcaAngles,kmeansRuns:9,kmeansStates:79,hierarchyMethods:4};fs.writeFileSync(path.join(__dirname,'../_review/engine-audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
