const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
module.exports=async function({page,go,settle,check,count,slides,errors,network,root,out,url,delay}){
 const stateIssues=[],responsive=[],interactions=[];let stateCount=0;
 async function inspect(label){await settle();const a=await check();if(a.issues.length)stateIssues.push({label,issues:a.issues});stateCount++;}
 async function settings(id,obj){await page.evaluate(({id,obj})=>{const w=C2Widgets.instances.find(w=>w.el.closest('section').id===id);for(const [k,v]of Object.entries(obj)){const e=w.setting(k);e.value=v;e.dispatchEvent(new Event(e.type==='range'?'input':'change',{bubbles:true}));}},{id,obj});await inspect(id+JSON.stringify(obj));}
 async function original(){await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.el.closest('section')===Reveal.getCurrentSlide());let raw=w.raw.data;if(w.kind==='frames')raw=w.raw.frames[w.num('frame')].data;if(w.kind==='panel')raw=raw.slice(w.panelIndex*2,w.panelIndex*2+2);for(let i=0;i<raw.length;i++)for(const key of ['x','y'])if(JSON.stringify(raw[i][key])!==JSON.stringify(w.plot.data[i][key]))throw Error('Source coordinates altered: '+w.name);});}
 for(const [width,height]of [[1440,900],[1280,720]]){await page.setViewport({width,height});for(let i=0;i<count;i++){await page.evaluate(i=>Reveal.slide(i),i);await settle();const a=await check();if(a.issues.length)responsive.push({width,height,...a});}}await page.setViewport({width:1920,height:1080});
 for(const id of ['data-lab','elbow-source','dendrogram-source','aligned-lab','rotated-lab','scale-source']){await go(id);await original();}
 await go('source-animation');for(let frame=0;frame<5;frame++){await settings('source-animation',{frame});await original();}
 await go('kmeans-lab');for(const k of [2,3,4])for(const seed of [0,7,19]){await page.select('#kmeans-lab [data-setting="k"]',String(k));await page.select('#kmeans-lab [data-setting="seed"]',String(seed));const n=await page.evaluate(()=>C2Widgets.instances.find(w=>w.kind==='kmeans').trace.length);for(let i=0;i<n;i++){await page.evaluate(i=>{const w=C2Widgets.instances.find(w=>w.kind==='kmeans');w.cursor=i;w.render();},i);await inspect(`kmeans/${k}/${seed}/${i}`);}}
 console.log('All original animation frames and added K-means states checked.');
 await go('selection-lab');for(let k=1;k<=10;k++)for(const view of ['Partition','Distortion','Silhouette'])await settings('selection-lab',{k,view});
 await go('silhouette-lab');for(let k=2;k<=10;k++)for(const point of [1,2,120,239,240]){await settings('silhouette-lab',{k,point});await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.kind==='silhouette');if(Math.abs(w.result.s-Models.selection[w.num('k')-1].samples[w.num('point')-1])>1e-9)throw Error('Silhouette mismatch');});}
 await go('gmm-lab');for(let iteration=0;iteration<=40;iteration++)for(const point of [1,120,240]){await settings('gmm-lab',{iteration,point});await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.kind==='gmm'),expected=Models.gmm[w.num('iteration')].responsibilities[w.num('point')-1];w.result.responsibilities.forEach((v,k)=>{if(Math.abs(v-expected[k])>1e-9)throw Error('Responsibility mismatch');});});}
 console.log('Selection, silhouettes and all EM iterations checked.');
 await go('hierarchy-lab');for(const linkage of ['single','complete','average','centroid'])for(let merges=0;merges<=5;merges++)await settings('hierarchy-lab',{linkage,merges});
 await go('pca-lab');for(const data of ['Rotated','Axis-aligned']){for(let angle=-90;angle<=90;angle+=10){await settings('pca-lab',{data,angle});await page.click('#pca-lab [data-action="lines"]');await inspect(`pca/${data}/${angle}/no-lines`);await page.click('#pca-lab [data-action="lines"]');}await page.click('#pca-lab [data-action="best"]');await inspect('pca/'+data+'/best');await page.evaluate(()=>{const w=C2Widgets.instances.find(w=>w.kind==='pca'),p=Models.pca[w.value('data')==='Rotated'?'gaussian_points_rot30':'gaussian_points'];if(Math.abs(w.result.variance-p.eigenvalues[0])>1e-8)throw Error('Best PC mismatch');});}
 await go('preprocessing-lab');for(const panel of ['Original','Min–max','Standardized','Whitened']){await settings('preprocessing-lab',{panel});await original();}
 console.log('Linkage, PCA and preprocessing configurations checked.');
 // Use actual buttons and keyboard, not just programmatic model changes.
 for(const [id,kind,key]of [['source-animation','frames','frame'],['kmeans-lab','kmeans',null],['gmm-lab','gmm','iteration']]){await go(id);await page.click(`#${id} [data-action="reset"]`);await settle();await page.click(`#${id} [data-action="step"]`);await settle();assert.equal(await page.evaluate(({kind,key})=>{const w=C2Widgets.instances.find(w=>w.kind===kind);return key?w.num(key):w.cursor;},{kind,key}),1);await page.click(`#${id} [data-action="reset"]`);await settle();await page.click(`#${id} [data-action="play"]`);await delay(900);await page.click(`#${id} [data-action="play"]`);await settle();assert(await page.evaluate(({kind,key})=>{const w=C2Widgets.instances.find(w=>w.kind===kind);return (key?w.num(key):w.cursor)>0&&w.timer===null;},{kind,key}));await page.click(`#${id} [data-action="play"]`);await go('map');assert.equal(await page.evaluate(kind=>C2Widgets.instances.find(w=>w.kind===kind).timer,kind),null);interactions.push(id+': step, reset, playback, pause and pause on exit');}
 for(const [id,key]of [['gmm-lab','iteration'],['hierarchy-lab','merges'],['pca-lab','angle']]){await go(id);await page.focus(`#${id} [data-setting="${key}"]`);await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await settle();assert.equal(await page.$eval(`#${id} [data-output="${key}"]`,e=>e.textContent),await page.$eval(`#${id} [data-setting="${key}"]`,e=>e.value));interactions.push(id+': keyboard slider');}
 const ids=await page.evaluate(()=>C2Widgets.instances.map(w=>w.el.closest('section').id));
 for(const id of ids){await go(id);await page.click(`#${id} [data-action="view"]`);await settle();const home=await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice());await page.click(`#${id} [data-action="pan"]`);await settle();assert.equal(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.dragmode),'pan');await page.click(`#${id} [data-action="zoom"]`);await settle();const p=await page.$eval(`#${id} .rg-plot`,p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return{x:b.left+(a._offset+a._length*.2)*s,y:b.top+(y._offset+y._length*.2)*s,xx:b.left+(a._offset+a._length*.65)*s,yy:b.top+(y._offset+y._length*.7)*s};});await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.xx,p.yy,{steps:7});await page.mouse.up();await delay(100);assert.notDeepEqual(await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice()),home);await page.click(`#${id} [data-action="view"]`);await settle();const restored=await page.$eval(`#${id} .rg-plot`,p=>p._fullLayout.xaxis.range.slice());restored.forEach((v,i)=>assert(Math.abs(v-home[i])<1e-5,id+': reset mismatch'));interactions.push(id+': pan, real pointer zoom, reset');}
 await go('scale-source');await page.click('#scale-source .legend .traces:first-child');await delay(350);assert.equal(await page.$eval('#scale-source .rg-plot',p=>p.data[0].visible),'legendonly');interactions.push('Original trace legend toggle');
 await go('data-lab');const h=await page.$eval('#data-lab .rg-plot',p=>{const b=p.getBoundingClientRect(),a=p._fullLayout.xaxis,y=p._fullLayout.yaxis,s=b.width/p._fullLayout.width;return {x:b.left+(a._offset+a.l2p(p.data[0].x[0]))*s,y:b.top+(y._offset+y.l2p(p.data[0].y[0]))*s};});await page.mouse.move(h.x,h.y);await delay(150);assert(await page.$('#data-lab .hoverlayer .hovertext'));interactions.push('Original observation tooltip');
 // Save representative final and alternate states for review.
 fs.mkdirSync(path.join(out,'states'),{recursive:true});for(const [id,obj]of [['source-animation',{frame:4}],['kmeans-lab',{k:4,seed:0}],['selection-lab',{k:3,view:'Silhouette'}],['gmm-lab',{iteration:40,point:120}],['hierarchy-lab',{linkage:'complete',merges:4}],['pca-lab',{data:'Rotated',angle:30}],['preprocessing-lab',{panel:'Whitened'}]]){await go(id);await settings(id,obj);await page.screenshot({path:path.join(out,'states',id+'.png')});}
 await page.evaluate(()=>{document.activeElement.blur();Reveal.slide(0);});for(let i=1;i<count;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>Reveal.getIndices().h),count-1);for(const id of ['source-animation','gmm-lab','pca-lab','references']){await page.goto('about:blank');await page.goto(url+'#/'+id,{waitUntil:'load'});await page.waitForFunction(id=>Reveal.isReady()&&Reveal.getCurrentSlide().id===id,{},id);await page.evaluate(()=>deckReady);}
 const report={count,errors,offlineRequests:network,slides,responsive,stateIssues,stateCount,interactions,keyboardNavigation:true,directEntry:true};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({count,errors,network,issues:slides.filter(s=>s.issues.length),responsive,stateIssues:stateIssues.slice(0,8),stateIssueCount:stateIssues.length,stateCount,interactions:interactions.length},null,2));
 const files=slides.map((s,i)=>`${String(i+1).padStart(2,'0')}-${s.slide}.png`);fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><title>AIML · Clustering · Gallery</title><style>body{margin:0;background:#0b0f17;color:#e8ecf4;font:18px system-ui}header{padding:24px}a{color:#45d6c0}img{display:block;width:100%;height:auto}figure{margin:0 0 30px}figcaption{padding:12px 24px}@media print{@page{size:1920px 1080px;margin:0}header,figcaption{display:none}figure{margin:0;break-after:page}img{height:1080px}}</style><header>Lesson 7 · Clustering · ${count} slides · static previews<br><a href="../index.html">Open interactive presentation</a></header>${files.map((f,i)=>`<figure><img src="${f}" alt="Slide ${i+1}: ${slides[i].slide}"><figcaption>${i+1} / ${count} · ${slides[i].slide}</figcaption></figure>`).join('')}</html>`);await page.goto(pathToFileURL(path.join(out,'index.html')).href,{waitUntil:'load'});await page.pdf({path:path.join(out,'AIML-Clustering-reviewed.pdf'),printBackground:true,preferCSSPageSize:true});assert.equal(errors.length+network.length+slides.filter(s=>s.issues.length).length+responsive.length+stateIssues.length,0,'Inspect audit.json for issues');
};
