const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const puppeteer=require(path.join(process.env.LOCALAPPDATA,'Temp/node_modules/puppeteer-core'));
const audit=require('./audit-function.js'),root=path.resolve(__dirname,'..'),out=path.join(root,'_review'),delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,pipe:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage();await page.setViewport({width:1920,height:1080});const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));await page.setRequestInterception(true);page.on('request',r=>{if(/^https?:/.test(r.url())){network.push(r.url());r.abort();}else r.continue();});const url=pathToFileURL(path.join(root,'index.html')).href;await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>Reveal.isReady());await page.evaluate(async()=>{await deckReady;Reveal.configure({transition:'none'});});
 async function settle(){await page.evaluate(async()=>{C2Widgets.resize();await Promise.all(C2Widgets.instances.map(w=>w.ready));});await delay(30);}
 async function go(id){await page.evaluate(id=>Reveal.slide(Reveal.getSlides().findIndex(s=>s.id===id)),id);await settle();}
 async function check(){const a=await page.evaluate(audit),extra=await page.evaluate(()=>{const issues=[];for(const p of Reveal.getCurrentSlide().querySelectorAll('.rg-plot')){const b=p.getBoundingClientRect(),labels=[...p.querySelectorAll('.xtick text,.ytick text,.g-xtitle text,.g-ytitle text,.legendtext')].map(t=>({b:t.getBoundingClientRect(),text:t.textContent}));for(const {b:r,text}of labels)if(r.width&&r.height&&(r.left<b.left-2||r.right>b.right+2||r.top<b.top-2||r.bottom>b.bottom+2))issues.push({type:'chart-label-clipping',label:text});for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],c=labels[j];if(Math.min(a.b.right,c.b.right)-Math.max(a.b.left,c.b.left)>2&&Math.min(a.b.bottom,c.b.bottom)-Math.max(a.b.top,c.b.top)>2)issues.push({type:'chart-label-overlap',a:a.text,b:c.text});}}return issues;});a.issues.push(...extra);return a;}
 const count=await page.evaluate(()=>Reveal.getTotalSlides()),slides=[];for(let i=0;i<count;i++){await page.evaluate(i=>Reveal.slide(i),i);await settle();const s=await check();slides.push(s);await page.screenshot({path:path.join(out,`${String(i+1).padStart(2,'0')}-${s.slide}.png`)});}fs.writeFileSync(path.join(out,'initial-audit.json'),JSON.stringify({count,errors,network,slides},null,2));console.log(JSON.stringify({stage:'rendered',count,errors,issues:slides.filter(s=>s.issues.length)},null,2));if(process.argv.includes('--quick'))return;

await require('./interaction-review.js')({page,go,settle,check,count,slides,errors,network,root,out,url,delay});
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
